// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
/**
 * GENERATED by `make tygo` from backend/internal/api. DO NOT EDIT.
 *
 * The Go types are the single source of truth for the API contract
 * (docs/07-IMPLEMENTATION-PLAN.md I3). `make check` fails if this file is
 * stale, which is what makes Go/TypeScript payload drift impossible --
 * docs/03-API-CONTRACT.md:265 calls that "the most likely silent bug in
 * this architecture".
 *
 * Money and quantity fields are typed `string` deliberately.
 */

//////////
// source: commerce.go

export interface Supplier {
  id: string;
  name: string;
  tax_id?: string | null;
  contact?: string | null;
  region?: string | null;
  rating?: number | null;
  version: number /* int32 */;
}
export interface SupplierWriteRequest {
  name: string;
  tax_id?: string;
  contact?: string;
  region?: string;
  rating?: number /* int32 */;
}
export interface PurchaseOrderRow {
  id: string;
  po_no: string;
  supplier_id: string;
  supplier_name: string;
  expected_at?: string | null;
  total: string;
  status: Status;
  version: number /* int32 */;
  created_at: string;
}
/**
 * PurchaseOrder is the detail payload. Fields repeated rather than embedded —
 * see the note on ManufacturingOrder.
 */
export interface PurchaseOrder {
  id: string;
  po_no: string;
  supplier_id: string;
  supplier_name: string;
  expected_at?: string | null;
  total: string;
  status: Status;
  version: number /* int32 */;
  created_at: string;
  lines: PurchaseOrderLine[];
  /**
   * AllowedTransitions is what this actor may move the order to next, given the
   * current status and their procurement:approve grant.
   */
  allowed_transitions: string[];
}
export interface PurchaseOrderLine {
  id: string;
  item_id: string;
  sku: string;
  item_name: string;
  qty: string;
  received_qty: string;
  unit_price: string;
  line_total: string;
}
export interface PurchaseOrderLineWrite {
  item_id: string;
  qty: string;
  unit_price: string;
}
export interface PurchaseOrderWriteRequest {
  po_no: string;
  supplier_id: string;
  expected_at?: string;
  lines: PurchaseOrderLineWrite[];
}
/**
 * TransitionRequest moves a document to a new status. Shared by purchase orders
 * and sales orders, which have different matrices but the same request shape.
 */
export interface TransitionRequest {
  to: string;
}
export interface GoodsReceiptLineWrite {
  po_line_id: string;
  qty: string;
  batch_id?: string;
}
export interface GoodsReceiptRequest {
  location_id: string;
  note?: string;
  lines: GoodsReceiptLineWrite[];
}
export interface GoodsReceipt {
  id: string;
  po_id: string;
  received_at: string;
}
export interface SalesOrderRow {
  id: string;
  so_no: string;
  customer_id: string;
  customer_name: string;
  ordered_on?: string | null;
  total: string;
  status: Status;
  version: number /* int32 */;
  created_at: string;
}
/**
 * SalesOrder is the detail payload. Fields repeated rather than embedded — see
 * the note on ManufacturingOrder.
 */
export interface SalesOrder {
  id: string;
  so_no: string;
  customer_id: string;
  customer_name: string;
  ordered_on?: string | null;
  total: string;
  status: Status;
  version: number /* int32 */;
  created_at: string;
  lines: SalesOrderLine[];
}
export interface SalesOrderLine {
  id: string;
  item_id: string;
  sku: string;
  item_name: string;
  batch_id?: string | null;
  batch_no?: string | null;
  qty: string;
  unit_price: string;
  line_total: string;
}
export interface SalesOrderLineWrite {
  item_id: string;
  batch_id?: string;
  qty: string;
  unit_price: string;
}
export interface SalesOrderWriteRequest {
  so_no: string;
  customer_id: string;
  ordered_on?: string;
  lines: SalesOrderLineWrite[];
}
/**
 * ConfirmOrderRequest names the location the stock leaves from. Confirmation is
 * the moment the company commits, so it is also the moment the released-batch
 * rule and the stock check apply (docs/05-MODULES.md §9).
 */
export interface ConfirmOrderRequest {
  location_id: string;
}
export interface Shipment {
  id: string;
  trip_no: string;
  route_from?: string | null;
  route_to?: string | null;
  driver_id?: string | null;
  driver_name?: string | null;
  vehicle_id?: string | null;
  vehicle_plate?: string | null;
  transport_cost?: string | null;
  status: Status;
  version: number /* int32 */;
  created_at: string;
  lines: ShipmentLine[];
}
export interface ShipmentLine {
  id: string;
  item_id: string;
  sku: string;
  item_name: string;
  batch_id: string;
  batch_no: string;
  qty: string;
}
export interface ShipmentWriteRequest {
  trip_no: string;
  route_from?: string;
  route_to?: string;
  driver_id?: string;
  vehicle_id?: string;
  transport_cost?: string;
}
/**
 * ShipmentLoadRequest loads one batch onto a trip. The batch must be released —
 * checked in Go, because a lorry leaving with quarantined product is the failure
 * this whole chain exists to prevent.
 */
export interface ShipmentLoadRequest {
  item_id: string;
  batch_id: string;
  qty: string;
}
export interface Inquiry {
  id: string;
  reference_no: string;
  type: Status;
  name: string;
  company?: string | null;
  contact: string;
  message?: string | null;
  batch_id?: string | null;
  batch_no?: string | null;
  status: Status;
  submitted_at: string;
  version: number /* int32 */;
}
/**
 * InquirySubmitRequest is the only request shape an unauthenticated caller can
 * send. Everything here is untrusted: it is length-bounded, type-checked and
 * rate-limited by IP before a row is written.
 */
export interface InquirySubmitRequest {
  type: string;
  name: string;
  company?: string;
  contact: string;
  message?: string;
  batch_id?: string;
}
/**
 * InquiryReceipt is what the website shows the visitor. Deliberately minimal: the
 * reference number and nothing that could confirm what else is in the database.
 */
export interface InquiryReceipt {
  reference_no: string;
}
export interface Lead {
  id: string;
  name: string;
  source?: string | null;
  status: Status;
}
export interface RoleDetail {
  id: string;
  key: string;
  name: string;
  permissions: string[];
  user_count: number /* int64 */;
  version: number /* int32 */;
}
export interface RoleWriteRequest {
  key: string;
  name: string;
}
export interface RolePermissionsRequest {
  permissions: string[];
}
export interface UserRolesRequest {
  role_ids: string[];
}
export interface UserActiveRequest {
  active: boolean;
}
export interface AdminUserRow {
  id: string;
  email: string;
  full_name: string;
  is_active: boolean;
  status: Status;
  roles: string[];
  version: number /* int32 */;
}
/**
 * PermissionCatalogue is every resource:action the system recognises, so the role
 * editor is generated from the enforced list rather than a hand-kept copy that
 * could drift from it.
 */
export interface PermissionCatalogue {
  resources: PermissionResource[];
}
export interface PermissionResource {
  key: string;
  actions: string[];
}
export interface Notification {
  id: string;
  kind: string;
  resource: string;
  resource_id?: string | null;
  level: string;
  title: string;
  body?: string | null;
  occurred_at: string;
  is_read: boolean;
}
/**
 * AlertFeed is the bell: persisted events plus the live standing conditions, and
 * the counts that drive the sidebar pills. Both come from one endpoint so the
 * bell and the sidebar cannot disagree.
 */
export interface AlertFeed {
  notifications: Notification[];
  conditions: AlertCondition[];
  unread: number /* int */;
  /**
   * Counts is resource → number of open items, for the nav pills.
   */
  counts: { [key: string]: number /* int */};
}
export interface AlertCondition {
  kind: string;
  resource: string;
  level: string;
  count: number /* int */;
}
export interface Employee {
  id: string;
  full_name: string;
  position_id?: string | null;
  position_title?: string | null;
  department?: string | null;
  shift?: string | null;
  hired_on?: string | null;
  contract_until?: string | null;
  status: Status;
  version: number /* int32 */;
}
/**
 * Version is a POINTER on every write request: an absent version must be a
 * validation error, not a silent zero that overwrites whatever the record now
 * holds. See common.RequireVersion.
 */
export interface EmployeeWriteRequest {
  full_name: string;
  position_id?: string;
  shift?: string;
  hired_on?: string;
  contract_until?: string;
  status: string;
  version?: number /* int32 */;
}
export interface Asset {
  id: string;
  asset_no: string;
  name: string;
  asset_type?: string | null;
  line?: string | null;
  commissioned_on?: string | null;
  warranty_until?: string | null;
  next_due_on?: string | null;
  last_service_at?: string | null;
  status: Status;
  version: number /* int32 */;
}
export interface AssetWriteRequest {
  asset_no: string;
  name: string;
  asset_type?: string;
  line?: string;
  commissioned_on?: string;
  warranty_until?: string;
  status: string;
  version?: number /* int32 */;
}
export interface MaintenanceEvent {
  id: string;
  asset_id: string;
  event_type?: string | null;
  performed_at?: string | null;
  next_due_on?: string | null;
  notes?: string | null;
}
export interface MaintenanceWriteRequest {
  event_type?: string;
  performed_at?: string;
  next_due_on?: string;
  notes?: string;
}
export interface Document {
  id: string;
  doc_no: string;
  title: string;
  doc_type?: string | null;
  owner_id?: string | null;
  owner_name?: string | null;
  valid_until?: string | null;
  status: Status;
  version: number /* int32 */;
  /**
   * AllowedTransitions is what this actor may do next. Activation needs
   * documents:approve, so the button set differs per user.
   */
  allowed_transitions: string[];
}
export interface DocumentWriteRequest {
  doc_no: string;
  title: string;
  doc_type?: string;
  owner_id?: string;
  valid_until?: string;
  version?: number /* int32 */;
}

//////////
// source: operations.go

export interface Location {
  id: string;
  code: string;
  name: string;
  zone: string;
}
/**
 * StockBalanceRow is one position in the warehouse list. `OnHand` is a SUM
 * computed at read time; there is no column behind it (CLAUDE.md §4.2).
 */
export interface StockBalanceRow {
  item_id: string;
  sku: string;
  item_name: string;
  base_uom: string;
  batch_id?: string | null;
  batch_no?: string | null;
  batch_status?: Status | null;
  expires_on?: string | null;
  location_id: string;
  location_code: string;
  location_zone: string;
  on_hand: string;
  min_qty?: string | null;
  status: Status;
  last_movement_at?: string | null;
}
/**
 * StockMovementRow is one line of the ledger, with the balance after it.
 */
export interface StockMovementRow {
  id: string;
  occurred_at: string;
  qty_delta: string;
  running_balance: string;
  reason: Status;
  ref_type?: string | null;
  ref_id?: string | null;
  note?: string | null;
  created_by?: string | null;
}
export interface MovementWriteRequest {
  item_id: string;
  batch_id?: string;
  location_id: string;
  qty_delta: string;
  reason: string;
  note?: string;
}
export interface TransferRequest {
  item_id: string;
  batch_id?: string;
  from_location_id: string;
  to_location_id: string;
  qty: string;
  note?: string;
}
export interface ManufacturingOrderRow {
  id: string;
  mo_no: string;
  item_id: string;
  sku: string;
  item_name: string;
  batch_id?: string | null;
  batch_no?: string | null;
  line?: string | null;
  scheduled_for?: string | null;
  planned_qty: string;
  good_qty: string;
  scrap_qty: string;
  status: Status;
  version: number /* int32 */;
  created_at: string;
}
/**
 * ManufacturingOrder is the detail payload.
 * The list row's fields are repeated rather than embedded. Go's encoding/json
 * FLATTENS an embedded struct, but tygo emits it as a nested field — so an
 * embedded row would generate TypeScript describing a shape the API never sends,
 * which is exactly the silent Go/TS drift the generated types exist to prevent.
 */
export interface ManufacturingOrder {
  id: string;
  mo_no: string;
  item_id: string;
  sku: string;
  item_name: string;
  batch_id?: string | null;
  batch_no?: string | null;
  line?: string | null;
  scheduled_for?: string | null;
  planned_qty: string;
  good_qty: string;
  scrap_qty: string;
  status: Status;
  version: number /* int32 */;
  created_at: string;
  /**
   * Progress is good ÷ planned as a whole percentage, capped at 100 for display.
   * Computed here so the two frontends cannot disagree about rounding.
   */
  progress: number /* int */;
  /**
   * Yield is good ÷ (good + scrap). Null rather than 0 when nothing has run:
   * "0% yield" and "not started" read very differently on a shift report.
   */
  yield_percent?: string | null;
  downtime_min: number /* int64 */;
  entries: ProductionEntry[];
}
export interface ProductionEntry {
  id: string;
  recorded_at: string;
  good_qty: string;
  scrap_qty: string;
  downtime_min: number /* int32 */;
  note?: string | null;
  recorded_by?: string | null;
}
export interface ManufacturingOrderWriteRequest {
  mo_no: string;
  item_id: string;
  batch_no: string;
  planned_qty: string;
  scheduled_for?: string;
  line?: string;
}
export interface ProductionEntryWriteRequest {
  good_qty: string;
  scrap_qty?: string;
  downtime_min?: number /* int32 */;
  note?: string;
}
export interface QualityTest {
  id: string;
  batch_id: string;
  test_type: string;
  result: Status;
  result_value?: string | null;
  tested_at: string;
  inspector_id?: string | null;
  inspector?: string | null;
  notes?: string | null;
}
export interface QualityTestWriteRequest {
  test_type: string;
  result_value?: string;
  passed?: boolean;
  notes?: string;
}
/**
 * BatchListRow is one row of the Качество list.
 * TestCount and FailedCount are carried so the list can show at a glance which
 * batches have been examined and which failed — the two facts a QC lead scans
 * for before opening anything.
 */
export interface BatchListRow {
  id: string;
  batch_no: string;
  item_id: string;
  sku: string;
  item_name: string;
  produced_on?: string | null;
  expires_on?: string | null;
  test_count: number /* int32 */;
  failed_count: number /* int32 */;
  status: Status;
  version: number /* int32 */;
}
/**
 * BatchStatusEvent is immutable evidence: who decided, when, and why. It has no
 * version and no deleted_at, so there is nothing here to edit.
 */
export interface BatchStatusEvent {
  id: string;
  from_status?: Status | null;
  to_status: Status;
  occurred_at: string;
  decided_by: string;
  decider_name?: string | null;
  reason?: string | null;
}
/**
 * BatchTransitionRequest moves a batch. `to` is the destination status; the
 * legality of the move and whether it needs quality:approve are decided in Go.
 */
export interface BatchTransitionRequest {
  to: string;
  reason?: string;
}
/**
 * BatchDetail is the traceability view: the batch, its tests, its status history
 * and where its stock currently sits.
 */
export interface BatchDetail {
  batch: Batch;
  sku: string;
  item_name: string;
  tests: QualityTest[];
  history: BatchStatusEvent[];
  stock: StockBalanceRow[];
  /**
   * AllowedTransitions is what this user may do next, given the current status
   * and their permissions. The frontend renders buttons from it rather than
   * re-implementing the transition matrix (docs/04-RBAC.md — hiding is not
   * enforcement, but showing an impossible button is a bug too).
   */
  allowed_transitions: string[];
}

//////////
// source: types.go
/*
Package api holds every payload type the HTTP layer sends or receives.

These Go types are the SINGLE SOURCE OF TRUTH for the API contract. The
TypeScript in packages/types is generated from this package by tygo, and
`make check` fails if the generated output is stale
(docs/07-IMPLEMENTATION-PLAN.md I3).

That matters because docs/03-API-CONTRACT.md:265 names drift between the Go and
TypeScript payload shapes as "the most likely silent bug in this architecture".
Generating one from the other makes the drift structurally impossible rather
than merely discouraged.

Rules for anything added here:
  - Money and quantities are `common.Money` / `common.Quantity`, which
    serialise as STRINGS. Never float64, never int cents (CLAUDE.md §4.6).
  - Timestamps are strings in RFC 3339 UTC.
  - Status fields are `common.Status`: the backend decides the semantic level,
    never a React component (docs/03-API-CONTRACT.md:177).
  - Every mutable resource carries `version` for optimistic concurrency (§7).
*/

/**
 * PageMeta is the metadata on every collection response.
 */
export interface PageMeta {
  page: number /* int */;
  per_page: number /* int */;
  total: number /* int64 */;
  total_pages: number /* int */;
}
/**
 * FieldError is one entry in an error's details array. The frontend switches on
 * Code, never on Message (docs/03-API-CONTRACT.md:116).
 */
export interface FieldError {
  field: string;
  code: string;
  message: string;
}
/**
 * APIError is the body of every error response, at every status code.
 */
export interface APIError {
  code: string;
  message: string;
  details?: FieldError[];
}
/**
 * ErrorEnvelope wraps APIError, matching the wire shape exactly.
 */
export interface ErrorEnvelope {
  error: APIError;
}
/**
 * Status drives the prototype's coloured tags. Per docs/07 C3 the frontend
 * renders the label from its i18n dictionary keyed on Key; Label is the Russian
 * fallback for a missing key.
 */
export interface Status {
  key: string;
  label: string;
  level: string; // ok | warn | danger | info | neutral
}
export interface LoginRequest {
  email: string;
  password: string;
}
/**
 * LoginResponse carries the opaque session token for the BFF to put in an
 * httpOnly cookie. The API never sets a cookie itself (docs/07 I8).
 */
export interface LoginResponse {
  token: string;
  user: User;
}
/**
 * Role is one of the caller's roles.
 * Names are carried in all three languages rather than pre-localised, because a
 * role name is CONTENT, not UI chrome (CLAUDE.md §6) — administrators create
 * roles and name them. docs/02-SCHEMA.md:56 makes `roles` one of two deliberate
 * exceptions to the sibling-translation-table rule for exactly this reason, and
 * the frontend picks the column matching the interface language.
 */
export interface Role {
  key: string;
  name_ru: string;
  name_tg: string;
  name_en: string;
}
/**
 * User is the caller's own identity, as returned by /auth/me.
 */
export interface User {
  id: string;
  email: string;
  full_name: string;
  roles: Role[];
  /**
   * Permissions is the flat "resource:action" list the CRM uses to hide nav
   * entries and buttons. Hiding is presentation only — the server still enforces
   * every request (docs/04-RBAC.md:120).
   */
  permissions: string[];
}
/**
 * ItemTranslation is the per-locale content for an item. Null fields render
 * «уточняется» until the client's recipes are lab-verified (docs/02-SCHEMA.md:176).
 */
export interface ItemTranslation {
  name: string;
  description?: string | null;
  ingredients?: string | null;
  nutrition?: string | null;
  storage_conditions?: string | null;
  after_opening?: string | null;
}
/**
 * PackagingUnit is a selling unit of an item. A case is a unit, not a product:
 * WAT-500 × 24 is a packaging unit of WAT-500, not a separate SKU (D8).
 */
export interface PackagingUnit {
  code: string;
  qty_in_base: string;
  barcode?: string | null; // EAN-13, null pending register Q4
}
export interface Price {
  amount: string;
  currency: string;
  valid_from: string;
  valid_to?: string | null;
}
/**
 * Item is a product-master record. status = "active" IS the website publication
 * state; there is no separate publication flag (docs/02-SCHEMA.md:141).
 */
export interface Item {
  id: string;
  sku: string;
  item_type: string; // finished_good | raw_material | packaging
  category?: string | null;
  base_uom: string;
  shelf_life_days?: number | null;
  min_qty?: string | null;
  translations: { [key: string]: ItemTranslation};
  packaging_units: PackagingUnit[];
  current_price?: Price | null;
  price_history: Price[];
  status: Status;
  version: number /* int32 */;
  created_at: string;
  updated_at: string;
}
/**
 * ItemListRow is one row of the Товары list. Deliberately narrower than Item:
 * the columns are SKU · Наименование · Категория · Упаковка · Цена · Срок годн. ·
 * Статус (docs/05-MODULES.md:85), and sending full translation sets and price
 * history for 50 rows would be wasted bytes on a Khorog connection.
 */
export interface ItemListRow {
  id: string;
  sku: string;
  /**
   * Name is already resolved to the requested locale, falling back to Russian
   * and then to the SKU. A list needs one label, not a translation set.
   */
  name: string;
  item_type: string;
  category?: string | null;
  base_uom: string;
  packaging_codes: string[];
  shelf_life_days?: number | null;
  current_price?: Price | null;
  status: Status;
  version: number /* int32 */;
}
/**
 * ItemTranslationWrite is the per-locale content on create and update.
 * Ingredients, Nutrition and the rest may be omitted: docs/02-SCHEMA.md:176
 * requires them to stay null until the client's recipes are lab-verified, and
 * the UI renders «уточняется». The system must not publish unverified claims.
 */
export interface ItemTranslationWrite {
  name: string;
  description?: string;
  ingredients?: string;
  nutrition?: string;
  storage_conditions?: string;
  after_opening?: string;
}
/**
 * PackagingUnitWrite defines a selling unit. QtyInBase is a STRING for the same
 * reason every quantity is (docs/03-API-CONTRACT.md:147).
 */
export interface PackagingUnitWrite {
  code: string;
  qty_in_base: string;
  barcode?: string;
}
/**
 * ItemWriteRequest is the create and update payload.
 * SKU and ItemType are ignored on update: changing either once batches and stock
 * movements reference the item would rewrite history other records point at.
 */
export interface ItemWriteRequest {
  /**
   * Version is required on PATCH and absent on POST
   * (docs/03-API-CONTRACT.md §7).
   */
  version?: number /* int32 */;
  sku: string;
  item_type: string;
  category?: string;
  base_uom: string;
  shelf_life_days?: number /* int32 */;
  min_qty?: string;
  status: string;
  translations: { [key: string]: ItemTranslationWrite};
  packaging_units: PackagingUnitWrite[];
}
/**
 * PriceWriteRequest adds a price. Prices are never overwritten: the new one
 * supersedes the open one and the history is kept.
 */
export interface PriceWriteRequest {
  amount: string;
  currency: string;
  valid_from: string;
  valid_to?: string;
}
/**
 * BatchWriteRequest creates a planned batch.
 * There is no status field, deliberately: a batch starts `in_production` and only
 * quality events move it (docs/02-SCHEMA.md:197). Offering a status here would
 * let production staff mark their own output released.
 */
export interface BatchWriteRequest {
  batch_no: string;
  item_id: string;
  produced_on?: string;
  expires_on?: string;
}
/**
 * Batch is the traceability spine.
 */
export interface Batch {
  id: string;
  batch_no: string;
  item_id: string;
  produced_on?: string | null;
  expires_on?: string | null;
  /**
   * QRPayload is the URL printed onto the wrapper. Null until issued; once
   * issued it never changes, because wrappers are ordered against it (D11).
   */
  qr_payload?: string | null;
  qr_issued_at?: string | null;
  status: Status;
  version: number /* int32 */;
  created_at: string;
}
