// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
/**
 * GENERATED by `make tygo` from backend/internal/api. DO NOT EDIT.
 *
 * The Go types are the single source of truth for the API contract
 * (docs/07-IMPLEMENTATION-PLAN.md I3). `make check` fails if this file is
 * stale, which is what makes Go/TypeScript payload drift impossible --
 * docs/03-API-CONTRACT.md:265 calls that "the most likely silent bug in
 * this architecture".
 *
 * Money and quantity fields are typed `string` deliberately.
 */

//////////
// source: types.go
/*
Package api holds every payload type the HTTP layer sends or receives.

These Go types are the SINGLE SOURCE OF TRUTH for the API contract. The
TypeScript in packages/types is generated from this package by tygo, and
`make check` fails if the generated output is stale
(docs/07-IMPLEMENTATION-PLAN.md I3).

That matters because docs/03-API-CONTRACT.md:265 names drift between the Go and
TypeScript payload shapes as "the most likely silent bug in this architecture".
Generating one from the other makes the drift structurally impossible rather
than merely discouraged.

Rules for anything added here:
  - Money and quantities are `common.Money` / `common.Quantity`, which
    serialise as STRINGS. Never float64, never int cents (CLAUDE.md §4.6).
  - Timestamps are strings in RFC 3339 UTC.
  - Status fields are `common.Status`: the backend decides the semantic level,
    never a React component (docs/03-API-CONTRACT.md:177).
  - Every mutable resource carries `version` for optimistic concurrency (§7).
*/

/**
 * PageMeta is the metadata on every collection response.
 */
export interface PageMeta {
  page: number /* int */;
  per_page: number /* int */;
  total: number /* int64 */;
  total_pages: number /* int */;
}
/**
 * FieldError is one entry in an error's details array. The frontend switches on
 * Code, never on Message (docs/03-API-CONTRACT.md:116).
 */
export interface FieldError {
  field: string;
  code: string;
  message: string;
}
/**
 * APIError is the body of every error response, at every status code.
 */
export interface APIError {
  code: string;
  message: string;
  details?: FieldError[];
}
/**
 * ErrorEnvelope wraps APIError, matching the wire shape exactly.
 */
export interface ErrorEnvelope {
  error: APIError;
}
/**
 * Status drives the prototype's coloured tags. Per docs/07 C3 the frontend
 * renders the label from its i18n dictionary keyed on Key; Label is the Russian
 * fallback for a missing key.
 */
export interface Status {
  key: string;
  label: string;
  level: string; // ok | warn | danger | info | neutral
}
export interface LoginRequest {
  email: string;
  password: string;
}
/**
 * LoginResponse carries the opaque session token for the BFF to put in an
 * httpOnly cookie. The API never sets a cookie itself (docs/07 I8).
 */
export interface LoginResponse {
  token: string;
  user: User;
}
/**
 * Role is one of the caller's roles.
 * Names are carried in all three languages rather than pre-localised, because a
 * role name is CONTENT, not UI chrome (CLAUDE.md §6) — administrators create
 * roles and name them. docs/02-SCHEMA.md:56 makes `roles` one of two deliberate
 * exceptions to the sibling-translation-table rule for exactly this reason, and
 * the frontend picks the column matching the interface language.
 */
export interface Role {
  key: string;
  name_ru: string;
  name_tg: string;
  name_en: string;
}
/**
 * User is the caller's own identity, as returned by /auth/me.
 */
export interface User {
  id: string;
  email: string;
  full_name: string;
  roles: Role[];
  /**
   * Permissions is the flat "resource:action" list the CRM uses to hide nav
   * entries and buttons. Hiding is presentation only — the server still enforces
   * every request (docs/04-RBAC.md:120).
   */
  permissions: string[];
}
/**
 * ItemTranslation is the per-locale content for an item. Null fields render
 * «уточняется» until the client's recipes are lab-verified (docs/02-SCHEMA.md:176).
 */
export interface ItemTranslation {
  name: string;
  description?: string;
  ingredients?: string;
  nutrition?: string;
  storage_conditions?: string;
  after_opening?: string;
}
/**
 * PackagingUnit is a selling unit of an item. A case is a unit, not a product:
 * WAT-500 × 24 is a packaging unit of WAT-500, not a separate SKU (D8).
 */
export interface PackagingUnit {
  code: string;
  qty_in_base: string;
  barcode?: string; // EAN-13, null pending register Q4
}
export interface Price {
  amount: string;
  currency: string;
  valid_from: string;
  valid_to?: string;
}
/**
 * Item is a product-master record. status = "active" IS the website publication
 * state; there is no separate publication flag (docs/02-SCHEMA.md:141).
 */
export interface Item {
  id: string;
  sku: string;
  item_type: string; // finished_good | raw_material | packaging
  category?: string;
  base_uom: string;
  shelf_life_days?: number /* int32 */;
  min_qty?: string;
  translations: { [key: string]: ItemTranslation};
  packaging_units: PackagingUnit[];
  current_price?: Price;
  price_history: Price[];
  status: Status;
  version: number /* int32 */;
  created_at: string;
  updated_at: string;
}
/**
 * ItemListRow is one row of the Товары list. Deliberately narrower than Item:
 * the columns are SKU · Наименование · Категория · Упаковка · Цена · Срок годн. ·
 * Статус (docs/05-MODULES.md:85), and sending full translation sets and price
 * history for 50 rows would be wasted bytes on a Khorog connection.
 */
export interface ItemListRow {
  id: string;
  sku: string;
  /**
   * Name is already resolved to the requested locale, falling back to Russian
   * and then to the SKU. A list needs one label, not a translation set.
   */
  name: string;
  item_type: string;
  category?: string;
  base_uom: string;
  packaging_codes: string[];
  shelf_life_days?: number /* int32 */;
  current_price?: Price;
  status: Status;
  version: number /* int32 */;
}
/**
 * ItemTranslationWrite is the per-locale content on create and update.
 * Ingredients, Nutrition and the rest may be omitted: docs/02-SCHEMA.md:176
 * requires them to stay null until the client's recipes are lab-verified, and
 * the UI renders «уточняется». The system must not publish unverified claims.
 */
export interface ItemTranslationWrite {
  name: string;
  description?: string;
  ingredients?: string;
  nutrition?: string;
  storage_conditions?: string;
  after_opening?: string;
}
/**
 * PackagingUnitWrite defines a selling unit. QtyInBase is a STRING for the same
 * reason every quantity is (docs/03-API-CONTRACT.md:147).
 */
export interface PackagingUnitWrite {
  code: string;
  qty_in_base: string;
  barcode?: string;
}
/**
 * ItemWriteRequest is the create and update payload.
 * SKU and ItemType are ignored on update: changing either once batches and stock
 * movements reference the item would rewrite history other records point at.
 */
export interface ItemWriteRequest {
  /**
   * Version is required on PATCH and absent on POST
   * (docs/03-API-CONTRACT.md §7).
   */
  version?: number /* int32 */;
  sku: string;
  item_type: string;
  category?: string;
  base_uom: string;
  shelf_life_days?: number /* int32 */;
  min_qty?: string;
  status: string;
  translations: { [key: string]: ItemTranslationWrite};
  packaging_units: PackagingUnitWrite[];
}
/**
 * PriceWriteRequest adds a price. Prices are never overwritten: the new one
 * supersedes the open one and the history is kept.
 */
export interface PriceWriteRequest {
  amount: string;
  currency: string;
  valid_from: string;
  valid_to?: string;
}
