// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignRole = `-- name: AssignRole :exec
INSERT INTO user_roles (user_id, role_id, created_by)
VALUES ($1,$2,$3) ON CONFLICT DO NOTHING
`

type AssignRoleParams struct {
	UserID    uuid.UUID
	RoleID    uuid.UUID
	CreatedBy uuid.NullUUID
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.Exec(ctx, assignRole, arg.UserID, arg.RoleID, arg.CreatedBy)
	return err
}

const clearRolePermissions = `-- name: ClearRolePermissions :exec
UPDATE role_permissions SET deleted_at=now() WHERE role_id=$1 AND deleted_at IS NULL
`

func (q *Queries) ClearRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearRolePermissions, roleID)
	return err
}

const clearUserRoles = `-- name: ClearUserRoles :exec
UPDATE user_roles SET deleted_at=now() WHERE user_id=$1 AND deleted_at IS NULL
`

func (q *Queries) ClearUserRoles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUserRoles, userID)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users u WHERE u.deleted_at IS NULL
  AND ($1::text IS NULL
       OR unaccent(lower(u.full_name)) LIKE '%'||unaccent(lower($1))||'%'
       OR lower(u.email) LIKE '%'||lower($1)||'%')
`

func (q *Queries) CountUsers(ctx context.Context, q_ *string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, q_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersHoldingPermission = `-- name: CountUsersHoldingPermission :one
SELECT count(DISTINCT u.id)::int
FROM users u
JOIN user_roles ur ON ur.user_id=u.id AND ur.deleted_at IS NULL
JOIN roles r ON r.id=ur.role_id AND r.deleted_at IS NULL
JOIN role_permissions rp ON rp.role_id=r.id AND rp.deleted_at IS NULL
WHERE u.deleted_at IS NULL AND u.is_active
  AND rp.resource=$1 AND rp.action=$2
  AND ($3::uuid IS NULL OR u.id <> $3)
`

type CountUsersHoldingPermissionParams struct {
	Resource  string
	Action    string
	Excluding uuid.NullUUID
}

// The last-admin guard (docs/04-RBAC.md:147). Counts ACTIVE, non-deleted users
// holding a permission, because a deactivated administrator cannot rescue anyone.
func (q *Queries) CountUsersHoldingPermission(ctx context.Context, arg CountUsersHoldingPermissionParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUsersHoldingPermission, arg.Resource, arg.Action, arg.Excluding)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (key, name_ru, name_tg, name_en, created_by)
VALUES ($1,$2,$3,$4,$5) RETURNING id, key, name_ru, name_tg, name_en, is_system, created_at, updated_at, deleted_at, version, created_by
`

type CreateRoleParams struct {
	Key       string
	NameRu    string
	NameTg    string
	NameEn    string
	CreatedBy uuid.NullUUID
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.Key,
		arg.NameRu,
		arg.NameTg,
		arg.NameEn,
		arg.CreatedBy,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.NameRu,
		&i.NameTg,
		&i.NameEn,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, key, name_ru, name_tg, name_en, is_system, created_at, updated_at, deleted_at, version, created_by FROM roles WHERE id=$1 AND deleted_at IS NULL
`

func (q *Queries) GetRole(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.NameRu,
		&i.NameTg,
		&i.NameEn,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const grantPermission = `-- name: GrantPermission :exec
INSERT INTO role_permissions (role_id, resource, action, created_by)
VALUES ($1,$2,$3,$4) ON CONFLICT DO NOTHING
`

type GrantPermissionParams struct {
	RoleID    uuid.UUID
	Resource  string
	Action    string
	CreatedBy uuid.NullUUID
}

func (q *Queries) GrantPermission(ctx context.Context, arg GrantPermissionParams) error {
	_, err := q.db.Exec(ctx, grantPermission,
		arg.RoleID,
		arg.Resource,
		arg.Action,
		arg.CreatedBy,
	)
	return err
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT id, role_id, resource, action, created_at, updated_at, deleted_at, version, created_by FROM role_permissions WHERE role_id=$1 AND deleted_at IS NULL
ORDER BY resource, action
`

func (q *Queries) ListRolePermissions(ctx context.Context, roleID uuid.UUID) ([]RolePermission, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolePermission{}
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.Resource,
			&i.Action,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many

SELECT r.id, r.key, r.name_ru, r.name_tg, r.name_en, r.is_system, r.created_at, r.updated_at, r.deleted_at, r.version, r.created_by, (SELECT count(*) FROM user_roles ur
             WHERE ur.role_id=r.id AND ur.deleted_at IS NULL)::int AS user_count
FROM roles r WHERE r.deleted_at IS NULL ORDER BY r.is_system DESC, r.key
`

type ListRolesRow struct {
	ID        uuid.UUID
	Key       string
	NameRu    string
	NameTg    string
	NameEn    string
	IsSystem  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Version   int32
	CreatedBy uuid.NullUUID
	UserCount int32
}

// Role management and the audit viewer — docs/04-RBAC.md §6.
func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesRow{}
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.NameRu,
			&i.NameTg,
			&i.NameEn,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithRoles = `-- name: ListUsersWithRoles :many
SELECT u.id, u.email, u.full_name, u.is_active, u.last_login_at,
  COALESCE(ARRAY_AGG(r.key ORDER BY r.key) FILTER (WHERE r.id IS NOT NULL), '{}')::text[] AS role_keys
FROM users u
LEFT JOIN user_roles ur ON ur.user_id=u.id AND ur.deleted_at IS NULL
LEFT JOIN roles r ON r.id=ur.role_id AND r.deleted_at IS NULL
WHERE u.deleted_at IS NULL
  AND ($3::text IS NULL
       OR unaccent(lower(u.full_name)) LIKE '%'||unaccent(lower($3))||'%'
       OR lower(u.email) LIKE '%'||lower($3)||'%')
GROUP BY u.id ORDER BY u.full_name LIMIT $1 OFFSET $2
`

type ListUsersWithRolesParams struct {
	Limit  int32
	Offset int32
	Q      *string
}

type ListUsersWithRolesRow struct {
	ID          uuid.UUID
	Email       string
	FullName    string
	IsActive    bool
	LastLoginAt pgtype.Timestamptz
	RoleKeys    []string
}

func (q *Queries) ListUsersWithRoles(ctx context.Context, arg ListUsersWithRolesParams) ([]ListUsersWithRolesRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithRoles, arg.Limit, arg.Offset, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersWithRolesRow{}
	for rows.Next() {
		var i ListUsersWithRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.IsActive,
			&i.LastLoginAt,
			&i.RoleKeys,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :one
UPDATE users SET is_active=$2 WHERE id=$1 AND deleted_at IS NULL RETURNING id, email, full_name, password_hash, is_active, last_login_at, failed_attempts, locked_until, created_at, updated_at, deleted_at, version, created_by
`

type SetUserActiveParams struct {
	ID       uuid.UUID
	IsActive bool
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserActive, arg.ID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.IsActive,
		&i.LastLoginAt,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const tombstoneRole = `-- name: TombstoneRole :one
UPDATE roles SET deleted_at=now()
WHERE id=$1 AND deleted_at IS NULL AND is_system=false RETURNING id, key, name_ru, name_tg, name_en, is_system, created_at, updated_at, deleted_at, version, created_by
`

// Seed roles are is_system and cannot be deleted (D9); the guard is in the WHERE
// clause so it holds regardless of caller.
func (q *Queries) TombstoneRole(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, tombstoneRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.NameRu,
		&i.NameTg,
		&i.NameEn,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}
