// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const analyticsDaysNeedingRollup = `-- name: AnalyticsDaysNeedingRollup :many
SELECT DISTINCT (occurred_at AT TIME ZONE 'UTC')::date AS day
FROM analytics_events
WHERE occurred_at < date_trunc('day', now())
ORDER BY day
`

// Every day that has raw events, oldest first, excluding today — a day is only
// rolled up once it is complete.
func (q *Queries) AnalyticsDaysNeedingRollup(ctx context.Context) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, analyticsDaysNeedingRollup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var day pgtype.Date
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const analyticsVisitTotals = `-- name: AnalyticsVisitTotals :one
SELECT
  COALESCE(sum(d.session_count) FILTER (WHERE d.kind = 'page_view'), 0)::int    AS visits,
  COALESCE(sum(d.session_count) FILTER (WHERE d.kind = 'product_view'), 0)::int AS product_visits
FROM analytics_daily d
WHERE d.day >= $1::date
`

type AnalyticsVisitTotalsRow struct {
	Visits        int32
	ProductVisits int32
}

// The headline: how many visits, and how many of them looked at a product.
func (q *Queries) AnalyticsVisitTotals(ctx context.Context, since pgtype.Date) (AnalyticsVisitTotalsRow, error) {
	row := q.db.QueryRow(ctx, analyticsVisitTotals, since)
	var i AnalyticsVisitTotalsRow
	err := row.Scan(&i.Visits, &i.ProductVisits)
	return i, err
}

const countAnalyticsEventsSince = `-- name: CountAnalyticsEventsSince :one

SELECT count(*)::int FROM analytics_events
WHERE ip_hash = $1 AND occurred_at >= now() - $2::interval
`

type CountAnalyticsEventsSinceParams struct {
	IpHash   string
	Lookback pgtype.Interval
}

// First-party website analytics (docs/01-DECISIONS.md D12).
// The ingestion rate limit, counted per batch rather than per event because the
// client buffers and flushes (D12). At click volume a per-event count would be
// a scan; per batch it is the same order as the inquiry limiter.
func (q *Queries) CountAnalyticsEventsSince(ctx context.Context, arg CountAnalyticsEventsSinceParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAnalyticsEventsSince, arg.IpHash, arg.Lookback)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAnalyticsEventsBefore = `-- name: DeleteAnalyticsEventsBefore :execrows

DELETE FROM analytics_events WHERE occurred_at < $1::timestamptz
`

// ---------------------------------------------------------------------------
// Retention
// ---------------------------------------------------------------------------
// A real DELETE, not a tombstone (D12). A soft-deleted row still contains the
// session id.
func (q *Queries) DeleteAnalyticsEventsBefore(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnalyticsEventsBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAnalyticsEvent = `-- name: InsertAnalyticsEvent :exec
INSERT INTO analytics_events
  (occurred_at, session_id, kind, target, item_id, source, category, locale, ip_hash)
VALUES (COALESCE($9::timestamptz, now()), $1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAnalyticsEventParams struct {
	SessionID  string
	Kind       string
	Target     string
	ItemID     uuid.NullUUID
	Source     *string
	Category   *string
	Locale     string
	IpHash     string
	OccurredAt pgtype.Timestamptz
}

// No RETURNING: nothing downstream needs the id, and the endpoint answers 204
// regardless of what happened (D12).
func (q *Queries) InsertAnalyticsEvent(ctx context.Context, arg InsertAnalyticsEventParams) error {
	_, err := q.db.Exec(ctx, insertAnalyticsEvent,
		arg.SessionID,
		arg.Kind,
		arg.Target,
		arg.ItemID,
		arg.Source,
		arg.Category,
		arg.Locale,
		arg.IpHash,
		arg.OccurredAt,
	)
	return err
}

const itemIDBySKU = `-- name: ItemIDBySKU :one
SELECT id FROM items WHERE sku = $1 AND deleted_at IS NULL
`

// Target validation. A product_view naming a SKU that is not in the catalogue is
// dropped, which is what stops the ranking being forged: the worst a prober can
// do is inflate something that genuinely exists.
func (q *Queries) ItemIDBySKU(ctx context.Context, sku string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, itemIDBySKU, sku)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const lastAnalyticsMaintenanceRun = `-- name: LastAnalyticsMaintenanceRun :one
SELECT id, ran_at, days_rolled_up, rows_deleted, oldest_surviving FROM analytics_maintenance_runs ORDER BY ran_at DESC LIMIT 1
`

// Drives the boot warning: a ticker that dies silently must be distinguishable
// from one that is working.
func (q *Queries) LastAnalyticsMaintenanceRun(ctx context.Context) (AnalyticsMaintenanceRun, error) {
	row := q.db.QueryRow(ctx, lastAnalyticsMaintenanceRun)
	var i AnalyticsMaintenanceRun
	err := row.Scan(
		&i.ID,
		&i.RanAt,
		&i.DaysRolledUp,
		&i.RowsDeleted,
		&i.OldestSurviving,
	)
	return i, err
}

const oldestAnalyticsEvent = `-- name: OldestAnalyticsEvent :one
SELECT min(occurred_at)::timestamptz FROM analytics_events
`

func (q *Queries) OldestAnalyticsEvent(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, oldestAnalyticsEvent)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const recordAnalyticsMaintenanceRun = `-- name: RecordAnalyticsMaintenanceRun :one
INSERT INTO analytics_maintenance_runs (days_rolled_up, rows_deleted, oldest_surviving)
VALUES ($1, $2, $3) RETURNING id, ran_at, days_rolled_up, rows_deleted, oldest_surviving
`

type RecordAnalyticsMaintenanceRunParams struct {
	DaysRolledUp    int32
	RowsDeleted     int32
	OldestSurviving pgtype.Date
}

func (q *Queries) RecordAnalyticsMaintenanceRun(ctx context.Context, arg RecordAnalyticsMaintenanceRunParams) (AnalyticsMaintenanceRun, error) {
	row := q.db.QueryRow(ctx, recordAnalyticsMaintenanceRun, arg.DaysRolledUp, arg.RowsDeleted, arg.OldestSurviving)
	var i AnalyticsMaintenanceRun
	err := row.Scan(
		&i.ID,
		&i.RanAt,
		&i.DaysRolledUp,
		&i.RowsDeleted,
		&i.OldestSurviving,
	)
	return i, err
}

const rollUpAnalyticsDay = `-- name: RollUpAnalyticsDay :execrows

INSERT INTO analytics_daily
  (day, kind, target, item_id, category, locale, event_count, session_count)
SELECT
  $1::date,
  e.kind,
  e.target,
  -- One target maps to at most one item, so any non-null one will do. Postgres
  -- has no min(uuid), and array_agg with a FILTER is the idiomatic "pick one".
  (array_agg(e.item_id) FILTER (WHERE e.item_id IS NOT NULL))[1],
  min(e.category),
  e.locale,
  count(*)::int,
  count(DISTINCT e.session_id)::int
FROM analytics_events e
WHERE e.occurred_at >= $1::date
  AND e.occurred_at <  $1::date + INTERVAL '1 day'
GROUP BY e.kind, e.target, e.locale
ON CONFLICT (day, kind, target, locale) DO UPDATE
SET event_count   = EXCLUDED.event_count,
    session_count = EXCLUDED.session_count,
    item_id       = EXCLUDED.item_id,
    category      = EXCLUDED.category
`

// ---------------------------------------------------------------------------
// The nightly rollup
// ---------------------------------------------------------------------------
// Collapses one day into (kind, target, locale) with an event count and a
// DISTINCT SESSION count. Idempotent — re-running a day overwrites it rather
// than doubling it, which matters because the CLI exists so a missed day can be
// caught up.
func (q *Queries) RollUpAnalyticsDay(ctx context.Context, day pgtype.Date) (int64, error) {
	result, err := q.db.Exec(ctx, rollUpAnalyticsDay, day)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const topLinksByVisits = `-- name: TopLinksByVisits :many
SELECT d.target,
       -- Cast for the same reason as migration 00005: sqlc types a bare
       -- aggregate as interface{}, unusable without an assertion per call site.
       COALESCE(max(d.category), 'cta')::text AS category,
       sum(d.session_count)::int AS visits,
       sum(d.event_count)::int   AS clicks
FROM analytics_daily d
WHERE d.kind = 'link_click'
  AND d.category IN ('cta', 'outbound')
  AND d.day >= $2::date
GROUP BY d.target
ORDER BY visits DESC, clicks DESC
LIMIT $1
`

type TopLinksByVisitsParams struct {
	Limit int32
	Since pgtype.Date
}

type TopLinksByVisitsRow struct {
	Target   string
	Category string
	Visits   int32
	Clicks   int32
}

// `cta` and `outbound` only. Nav and footer are captured but never shown: they
// always win on volume and tell the owner nothing (D12).
func (q *Queries) TopLinksByVisits(ctx context.Context, arg TopLinksByVisitsParams) ([]TopLinksByVisitsRow, error) {
	rows, err := q.db.Query(ctx, topLinksByVisits, arg.Limit, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopLinksByVisitsRow{}
	for rows.Next() {
		var i TopLinksByVisitsRow
		if err := rows.Scan(
			&i.Target,
			&i.Category,
			&i.Visits,
			&i.Clicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topProductsByVisits = `-- name: TopProductsByVisits :many

SELECT d.target AS sku,
       COALESCE(max(t.name), d.target)::text AS name,
       sum(d.session_count)::int AS visits,
       sum(d.event_count)::int   AS views
FROM analytics_daily d
LEFT JOIN item_translations t
  ON t.item_id = d.item_id AND t.locale = $2::text AND t.deleted_at IS NULL
WHERE d.kind = 'product_view'
  AND d.day >= $3::date
GROUP BY d.target
ORDER BY visits DESC, views DESC
LIMIT $1
`

type TopProductsByVisitsParams struct {
	Limit  int32
	Locale string
	Since  pgtype.Date
}

type TopProductsByVisitsRow struct {
	Sku    string
	Name   string
	Visits int32
	Views  int32
}

// ---------------------------------------------------------------------------
// The dashboard panels
//
// Both read analytics_daily, never the raw table: the raw rows are gone after 90
// days and the panel must keep working. Ranked by SESSION count — ten views in
// one session are one visit (D12).
// ---------------------------------------------------------------------------
func (q *Queries) TopProductsByVisits(ctx context.Context, arg TopProductsByVisitsParams) ([]TopProductsByVisitsRow, error) {
	rows, err := q.db.Query(ctx, topProductsByVisits, arg.Limit, arg.Locale, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopProductsByVisitsRow{}
	for rows.Next() {
		var i TopProductsByVisitsRow
		if err := rows.Scan(
			&i.Sku,
			&i.Name,
			&i.Visits,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
