// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAudit = `-- name: CountAudit :one
SELECT count(*) FROM audit_log
WHERE ($1::uuid IS NULL OR actor_id = $1)
  AND ($2::text IS NULL OR resource = $2)
  AND ($3::uuid IS NULL OR resource_id = $3)
  AND ($4::timestamptz IS NULL OR occurred_at >= $4)
  AND ($5::timestamptz IS NULL OR occurred_at <= $5)
`

type CountAuditParams struct {
	ActorID    uuid.NullUUID
	Resource   *string
	ResourceID uuid.NullUUID
	FromTs     pgtype.Timestamptz
	ToTs       pgtype.Timestamptz
}

func (q *Queries) CountAudit(ctx context.Context, arg CountAuditParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAudit,
		arg.ActorID,
		arg.Resource,
		arg.ResourceID,
		arg.FromTs,
		arg.ToTs,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditForResource = `-- name: CountAuditForResource :one
SELECT count(*) FROM audit_log
WHERE resource = $1 AND resource_id = $2
`

type CountAuditForResourceParams struct {
	Resource   string
	ResourceID uuid.NullUUID
}

func (q *Queries) CountAuditForResource(ctx context.Context, arg CountAuditForResourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditForResource, arg.Resource, arg.ResourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditEntry = `-- name: InsertAuditEntry :one

INSERT INTO audit_log (actor_id, action, resource, resource_id, before, after, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, actor_id, action, resource, resource_id, before, after, ip, occurred_at
`

type InsertAuditEntryParams struct {
	ActorID    uuid.NullUUID
	Action     string
	Resource   string
	ResourceID uuid.NullUUID
	Before     []byte
	After      []byte
	Ip         *netip.Addr
}

// Audit log. Append-only: there is no update and no delete, by design
// (docs/02-SCHEMA.md:123). Every mutation in the system writes one row, inside
// the mutating transaction (docs/07-IMPLEMENTATION-PLAN.md I4).
func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditEntry,
		arg.ActorID,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Before,
		arg.After,
		arg.Ip,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.Resource,
		&i.ResourceID,
		&i.Before,
		&i.After,
		&i.Ip,
		&i.OccurredAt,
	)
	return i, err
}

const listAudit = `-- name: ListAudit :many
SELECT id, actor_id, action, resource, resource_id, before, after, ip, occurred_at FROM audit_log
WHERE ($3::uuid IS NULL OR actor_id = $3)
  AND ($4::text IS NULL OR resource = $4)
  AND ($5::uuid IS NULL OR resource_id = $5)
  AND ($6::timestamptz IS NULL OR occurred_at >= $6)
  AND ($7::timestamptz IS NULL OR occurred_at <= $7)
ORDER BY occurred_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListAuditParams struct {
	Limit      int32
	Offset     int32
	ActorID    uuid.NullUUID
	Resource   *string
	ResourceID uuid.NullUUID
	FromTs     pgtype.Timestamptz
	ToTs       pgtype.Timestamptz
}

// The audit viewer (docs/04-RBAC.md §6), filterable by actor, resource and date
// range. NULL means "no filter" for each dimension.
func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAudit,
		arg.Limit,
		arg.Offset,
		arg.ActorID,
		arg.Resource,
		arg.ResourceID,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Before,
			&i.After,
			&i.Ip,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditForResource = `-- name: ListAuditForResource :many
SELECT id, actor_id, action, resource, resource_id, before, after, ip, occurred_at FROM audit_log
WHERE resource = $1 AND resource_id = $2
ORDER BY occurred_at DESC, id DESC
LIMIT $3 OFFSET $4
`

type ListAuditForResourceParams struct {
	Resource   string
	ResourceID uuid.NullUUID
	Limit      int32
	Offset     int32
}

// Powers the activity panel on every detail view (docs/05-MODULES.md §2).
func (q *Queries) ListAuditForResource(ctx context.Context, arg ListAuditForResourceParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditForResource,
		arg.Resource,
		arg.ResourceID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Before,
			&i.After,
			&i.Ip,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
