// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cms.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMedia = `-- name: CountMedia :one
SELECT count(*) FROM media WHERE deleted_at IS NULL
  AND ($1::text IS NULL
       OR unaccent(lower(file_path)) LIKE '%'||unaccent(lower($1))||'%'
       OR unaccent(lower(COALESCE(alt_ru,''))) LIKE '%'||unaccent(lower($1))||'%')
`

func (q *Queries) CountMedia(ctx context.Context, q_ *string) (int64, error) {
	row := q.db.QueryRow(ctx, countMedia, q_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNewsPosts = `-- name: CountNewsPosts :one
SELECT count(*) FROM news_posts n
LEFT JOIN news_post_translations tr
  ON tr.post_id = n.id AND tr.locale = $1::text AND tr.deleted_at IS NULL
LEFT JOIN news_post_translations ru
  ON ru.post_id = n.id AND ru.locale = 'ru' AND ru.deleted_at IS NULL
WHERE n.deleted_at IS NULL
  AND ($2::text IS NULL OR n.status = $2)
  AND ($3::text IS NULL
       OR unaccent(lower(n.slug)) LIKE '%'||unaccent(lower($3))||'%'
       OR unaccent(lower(COALESCE(tr.title, ru.title, ''))) LIKE '%'||unaccent(lower($3))||'%')
`

type CountNewsPostsParams struct {
	Locale string
	Status *string
	Q      *string
}

func (q *Queries) CountNewsPosts(ctx context.Context, arg CountNewsPostsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNewsPosts, arg.Locale, arg.Status, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContentPage = `-- name: CreateContentPage :one
INSERT INTO content_pages (key, created_by) VALUES ($1, $2) RETURNING id, key, status, published_at, published_by, created_at, updated_at, deleted_at, version, created_by
`

type CreateContentPageParams struct {
	Key       string
	CreatedBy uuid.NullUUID
}

func (q *Queries) CreateContentPage(ctx context.Context, arg CreateContentPageParams) (ContentPage, error) {
	row := q.db.QueryRow(ctx, createContentPage, arg.Key, arg.CreatedBy)
	var i ContentPage
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Status,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (file_path, mime_type, width, height, size_bytes, alt_ru, alt_tg, alt_en, uploaded_by, created_by)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$9) RETURNING id, file_path, mime_type, width, height, size_bytes, alt_ru, alt_tg, alt_en, uploaded_by, created_at, updated_at, deleted_at, version, created_by
`

type CreateMediaParams struct {
	FilePath   string
	MimeType   string
	Width      *int32
	Height     *int32
	SizeBytes  *int64
	AltRu      *string
	AltTg      *string
	AltEn      *string
	UploadedBy uuid.NullUUID
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.FilePath,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
		arg.AltRu,
		arg.AltTg,
		arg.AltEn,
		arg.UploadedBy,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.AltRu,
		&i.AltTg,
		&i.AltEn,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const createNewsPost = `-- name: CreateNewsPost :one
INSERT INTO news_posts (slug, category, published_on, created_by)
VALUES ($1, $2, $3, $4) RETURNING id, slug, category, published_on, cover_media_id, status, created_at, updated_at, deleted_at, version, created_by
`

type CreateNewsPostParams struct {
	Slug        string
	Category    *string
	PublishedOn pgtype.Date
	CreatedBy   uuid.NullUUID
}

func (q *Queries) CreateNewsPost(ctx context.Context, arg CreateNewsPostParams) (NewsPost, error) {
	row := q.db.QueryRow(ctx, createNewsPost,
		arg.Slug,
		arg.Category,
		arg.PublishedOn,
		arg.CreatedBy,
	)
	var i NewsPost
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Category,
		&i.PublishedOn,
		&i.CoverMediaID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getContentPage = `-- name: GetContentPage :one
SELECT id, key, status, published_at, published_by, created_at, updated_at, deleted_at, version, created_by FROM content_pages WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetContentPage(ctx context.Context, id uuid.UUID) (ContentPage, error) {
	row := q.db.QueryRow(ctx, getContentPage, id)
	var i ContentPage
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Status,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getContentPageByKey = `-- name: GetContentPageByKey :one
SELECT id, key, status, published_at, published_by, created_at, updated_at, deleted_at, version, created_by FROM content_pages WHERE key = $1 AND deleted_at IS NULL
`

func (q *Queries) GetContentPageByKey(ctx context.Context, key string) (ContentPage, error) {
	row := q.db.QueryRow(ctx, getContentPageByKey, key)
	var i ContentPage
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Status,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getNewsPost = `-- name: GetNewsPost :one
SELECT id, slug, category, published_on, cover_media_id, status, created_at, updated_at, deleted_at, version, created_by FROM news_posts WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetNewsPost(ctx context.Context, id uuid.UUID) (NewsPost, error) {
	row := q.db.QueryRow(ctx, getNewsPost, id)
	var i NewsPost
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Category,
		&i.PublishedOn,
		&i.CoverMediaID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const insertWorkflowEvent = `-- name: InsertWorkflowEvent :one

INSERT INTO content_workflow_events (entity_type, entity_id, from_status, to_status, actor_id, comment)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, entity_type, entity_id, from_status, to_status, actor_id, comment, occurred_at, created_at
`

type InsertWorkflowEventParams struct {
	EntityType string
	EntityID   uuid.UUID
	FromStatus *string
	ToStatus   string
	ActorID    uuid.UUID
	Comment    *string
}

// ---------------------------------------------------------------------------
// Workflow history
// ---------------------------------------------------------------------------
// Immutable evidence of who moved what, and when. No deleted_at and no version:
// there is nothing here to edit.
func (q *Queries) InsertWorkflowEvent(ctx context.Context, arg InsertWorkflowEventParams) (ContentWorkflowEvent, error) {
	row := q.db.QueryRow(ctx, insertWorkflowEvent,
		arg.EntityType,
		arg.EntityID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorID,
		arg.Comment,
	)
	var i ContentWorkflowEvent
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.FromStatus,
		&i.ToStatus,
		&i.ActorID,
		&i.Comment,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listContentBlocks = `-- name: ListContentBlocks :many
SELECT b.id, b.page_id, b.block_key, b.sort_order, b.created_at, b.updated_at, b.deleted_at, b.version, b.created_by, t.heading, t.body, t.cta_label
FROM content_blocks b
LEFT JOIN content_block_translations t
  ON t.block_id = b.id AND t.locale = $2::text AND t.deleted_at IS NULL
WHERE b.page_id = $1 AND b.deleted_at IS NULL
ORDER BY b.sort_order, b.block_key
`

type ListContentBlocksParams struct {
	PageID uuid.UUID
	Locale string
}

type ListContentBlocksRow struct {
	ID        uuid.UUID
	PageID    uuid.UUID
	BlockKey  string
	SortOrder int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Version   int32
	CreatedBy uuid.NullUUID
	Heading   *string
	Body      *string
	CtaLabel  *string
}

// Every block with its translation in one locale. LEFT JOIN, so a block whose
// translation is missing still appears — an editor cannot fill in a gap they
// cannot see.
func (q *Queries) ListContentBlocks(ctx context.Context, arg ListContentBlocksParams) ([]ListContentBlocksRow, error) {
	rows, err := q.db.Query(ctx, listContentBlocks, arg.PageID, arg.Locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContentBlocksRow{}
	for rows.Next() {
		var i ListContentBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.BlockKey,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
			&i.Heading,
			&i.Body,
			&i.CtaLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentPages = `-- name: ListContentPages :many


SELECT p.id, p.key, p.status, p.published_at, p.published_by, p.created_at, p.updated_at, p.deleted_at, p.version, p.created_by,
  (SELECT count(*) FROM content_blocks b
    WHERE b.page_id = p.id AND b.deleted_at IS NULL)::int AS block_count
FROM content_pages p
WHERE p.deleted_at IS NULL
  AND ($1::text IS NULL OR p.status = $1)
ORDER BY p.key
`

type ListContentPagesRow struct {
	ID          uuid.UUID
	Key         string
	Status      string
	PublishedAt pgtype.Timestamptz
	PublishedBy uuid.NullUUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	Version     int32
	CreatedBy   uuid.NullUUID
	BlockCount  int32
}

// CMS — docs/05-MODULES.md §15.
//
// The public site renders only `published`; the CRM can preview any state. That
// asymmetry is the module's whole reason for existing, so every read here is
// explicit about which side it serves.
// ---------------------------------------------------------------------------
// Pages and blocks
// ---------------------------------------------------------------------------
func (q *Queries) ListContentPages(ctx context.Context, status *string) ([]ListContentPagesRow, error) {
	rows, err := q.db.Query(ctx, listContentPages, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContentPagesRow{}
	for rows.Next() {
		var i ListContentPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Status,
			&i.PublishedAt,
			&i.PublishedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
			&i.BlockCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedia = `-- name: ListMedia :many

SELECT id, file_path, mime_type, width, height, size_bytes, alt_ru, alt_tg, alt_en, uploaded_by, created_at, updated_at, deleted_at, version, created_by FROM media WHERE deleted_at IS NULL
  AND ($3::text IS NULL
       OR unaccent(lower(file_path)) LIKE '%'||unaccent(lower($3))||'%'
       OR unaccent(lower(COALESCE(alt_ru,''))) LIKE '%'||unaccent(lower($3))||'%')
ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListMediaParams struct {
	Limit  int32
	Offset int32
	Q      *string
}

// ---------------------------------------------------------------------------
// Media
// ---------------------------------------------------------------------------
func (q *Queries) ListMedia(ctx context.Context, arg ListMediaParams) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMedia, arg.Limit, arg.Offset, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.AltRu,
			&i.AltTg,
			&i.AltEn,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsPosts = `-- name: ListNewsPosts :many

SELECT n.id, n.slug, n.category, n.published_on, n.cover_media_id, n.status, n.created_at, n.updated_at, n.deleted_at, n.version, n.created_by, COALESCE(tr.title, ru.title) AS title
FROM news_posts n
LEFT JOIN news_post_translations tr
  ON tr.post_id = n.id AND tr.locale = $3::text AND tr.deleted_at IS NULL
LEFT JOIN news_post_translations ru
  ON ru.post_id = n.id AND ru.locale = 'ru' AND ru.deleted_at IS NULL
WHERE n.deleted_at IS NULL
  AND ($4::text IS NULL OR n.status = $4)
  AND ($5::text IS NULL
       OR unaccent(lower(n.slug)) LIKE '%'||unaccent(lower($5))||'%'
       OR unaccent(lower(COALESCE(tr.title, ru.title, ''))) LIKE '%'||unaccent(lower($5))||'%')
ORDER BY n.published_on DESC NULLS FIRST, n.created_at DESC
LIMIT $1 OFFSET $2
`

type ListNewsPostsParams struct {
	Limit  int32
	Offset int32
	Locale string
	Status *string
	Q      *string
}

type ListNewsPostsRow struct {
	ID           uuid.UUID
	Slug         string
	Category     *string
	PublishedOn  pgtype.Date
	CoverMediaID uuid.NullUUID
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	Version      int32
	CreatedBy    uuid.NullUUID
	Title        string
}

// ---------------------------------------------------------------------------
// News
// ---------------------------------------------------------------------------
func (q *Queries) ListNewsPosts(ctx context.Context, arg ListNewsPostsParams) ([]ListNewsPostsRow, error) {
	rows, err := q.db.Query(ctx, listNewsPosts,
		arg.Limit,
		arg.Offset,
		arg.Locale,
		arg.Status,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNewsPostsRow{}
	for rows.Next() {
		var i ListNewsPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Category,
			&i.PublishedOn,
			&i.CoverMediaID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsTranslations = `-- name: ListNewsTranslations :many
SELECT id, post_id, locale, title, excerpt, body, created_at, updated_at, deleted_at, version, created_by FROM news_post_translations
WHERE post_id = $1 AND deleted_at IS NULL ORDER BY locale
`

func (q *Queries) ListNewsTranslations(ctx context.Context, postID uuid.UUID) ([]NewsPostTranslation, error) {
	rows, err := q.db.Query(ctx, listNewsTranslations, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsPostTranslation{}
	for rows.Next() {
		var i NewsPostTranslation
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Locale,
			&i.Title,
			&i.Excerpt,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowEvents = `-- name: ListWorkflowEvents :many
SELECT e.id, e.entity_type, e.entity_id, e.from_status, e.to_status, e.actor_id, e.comment, e.occurred_at, e.created_at, u.full_name AS actor_name
FROM content_workflow_events e
JOIN users u ON u.id = e.actor_id
WHERE e.entity_type = $1 AND e.entity_id = $2
ORDER BY e.occurred_at DESC
`

type ListWorkflowEventsParams struct {
	EntityType string
	EntityID   uuid.UUID
}

type ListWorkflowEventsRow struct {
	ID         uuid.UUID
	EntityType string
	EntityID   uuid.UUID
	FromStatus *string
	ToStatus   string
	ActorID    uuid.UUID
	Comment    *string
	OccurredAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	ActorName  string
}

func (q *Queries) ListWorkflowEvents(ctx context.Context, arg ListWorkflowEventsParams) ([]ListWorkflowEventsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowEvents, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkflowEventsRow{}
	for rows.Next() {
		var i ListWorkflowEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ActorID,
			&i.Comment,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionContentPage = `-- name: TransitionContentPage :one
UPDATE content_pages
SET status = $2::text,
    published_at = CASE WHEN $2::text = 'published' THEN now() ELSE published_at END,
    published_by = CASE WHEN $2::text = 'published' THEN $3::uuid ELSE published_by END
WHERE id = $1 AND deleted_at IS NULL AND status = $4::text
RETURNING id, key, status, published_at, published_by, created_at, updated_at, deleted_at, version, created_by
`

type TransitionContentPageParams struct {
	ID         uuid.UUID
	ToStatus   string
	Actor      uuid.NullUUID
	FromStatus string
}

// Guarded on the current status, so a concurrent move cannot slip between the
// caller's read and this write.
func (q *Queries) TransitionContentPage(ctx context.Context, arg TransitionContentPageParams) (ContentPage, error) {
	row := q.db.QueryRow(ctx, transitionContentPage,
		arg.ID,
		arg.ToStatus,
		arg.Actor,
		arg.FromStatus,
	)
	var i ContentPage
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Status,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const transitionNewsPost = `-- name: TransitionNewsPost :one
UPDATE news_posts SET status = $2::text
WHERE id = $1 AND deleted_at IS NULL AND status = $3::text
RETURNING id, slug, category, published_on, cover_media_id, status, created_at, updated_at, deleted_at, version, created_by
`

type TransitionNewsPostParams struct {
	ID         uuid.UUID
	ToStatus   string
	FromStatus string
}

func (q *Queries) TransitionNewsPost(ctx context.Context, arg TransitionNewsPostParams) (NewsPost, error) {
	row := q.db.QueryRow(ctx, transitionNewsPost, arg.ID, arg.ToStatus, arg.FromStatus)
	var i NewsPost
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Category,
		&i.PublishedOn,
		&i.CoverMediaID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const updateMediaAlt = `-- name: UpdateMediaAlt :one
UPDATE media SET alt_ru = $2, alt_tg = $3, alt_en = $4
WHERE id = $1 AND deleted_at IS NULL AND version = $5 RETURNING id, file_path, mime_type, width, height, size_bytes, alt_ru, alt_tg, alt_en, uploaded_by, created_at, updated_at, deleted_at, version, created_by
`

type UpdateMediaAltParams struct {
	ID      uuid.UUID
	AltRu   *string
	AltTg   *string
	AltEn   *string
	Version int32
}

func (q *Queries) UpdateMediaAlt(ctx context.Context, arg UpdateMediaAltParams) (Medium, error) {
	row := q.db.QueryRow(ctx, updateMediaAlt,
		arg.ID,
		arg.AltRu,
		arg.AltTg,
		arg.AltEn,
		arg.Version,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.AltRu,
		&i.AltTg,
		&i.AltEn,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const upsertBlockTranslation = `-- name: UpsertBlockTranslation :one
INSERT INTO content_block_translations (block_id, locale, heading, body, cta_label, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (block_id, locale) WHERE deleted_at IS NULL
DO UPDATE SET heading = EXCLUDED.heading, body = EXCLUDED.body, cta_label = EXCLUDED.cta_label
RETURNING id, block_id, locale, heading, body, cta_label, created_at, updated_at, deleted_at, version, created_by
`

type UpsertBlockTranslationParams struct {
	BlockID   uuid.UUID
	Locale    string
	Heading   *string
	Body      *string
	CtaLabel  *string
	CreatedBy uuid.NullUUID
}

func (q *Queries) UpsertBlockTranslation(ctx context.Context, arg UpsertBlockTranslationParams) (ContentBlockTranslation, error) {
	row := q.db.QueryRow(ctx, upsertBlockTranslation,
		arg.BlockID,
		arg.Locale,
		arg.Heading,
		arg.Body,
		arg.CtaLabel,
		arg.CreatedBy,
	)
	var i ContentBlockTranslation
	err := row.Scan(
		&i.ID,
		&i.BlockID,
		&i.Locale,
		&i.Heading,
		&i.Body,
		&i.CtaLabel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const upsertContentBlock = `-- name: UpsertContentBlock :one
INSERT INTO content_blocks (page_id, block_key, sort_order, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (page_id, block_key) WHERE deleted_at IS NULL
DO UPDATE SET sort_order = EXCLUDED.sort_order
RETURNING id, page_id, block_key, sort_order, created_at, updated_at, deleted_at, version, created_by
`

type UpsertContentBlockParams struct {
	PageID    uuid.UUID
	BlockKey  string
	SortOrder int32
	CreatedBy uuid.NullUUID
}

func (q *Queries) UpsertContentBlock(ctx context.Context, arg UpsertContentBlockParams) (ContentBlock, error) {
	row := q.db.QueryRow(ctx, upsertContentBlock,
		arg.PageID,
		arg.BlockKey,
		arg.SortOrder,
		arg.CreatedBy,
	)
	var i ContentBlock
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.BlockKey,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const upsertNewsTranslation = `-- name: UpsertNewsTranslation :one
INSERT INTO news_post_translations (post_id, locale, title, excerpt, body, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (post_id, locale) WHERE deleted_at IS NULL
DO UPDATE SET title = EXCLUDED.title, excerpt = EXCLUDED.excerpt, body = EXCLUDED.body
RETURNING id, post_id, locale, title, excerpt, body, created_at, updated_at, deleted_at, version, created_by
`

type UpsertNewsTranslationParams struct {
	PostID    uuid.UUID
	Locale    string
	Title     string
	Excerpt   *string
	Body      *string
	CreatedBy uuid.NullUUID
}

func (q *Queries) UpsertNewsTranslation(ctx context.Context, arg UpsertNewsTranslationParams) (NewsPostTranslation, error) {
	row := q.db.QueryRow(ctx, upsertNewsTranslation,
		arg.PostID,
		arg.Locale,
		arg.Title,
		arg.Excerpt,
		arg.Body,
		arg.CreatedBy,
	)
	var i NewsPostTranslation
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Locale,
		&i.Title,
		&i.Excerpt,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}
