// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crm.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countCustomers = `-- name: CountCustomers :one
SELECT count(*) FROM customers c
WHERE c.deleted_at IS NULL
  AND ($1::text IS NULL OR c.region = $1)
  AND ($2::text IS NULL
       OR unaccent(lower(c.name)) LIKE '%'||unaccent(lower($2))||'%'
       OR unaccent(lower(COALESCE(c.contact,''))) LIKE '%'||unaccent(lower($2))||'%'
       OR unaccent(lower(COALESCE(c.region,''))) LIKE '%'||unaccent(lower($2))||'%')
`

type CountCustomersParams struct {
	Region *string
	Q      *string
}

func (q *Queries) CountCustomers(ctx context.Context, arg CountCustomersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers, arg.Region, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeals = `-- name: CountDeals :one
SELECT count(*) FROM deals d JOIN customers c ON c.id = d.customer_id
WHERE d.deleted_at IS NULL
  AND ($1::text IS NULL OR d.stage = $1)
  AND ($2::uuid IS NULL OR d.customer_id = $2)
  AND ($3::text IS NULL
       OR unaccent(lower(c.name)) LIKE '%'||unaccent(lower($3))||'%'
       OR unaccent(lower(COALESCE(c.region,''))) LIKE '%'||unaccent(lower($3))||'%')
`

type CountDealsParams struct {
	Stage      *string
	CustomerID uuid.NullUUID
	Q          *string
}

func (q *Queries) CountDeals(ctx context.Context, arg CountDealsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDeals, arg.Stage, arg.CustomerID, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNewLeads = `-- name: CountNewLeads :one
SELECT count(*) FROM leads WHERE status = 'new' AND deleted_at IS NULL
`

func (q *Queries) CountNewLeads(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNewLeads)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenDeals = `-- name: CountOpenDeals :one
SELECT count(*) FROM deals
WHERE stage NOT IN ('won','lost') AND deleted_at IS NULL
`

func (q *Queries) CountOpenDeals(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenDeals)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasks = `-- name: CountTasks :one
SELECT count(*) FROM tasks
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1)
`

func (q *Queries) CountTasks(ctx context.Context, status *string) (int64, error) {
	row := q.db.QueryRow(ctx, countTasks, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (customer_id, full_name, role, email, phone, created_by)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, customer_id, full_name, role, email, phone, created_at, updated_at, deleted_at, version, created_by
`

type CreateContactParams struct {
	CustomerID uuid.UUID
	FullName   string
	Role       *string
	Email      *string
	Phone      *string
	CreatedBy  uuid.NullUUID
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.CustomerID,
		arg.FullName,
		arg.Role,
		arg.Email,
		arg.Phone,
		arg.CreatedBy,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.FullName,
		&i.Role,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const createDeal = `-- name: CreateDeal :one
INSERT INTO deals (customer_id, amount, stage, owner_id, expected_close, created_by)
VALUES ($1, $2, COALESCE($6::text, 'new'), $3, $4, $5)
RETURNING id, customer_id, amount, stage, owner_id, expected_close, created_at, updated_at, deleted_at, version, created_by
`

type CreateDealParams struct {
	CustomerID    uuid.UUID
	Amount        decimal.NullDecimal
	OwnerID       uuid.NullUUID
	ExpectedClose pgtype.Date
	CreatedBy     uuid.NullUUID
	Stage         *string
}

func (q *Queries) CreateDeal(ctx context.Context, arg CreateDealParams) (Deal, error) {
	row := q.db.QueryRow(ctx, createDeal,
		arg.CustomerID,
		arg.Amount,
		arg.OwnerID,
		arg.ExpectedClose,
		arg.CreatedBy,
		arg.Stage,
	)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Amount,
		&i.Stage,
		&i.OwnerID,
		&i.ExpectedClose,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const createDealStageEvent = `-- name: CreateDealStageEvent :one
INSERT INTO deal_stage_events (deal_id, from_stage, to_stage, changed_by, note)
VALUES ($1, $2, $3, $4, $5) RETURNING id, deal_id, from_stage, to_stage, changed_by, note, occurred_at, created_at
`

type CreateDealStageEventParams struct {
	DealID    uuid.UUID
	FromStage *string
	ToStage   string
	ChangedBy uuid.UUID
	Note      *string
}

// Immutable evidence, exactly like batch_status_events: no version, no
// deleted_at, so there is nothing here to edit.
func (q *Queries) CreateDealStageEvent(ctx context.Context, arg CreateDealStageEventParams) (DealStageEvent, error) {
	row := q.db.QueryRow(ctx, createDealStageEvent,
		arg.DealID,
		arg.FromStage,
		arg.ToStage,
		arg.ChangedBy,
		arg.Note,
	)
	var i DealStageEvent
	err := row.Scan(
		&i.ID,
		&i.DealID,
		&i.FromStage,
		&i.ToStage,
		&i.ChangedBy,
		&i.Note,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, assignee_id, due_on, status, related_type, related_id, created_by)
VALUES ($1, $2, $3, 'open', $4, $5, $6) RETURNING id, title, assignee_id, due_on, status, related_type, related_id, created_at, updated_at, deleted_at, version, created_by
`

type CreateTaskParams struct {
	Title       string
	AssigneeID  uuid.NullUUID
	DueOn       pgtype.Date
	RelatedType *string
	RelatedID   uuid.NullUUID
	CreatedBy   uuid.NullUUID
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Title,
		arg.AssigneeID,
		arg.DueOn,
		arg.RelatedType,
		arg.RelatedID,
		arg.CreatedBy,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AssigneeID,
		&i.DueOn,
		&i.Status,
		&i.RelatedType,
		&i.RelatedID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const dealOutcomeCounts = `-- name: DealOutcomeCounts :one
SELECT
  count(*) FILTER (WHERE stage = 'won')::int AS won,
  count(*) FILTER (WHERE stage IN ('won','lost'))::int AS decided
FROM deals WHERE deleted_at IS NULL
`

type DealOutcomeCountsRow struct {
	Won     int32
	Decided int32
}

// Two counts rather than a computed rate.
//
// The ratio is formed in Go so that "nothing has closed yet" can be NULL rather
// than 0: on a sales dashboard those read very differently, and expressing that
// in SQL means fighting sqlc's nullability inference through a cast.
func (q *Queries) DealOutcomeCounts(ctx context.Context) (DealOutcomeCountsRow, error) {
	row := q.db.QueryRow(ctx, dealOutcomeCounts)
	var i DealOutcomeCountsRow
	err := row.Scan(&i.Won, &i.Decided)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, name, customer_type, region, contact, created_at, updated_at, deleted_at, version, created_by FROM customers WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CustomerType,
		&i.Region,
		&i.Contact,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getDeal = `-- name: GetDeal :one
SELECT d.id, d.customer_id, d.amount, d.stage, d.owner_id, d.expected_close, d.created_at, d.updated_at, d.deleted_at, d.version, d.created_by, c.name AS customer_name, u.full_name AS owner_name
FROM deals d
JOIN customers c ON c.id = d.customer_id
LEFT JOIN users u ON u.id = d.owner_id
WHERE d.id = $1 AND d.deleted_at IS NULL
`

type GetDealRow struct {
	Deal         Deal
	CustomerName string
	OwnerName    *string
}

func (q *Queries) GetDeal(ctx context.Context, id uuid.UUID) (GetDealRow, error) {
	row := q.db.QueryRow(ctx, getDeal, id)
	var i GetDealRow
	err := row.Scan(
		&i.Deal.ID,
		&i.Deal.CustomerID,
		&i.Deal.Amount,
		&i.Deal.Stage,
		&i.Deal.OwnerID,
		&i.Deal.ExpectedClose,
		&i.Deal.CreatedAt,
		&i.Deal.UpdatedAt,
		&i.Deal.DeletedAt,
		&i.Deal.Version,
		&i.Deal.CreatedBy,
		&i.CustomerName,
		&i.OwnerName,
	)
	return i, err
}

const listContactsForCustomer = `-- name: ListContactsForCustomer :many
SELECT id, customer_id, full_name, role, email, phone, created_at, updated_at, deleted_at, version, created_by FROM contacts
WHERE customer_id = $1 AND deleted_at IS NULL
ORDER BY full_name
`

func (q *Queries) ListContactsForCustomer(ctx context.Context, customerID uuid.UUID) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContactsForCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.FullName,
			&i.Role,
			&i.Email,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomers = `-- name: ListCustomers :many

SELECT c.id, c.name, c.customer_type, c.region, c.contact, c.created_at, c.updated_at, c.deleted_at, c.version, c.created_by,
  (SELECT count(*) FROM deals d
    WHERE d.customer_id = c.id AND d.deleted_at IS NULL
      AND d.stage NOT IN ('won','lost'))::int AS open_deals,
  (SELECT COALESCE(SUM(d.amount), 0) FROM deals d
    WHERE d.customer_id = c.id AND d.deleted_at IS NULL
      AND d.stage NOT IN ('won','lost'))::numeric(14,2) AS open_amount,
  -- COALESCE, not a bare cast: ` + "`" + `::text` + "`" + ` makes sqlc type the column
  -- non-nullable, and a customer with no leads then fails to scan. The empty
  -- string is the "no lead" case and the handler reads it as such.
  COALESCE((SELECT max(l.status) FROM leads l
    WHERE l.customer_id = c.id AND l.deleted_at IS NULL), '')::text AS lead_status
FROM customers c
WHERE c.deleted_at IS NULL
  AND ($3::text IS NULL OR c.region = $3)
  AND ($4::text IS NULL
       OR unaccent(lower(c.name)) LIKE '%'||unaccent(lower($4))||'%'
       OR unaccent(lower(COALESCE(c.contact,''))) LIKE '%'||unaccent(lower($4))||'%'
       OR unaccent(lower(COALESCE(c.region,''))) LIKE '%'||unaccent(lower($4))||'%')
ORDER BY c.name
LIMIT $1 OFFSET $2
`

type ListCustomersParams struct {
	Limit  int32
	Offset int32
	Region *string
	Q      *string
}

type ListCustomersRow struct {
	Customer   Customer
	OpenDeals  int32
	OpenAmount decimal.Decimal
	LeadStatus string
}

// CRM и продажи — customers, contacts, leads, deals and tasks.
//
// The tables have existed since migration 00003 and were never queried. The
// dashboard's Воронка продаж reads `deals` (inventory.sql:326), so the funnel has
// rendered its empty state since the day it shipped.
func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error) {
	rows, err := q.db.Query(ctx, listCustomers,
		arg.Limit,
		arg.Offset,
		arg.Region,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomersRow{}
	for rows.Next() {
		var i ListCustomersRow
		if err := rows.Scan(
			&i.Customer.ID,
			&i.Customer.Name,
			&i.Customer.CustomerType,
			&i.Customer.Region,
			&i.Customer.Contact,
			&i.Customer.CreatedAt,
			&i.Customer.UpdatedAt,
			&i.Customer.DeletedAt,
			&i.Customer.Version,
			&i.Customer.CreatedBy,
			&i.OpenDeals,
			&i.OpenAmount,
			&i.LeadStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealStageEvents = `-- name: ListDealStageEvents :many
SELECT e.id, e.deal_id, e.from_stage, e.to_stage, e.changed_by, e.note, e.occurred_at, e.created_at, u.full_name AS changed_by_name
FROM deal_stage_events e
LEFT JOIN users u ON u.id = e.changed_by
WHERE e.deal_id = $1
ORDER BY e.occurred_at DESC
`

type ListDealStageEventsRow struct {
	ID            uuid.UUID
	DealID        uuid.UUID
	FromStage     *string
	ToStage       string
	ChangedBy     uuid.UUID
	Note          *string
	OccurredAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	ChangedByName *string
}

func (q *Queries) ListDealStageEvents(ctx context.Context, dealID uuid.UUID) ([]ListDealStageEventsRow, error) {
	rows, err := q.db.Query(ctx, listDealStageEvents, dealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDealStageEventsRow{}
	for rows.Next() {
		var i ListDealStageEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.DealID,
			&i.FromStage,
			&i.ToStage,
			&i.ChangedBy,
			&i.Note,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.ChangedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeals = `-- name: ListDeals :many
SELECT d.id, d.customer_id, d.amount, d.stage, d.owner_id, d.expected_close, d.created_at, d.updated_at, d.deleted_at, d.version, d.created_by, c.name AS customer_name, c.region AS customer_region,
  u.full_name AS owner_name
FROM deals d
JOIN customers c ON c.id = d.customer_id
LEFT JOIN users u ON u.id = d.owner_id
WHERE d.deleted_at IS NULL
  AND ($3::text IS NULL OR d.stage = $3)
  AND ($4::uuid IS NULL OR d.customer_id = $4)
  AND ($5::text IS NULL
       OR unaccent(lower(c.name)) LIKE '%'||unaccent(lower($5))||'%'
       OR unaccent(lower(COALESCE(c.region,''))) LIKE '%'||unaccent(lower($5))||'%')
ORDER BY d.expected_close NULLS LAST, d.created_at DESC
LIMIT $1 OFFSET $2
`

type ListDealsParams struct {
	Limit      int32
	Offset     int32
	Stage      *string
	CustomerID uuid.NullUUID
	Q          *string
}

type ListDealsRow struct {
	Deal           Deal
	CustomerName   string
	CustomerRegion *string
	OwnerName      *string
}

func (q *Queries) ListDeals(ctx context.Context, arg ListDealsParams) ([]ListDealsRow, error) {
	rows, err := q.db.Query(ctx, listDeals,
		arg.Limit,
		arg.Offset,
		arg.Stage,
		arg.CustomerID,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDealsRow{}
	for rows.Next() {
		var i ListDealsRow
		if err := rows.Scan(
			&i.Deal.ID,
			&i.Deal.CustomerID,
			&i.Deal.Amount,
			&i.Deal.Stage,
			&i.Deal.OwnerID,
			&i.Deal.ExpectedClose,
			&i.Deal.CreatedAt,
			&i.Deal.UpdatedAt,
			&i.Deal.DeletedAt,
			&i.Deal.Version,
			&i.Deal.CreatedBy,
			&i.CustomerName,
			&i.CustomerRegion,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealsForCustomer = `-- name: ListDealsForCustomer :many
SELECT d.id, d.customer_id, d.amount, d.stage, d.owner_id, d.expected_close, d.created_at, d.updated_at, d.deleted_at, d.version, d.created_by, u.full_name AS owner_name
FROM deals d LEFT JOIN users u ON u.id = d.owner_id
WHERE d.customer_id = $1 AND d.deleted_at IS NULL
ORDER BY d.created_at DESC
`

type ListDealsForCustomerRow struct {
	Deal      Deal
	OwnerName *string
}

func (q *Queries) ListDealsForCustomer(ctx context.Context, customerID uuid.UUID) ([]ListDealsForCustomerRow, error) {
	rows, err := q.db.Query(ctx, listDealsForCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDealsForCustomerRow{}
	for rows.Next() {
		var i ListDealsForCustomerRow
		if err := rows.Scan(
			&i.Deal.ID,
			&i.Deal.CustomerID,
			&i.Deal.Amount,
			&i.Deal.Stage,
			&i.Deal.OwnerID,
			&i.Deal.ExpectedClose,
			&i.Deal.CreatedAt,
			&i.Deal.UpdatedAt,
			&i.Deal.DeletedAt,
			&i.Deal.Version,
			&i.Deal.CreatedBy,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInquiriesForCustomer = `-- name: ListInquiriesForCustomer :many
SELECT i.id, i.reference_no, i.inquiry_type, i.status, i.created_at
FROM inquiries i
JOIN leads l ON l.inquiry_id = i.id AND l.deleted_at IS NULL
WHERE l.customer_id = $1 AND i.deleted_at IS NULL
ORDER BY i.created_at DESC
`

type ListInquiriesForCustomerRow struct {
	ID          uuid.UUID
	ReferenceNo string
	InquiryType string
	Status      string
	CreatedAt   pgtype.Timestamptz
}

// An enquiry reaches a customer through the lead its conversion created.
func (q *Queries) ListInquiriesForCustomer(ctx context.Context, customerID uuid.NullUUID) ([]ListInquiriesForCustomerRow, error) {
	rows, err := q.db.Query(ctx, listInquiriesForCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInquiriesForCustomerRow{}
	for rows.Next() {
		var i ListInquiriesForCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.ReferenceNo,
			&i.InquiryType,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadsForCustomer = `-- name: ListLeadsForCustomer :many
SELECT id, customer_id, inquiry_id, source, status, created_at, updated_at, deleted_at, version, created_by FROM leads
WHERE customer_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListLeadsForCustomer(ctx context.Context, customerID uuid.NullUUID) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeadsForCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lead{}
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.InquiryID,
			&i.Source,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrdersForCustomer = `-- name: ListSalesOrdersForCustomer :many
SELECT so.id, so.so_no, so.ordered_on, so.status,
  COALESCE((SELECT SUM(l.qty*l.unit_price) FROM sales_order_lines l
            WHERE l.sales_order_id = so.id AND l.deleted_at IS NULL), 0)::numeric(14,2) AS total
FROM sales_orders so
WHERE so.customer_id = $1 AND so.deleted_at IS NULL
ORDER BY so.ordered_on DESC NULLS LAST
`

type ListSalesOrdersForCustomerRow struct {
	ID        uuid.UUID
	SoNo      string
	OrderedOn pgtype.Date
	Status    string
	Total     decimal.Decimal
}

func (q *Queries) ListSalesOrdersForCustomer(ctx context.Context, customerID uuid.UUID) ([]ListSalesOrdersForCustomerRow, error) {
	rows, err := q.db.Query(ctx, listSalesOrdersForCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesOrdersForCustomerRow{}
	for rows.Next() {
		var i ListSalesOrdersForCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.SoNo,
			&i.OrderedOn,
			&i.Status,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT t.id, t.title, t.assignee_id, t.due_on, t.status, t.related_type, t.related_id, t.created_at, t.updated_at, t.deleted_at, t.version, t.created_by, u.full_name AS assignee_name
FROM tasks t LEFT JOIN users u ON u.id = t.assignee_id
WHERE t.deleted_at IS NULL
  AND ($3::text IS NULL OR t.status = $3)
ORDER BY t.due_on NULLS LAST, t.created_at DESC
LIMIT $1 OFFSET $2
`

type ListTasksParams struct {
	Limit  int32
	Offset int32
	Status *string
}

type ListTasksRow struct {
	ID           uuid.UUID
	Title        string
	AssigneeID   uuid.NullUUID
	DueOn        pgtype.Date
	Status       string
	RelatedType  *string
	RelatedID    uuid.NullUUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	Version      int32
	CreatedBy    uuid.NullUUID
	AssigneeName *string
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AssigneeID,
			&i.DueOn,
			&i.Status,
			&i.RelatedType,
			&i.RelatedID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
			&i.AssigneeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDealStage = `-- name: SetDealStage :one
UPDATE deals SET stage = $2, updated_at = now(), version = version + 1
WHERE id = $1 AND deleted_at IS NULL RETURNING id, customer_id, amount, stage, owner_id, expected_close, created_at, updated_at, deleted_at, version, created_by
`

type SetDealStageParams struct {
	ID    uuid.UUID
	Stage string
}

func (q *Queries) SetDealStage(ctx context.Context, arg SetDealStageParams) (Deal, error) {
	row := q.db.QueryRow(ctx, setDealStage, arg.ID, arg.Stage)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Amount,
		&i.Stage,
		&i.OwnerID,
		&i.ExpectedClose,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const setTaskStatus = `-- name: SetTaskStatus :one
UPDATE tasks SET status = $2, updated_at = now(), version = version + 1
WHERE id = $1 AND deleted_at IS NULL RETURNING id, title, assignee_id, due_on, status, related_type, related_id, created_at, updated_at, deleted_at, version, created_by
`

type SetTaskStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetTaskStatus(ctx context.Context, arg SetTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, setTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AssigneeID,
		&i.DueOn,
		&i.Status,
		&i.RelatedType,
		&i.RelatedID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const tombstoneCustomer = `-- name: TombstoneCustomer :one
UPDATE customers SET deleted_at = now(), updated_at = now(), version = version + 1
WHERE id = $1 AND deleted_at IS NULL RETURNING id, name, customer_type, region, contact, created_at, updated_at, deleted_at, version, created_by
`

func (q *Queries) TombstoneCustomer(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, tombstoneCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CustomerType,
		&i.Region,
		&i.Contact,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET name = $2, customer_type = $3, region = $4, contact = $5,
    updated_at = now(), version = version + 1
WHERE id = $1 AND deleted_at IS NULL AND version = $6
RETURNING id, name, customer_type, region, contact, created_at, updated_at, deleted_at, version, created_by
`

type UpdateCustomerParams struct {
	ID           uuid.UUID
	Name         string
	CustomerType *string
	Region       *string
	Contact      *string
	Version      int32
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.Name,
		arg.CustomerType,
		arg.Region,
		arg.Contact,
		arg.Version,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CustomerType,
		&i.Region,
		&i.Contact,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}
