// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inquiries.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countInquiries = `-- name: CountInquiries :one
SELECT count(*) FROM inquiries i WHERE i.deleted_at IS NULL
  AND ($1::text IS NULL OR i.status=$1)
  AND ($2::text IS NULL OR i.inquiry_type=$2)
  AND ($3::text IS NULL
       OR unaccent(lower(i.reference_no)) LIKE '%'||unaccent(lower($3))||'%'
       OR unaccent(lower(i.name)) LIKE '%'||unaccent(lower($3))||'%'
       OR unaccent(lower(COALESCE(i.company,''))) LIKE '%'||unaccent(lower($3))||'%')
`

type CountInquiriesParams struct {
	Status      *string
	InquiryType *string
	Q           *string
}

func (q *Queries) CountInquiries(ctx context.Context, arg CountInquiriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInquiries, arg.Status, arg.InquiryType, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInquiriesSince = `-- name: CountInquiriesSince :one
SELECT count(*)::int FROM inquiries
WHERE source_ip = $1 AND created_at >= now() - $2::interval
`

type CountInquiriesSinceParams struct {
	SourceIp *netip.Addr
	Lookback pgtype.Interval
}

// Rate limiting by IP (docs/03-API-CONTRACT.md:249).
func (q *Queries) CountInquiriesSince(ctx context.Context, arg CountInquiriesSinceParams) (int32, error) {
	row := q.db.QueryRow(ctx, countInquiriesSince, arg.SourceIp, arg.Lookback)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countInquiriesToday = `-- name: CountInquiriesToday :one
SELECT count(*)::int FROM inquiries
WHERE deleted_at IS NULL AND created_at >= CURRENT_DATE
`

func (q *Queries) CountInquiriesToday(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countInquiriesToday)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (name, customer_type, region, contact, created_by)
VALUES ($1,$2,$3,$4,$5) RETURNING id, name, customer_type, region, contact, created_at, updated_at, deleted_at, version, created_by
`

type CreateCustomerParams struct {
	Name         string
	CustomerType *string
	Region       *string
	Contact      *string
	CreatedBy    uuid.NullUUID
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.Name,
		arg.CustomerType,
		arg.Region,
		arg.Contact,
		arg.CreatedBy,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CustomerType,
		&i.Region,
		&i.Contact,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const createInquiry = `-- name: CreateInquiry :one

INSERT INTO inquiries (reference_no, inquiry_type, name, company, contact, message, batch_id, source_ip)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id, reference_no, inquiry_type, name, company, contact, message, batch_id, status, source_ip, created_at, updated_at, deleted_at, version, created_by
`

type CreateInquiryParams struct {
	ReferenceNo string
	InquiryType string
	Name        string
	Company     *string
	Contact     string
	Message     *string
	BatchID     uuid.NullUUID
	SourceIp    *netip.Addr
}

// Интеграция с сайтом — docs/05-MODULES.md §8.
// Written by the PUBLIC website through the same backend.
func (q *Queries) CreateInquiry(ctx context.Context, arg CreateInquiryParams) (Inquiry, error) {
	row := q.db.QueryRow(ctx, createInquiry,
		arg.ReferenceNo,
		arg.InquiryType,
		arg.Name,
		arg.Company,
		arg.Contact,
		arg.Message,
		arg.BatchID,
		arg.SourceIp,
	)
	var i Inquiry
	err := row.Scan(
		&i.ID,
		&i.ReferenceNo,
		&i.InquiryType,
		&i.Name,
		&i.Company,
		&i.Contact,
		&i.Message,
		&i.BatchID,
		&i.Status,
		&i.SourceIp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const createLead = `-- name: CreateLead :one
INSERT INTO leads (customer_id, inquiry_id, source, created_by)
VALUES ($1,$2,$3,$4) RETURNING id, customer_id, inquiry_id, source, status, created_at, updated_at, deleted_at, version, created_by
`

type CreateLeadParams struct {
	CustomerID uuid.NullUUID
	InquiryID  uuid.NullUUID
	Source     *string
	CreatedBy  uuid.NullUUID
}

func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, createLead,
		arg.CustomerID,
		arg.InquiryID,
		arg.Source,
		arg.CreatedBy,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.InquiryID,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getInquiry = `-- name: GetInquiry :one
SELECT id, reference_no, inquiry_type, name, company, contact, message, batch_id, status, source_ip, created_at, updated_at, deleted_at, version, created_by FROM inquiries WHERE id=$1 AND deleted_at IS NULL
`

func (q *Queries) GetInquiry(ctx context.Context, id uuid.UUID) (Inquiry, error) {
	row := q.db.QueryRow(ctx, getInquiry, id)
	var i Inquiry
	err := row.Scan(
		&i.ID,
		&i.ReferenceNo,
		&i.InquiryType,
		&i.Name,
		&i.Company,
		&i.Contact,
		&i.Message,
		&i.BatchID,
		&i.Status,
		&i.SourceIp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getLeadForInquiry = `-- name: GetLeadForInquiry :one
SELECT id, customer_id, inquiry_id, source, status, created_at, updated_at, deleted_at, version, created_by FROM leads WHERE inquiry_id=$1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetLeadForInquiry(ctx context.Context, inquiryID uuid.NullUUID) (Lead, error) {
	row := q.db.QueryRow(ctx, getLeadForInquiry, inquiryID)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.InquiryID,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const listInquiries = `-- name: ListInquiries :many
SELECT i.id, i.reference_no, i.inquiry_type, i.name, i.company, i.contact, i.message, i.batch_id, i.status, i.source_ip, i.created_at, i.updated_at, i.deleted_at, i.version, i.created_by, b.batch_no
FROM inquiries i LEFT JOIN batches b ON b.id=i.batch_id
WHERE i.deleted_at IS NULL
  AND ($3::text IS NULL OR i.status=$3)
  AND ($4::text IS NULL OR i.inquiry_type=$4)
  AND ($5::text IS NULL
       OR unaccent(lower(i.reference_no)) LIKE '%'||unaccent(lower($5))||'%'
       OR unaccent(lower(i.name)) LIKE '%'||unaccent(lower($5))||'%'
       OR unaccent(lower(COALESCE(i.company,''))) LIKE '%'||unaccent(lower($5))||'%')
ORDER BY i.created_at DESC LIMIT $1 OFFSET $2
`

type ListInquiriesParams struct {
	Limit       int32
	Offset      int32
	Status      *string
	InquiryType *string
	Q           *string
}

type ListInquiriesRow struct {
	ID          uuid.UUID
	ReferenceNo string
	InquiryType string
	Name        string
	Company     *string
	Contact     string
	Message     *string
	BatchID     uuid.NullUUID
	Status      string
	SourceIp    *netip.Addr
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	Version     int32
	CreatedBy   uuid.NullUUID
	BatchNo     *string
}

func (q *Queries) ListInquiries(ctx context.Context, arg ListInquiriesParams) ([]ListInquiriesRow, error) {
	rows, err := q.db.Query(ctx, listInquiries,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.InquiryType,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInquiriesRow{}
	for rows.Next() {
		var i ListInquiriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ReferenceNo,
			&i.InquiryType,
			&i.Name,
			&i.Company,
			&i.Contact,
			&i.Message,
			&i.BatchID,
			&i.Status,
			&i.SourceIp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
			&i.BatchNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextInquirySequence = `-- name: NextInquirySequence :one
SELECT COALESCE(MAX(SUBSTRING(reference_no FROM '[0-9]+$')::int), 0)::int + 1 AS next
FROM inquiries WHERE reference_no LIKE $1::text || '%'
`

// A sequence per prefix. SELECT ... FOR UPDATE on the max row would still race on
// an empty table, so the uniqueness is guaranteed by the partial unique index and
// this is only a hint for the next number.
func (q *Queries) NextInquirySequence(ctx context.Context, prefix string) (int32, error) {
	row := q.db.QueryRow(ctx, nextInquirySequence, prefix)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const setInquiryStatus = `-- name: SetInquiryStatus :one
UPDATE inquiries SET status=$2 WHERE id=$1 AND deleted_at IS NULL RETURNING id, reference_no, inquiry_type, name, company, contact, message, batch_id, status, source_ip, created_at, updated_at, deleted_at, version, created_by
`

type SetInquiryStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetInquiryStatus(ctx context.Context, arg SetInquiryStatusParams) (Inquiry, error) {
	row := q.db.QueryRow(ctx, setInquiryStatus, arg.ID, arg.Status)
	var i Inquiry
	err := row.Scan(
		&i.ID,
		&i.ReferenceNo,
		&i.InquiryType,
		&i.Name,
		&i.Company,
		&i.Contact,
		&i.Message,
		&i.BatchID,
		&i.Status,
		&i.SourceIp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}
