// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countBatchesExpiringWithin = `-- name: CountBatchesExpiringWithin :one
SELECT count(*)::int FROM batches
WHERE deleted_at IS NULL
  AND expires_on IS NOT NULL
  AND expires_on <= CURRENT_DATE + $1::int
  AND status <> 'rejected'
`

func (q *Queries) CountBatchesExpiringWithin(ctx context.Context, days int32) (int32, error) {
	row := q.db.QueryRow(ctx, countBatchesExpiringWithin, days)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countContractsExpiringWithin = `-- name: CountContractsExpiringWithin :one
SELECT count(*)::int FROM employees
WHERE deleted_at IS NULL AND contract_until IS NOT NULL
  AND contract_until <= CURRENT_DATE + $1::int
  AND status = 'active'
`

func (q *Queries) CountContractsExpiringWithin(ctx context.Context, days int32) (int32, error) {
	row := q.db.QueryRow(ctx, countContractsExpiringWithin, days)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countDocumentsExpiringWithin = `-- name: CountDocumentsExpiringWithin :one

SELECT count(*)::int FROM documents
WHERE deleted_at IS NULL AND valid_until IS NOT NULL
  AND valid_until <= CURRENT_DATE + $1::int
  AND status IN ('active','expiring')
`

// ---------------------------------------------------------------------------
// Derived standing conditions — the other seven (docs/07 I15)
// ---------------------------------------------------------------------------
func (q *Queries) CountDocumentsExpiringWithin(ctx context.Context, days int32) (int32, error) {
	row := q.db.QueryRow(ctx, countDocumentsExpiringWithin, days)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countItemsBelowMinimum = `-- name: CountItemsBelowMinimum :one

SELECT count(*)::int FROM (
  SELECT i.id
  FROM items i
  JOIN stock_balances b ON b.item_id = i.id
  WHERE i.deleted_at IS NULL AND i.min_qty IS NOT NULL
  GROUP BY i.id, i.min_qty
  HAVING SUM(b.on_hand) < i.min_qty
) low
`

// ---------------------------------------------------------------------------
// Alerts — derived standing conditions (docs/07-IMPLEMENTATION-PLAN.md I15)
// ---------------------------------------------------------------------------
// Self-healing by construction: a goods receipt pushes the total back above the
// threshold and the alert disappears with no retraction logic.
func (q *Queries) CountItemsBelowMinimum(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countItemsBelowMinimum)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countMaintenanceDue = `-- name: CountMaintenanceDue :one
SELECT count(*)::int FROM assets a
WHERE a.deleted_at IS NULL AND a.status <> 'retired'
  AND EXISTS (SELECT 1 FROM maintenance_events m
              WHERE m.asset_id=a.id AND m.deleted_at IS NULL
                AND m.next_due_on IS NOT NULL
                AND m.next_due_on <= CURRENT_DATE + $1::int)
`

func (q *Queries) CountMaintenanceDue(ctx context.Context, days int32) (int32, error) {
	row := q.db.QueryRow(ctx, countMaintenanceDue, days)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countStockBalances = `-- name: CountStockBalances :one
SELECT count(*)
FROM stock_balances b
JOIN items i ON i.id = b.item_id AND i.deleted_at IS NULL
JOIN locations l ON l.id = b.location_id AND l.deleted_at IS NULL
LEFT JOIN item_translations tr
  ON tr.item_id = i.id AND tr.locale = 'ru' AND tr.deleted_at IS NULL
LEFT JOIN batches bt ON bt.id = b.batch_id
WHERE b.on_hand <> 0
  AND ($1::uuid IS NULL OR b.item_id = $1)
  AND ($2::uuid IS NULL OR b.batch_id = $2)
  AND ($3::text IS NULL OR l.zone = $3)
  AND (
    $4::text IS NULL
    OR unaccent(lower(i.sku)) LIKE '%' || unaccent(lower($4)) || '%'
    OR unaccent(lower(COALESCE(tr.name, ''))) LIKE '%' || unaccent(lower($4)) || '%'
    OR unaccent(lower(COALESCE(bt.batch_no, ''))) LIKE '%' || unaccent(lower($4)) || '%'
  )
`

type CountStockBalancesParams struct {
	ItemID  uuid.NullUUID
	BatchID uuid.NullUUID
	Zone    *string
	Q       *string
}

func (q *Queries) CountStockBalances(ctx context.Context, arg CountStockBalancesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStockBalances,
		arg.ItemID,
		arg.BatchID,
		arg.Zone,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)::int FROM notifications n
LEFT JOIN notification_reads r ON r.notification_id=n.id AND r.user_id=$1
WHERE n.deleted_at IS NULL AND r.id IS NULL
  AND n.resource = ANY($2::text[])
`

type CountUnreadNotificationsParams struct {
	UserID    uuid.UUID
	Resources []string
}

func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, arg.UserID, arg.Resources)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createLocation = `-- name: CreateLocation :one

INSERT INTO locations (code, name, zone, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, zone, created_at, updated_at, deleted_at, version, created_by
`

type CreateLocationParams struct {
	Code      string
	Name      string
	Zone      string
	CreatedBy uuid.NullUUID
}

// Склад и запасы — the append-only ledger. docs/02-SCHEMA.md §5.
//
// Note what is absent from this entire file: any UPDATE of qty_delta, and any
// query that sets a quantity. Corrections are compensating INSERTs. The original
// row is evidence and is never edited (docs/02-SCHEMA.md:240).
func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.Code,
		arg.Name,
		arg.Zone,
		arg.CreatedBy,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Zone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const dashboardOpenOrders = `-- name: DashboardOpenOrders :one
SELECT count(*)::int FROM sales_orders
WHERE deleted_at IS NULL AND status IN ('confirmed','picking')
`

func (q *Queries) DashboardOpenOrders(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, dashboardOpenOrders)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const dashboardOverduePurchases = `-- name: DashboardOverduePurchases :one
SELECT count(*)::int FROM purchase_orders
WHERE deleted_at IS NULL
  AND status IN ('confirmed','in_transit')
  AND expected_at IS NOT NULL AND expected_at < CURRENT_DATE
`

func (q *Queries) DashboardOverduePurchases(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, dashboardOverduePurchases)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const dashboardPipeline = `-- name: DashboardPipeline :many
SELECT stage, count(*)::int AS deal_count,
  COALESCE(SUM(amount), 0)::numeric(14,2) AS amount
FROM deals WHERE deleted_at IS NULL AND stage NOT IN ('won','lost')
GROUP BY stage ORDER BY stage
`

type DashboardPipelineRow struct {
	Stage     string
	DealCount int32
	Amount    decimal.Decimal
}

// Воронка продаж by deal stage.
func (q *Queries) DashboardPipeline(ctx context.Context) ([]DashboardPipelineRow, error) {
	rows, err := q.db.Query(ctx, dashboardPipeline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardPipelineRow{}
	for rows.Next() {
		var i DashboardPipelineRow
		if err := rows.Scan(&i.Stage, &i.DealCount, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardProductionToday = `-- name: DashboardProductionToday :one
SELECT
  COALESCE(SUM(e.good_qty), 0)::numeric(14,3)  AS good_qty,
  COALESCE(SUM(e.scrap_qty), 0)::numeric(14,3) AS scrap_qty,
  COALESCE(SUM(mo.planned_qty), 0)::numeric(14,3) AS planned_qty
FROM manufacturing_orders mo
LEFT JOIN production_entries e
  ON e.mo_id = mo.id AND e.deleted_at IS NULL
  AND e.recorded_at >= date_trunc('day', now())
WHERE mo.deleted_at IS NULL AND mo.status = 'in_progress'
`

type DashboardProductionTodayRow struct {
	GoodQty    decimal.Decimal
	ScrapQty   decimal.Decimal
	PlannedQty decimal.Decimal
}

func (q *Queries) DashboardProductionToday(ctx context.Context) (DashboardProductionTodayRow, error) {
	row := q.db.QueryRow(ctx, dashboardProductionToday)
	var i DashboardProductionTodayRow
	err := row.Scan(&i.GoodQty, &i.ScrapQty, &i.PlannedQty)
	return i, err
}

const dashboardQuarantinedBatches = `-- name: DashboardQuarantinedBatches :one
SELECT count(*)::int FROM batches
WHERE deleted_at IS NULL AND status = 'quarantine'
`

func (q *Queries) DashboardQuarantinedBatches(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, dashboardQuarantinedBatches)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const dashboardRecentAudit = `-- name: DashboardRecentAudit :many
SELECT a.id, a.action, a.resource, a.resource_id, a.occurred_at, u.full_name AS actor_name
FROM audit_log a
LEFT JOIN users u ON u.id = a.actor_id
WHERE a.resource = ANY($2::text[])
ORDER BY a.occurred_at DESC
LIMIT $1
`

type DashboardRecentAuditParams struct {
	Limit     int32
	Resources []string
}

type DashboardRecentAuditRow struct {
	ID         uuid.UUID
	Action     string
	Resource   string
	ResourceID uuid.NullUUID
	OccurredAt pgtype.Timestamptz
	ActorName  *string
}

// Лента событий. Read from the audit log rather than a second feed table: the
// audit trail is already the record of everything that happened, and a parallel
// feed would be a second thing to keep in step.
func (q *Queries) DashboardRecentAudit(ctx context.Context, arg DashboardRecentAuditParams) ([]DashboardRecentAuditRow, error) {
	rows, err := q.db.Query(ctx, dashboardRecentAudit, arg.Limit, arg.Resources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardRecentAuditRow{}
	for rows.Next() {
		var i DashboardRecentAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.OccurredAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRecentOrders = `-- name: DashboardRecentOrders :many
SELECT so.id, so.so_no, c.name AS customer_name, so.status, so.created_at,
  COALESCE((SELECT SUM(l.qty * l.unit_price) FROM sales_order_lines l
            WHERE l.sales_order_id = so.id AND l.deleted_at IS NULL), 0)::numeric(14,2) AS total
FROM sales_orders so
JOIN customers c ON c.id = so.customer_id
WHERE so.deleted_at IS NULL
ORDER BY so.created_at DESC
LIMIT $1
`

type DashboardRecentOrdersRow struct {
	ID           uuid.UUID
	SoNo         string
	CustomerName string
	Status       string
	CreatedAt    pgtype.Timestamptz
	Total        decimal.Decimal
}

func (q *Queries) DashboardRecentOrders(ctx context.Context, limit int32) ([]DashboardRecentOrdersRow, error) {
	rows, err := q.db.Query(ctx, dashboardRecentOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardRecentOrdersRow{}
	for rows.Next() {
		var i DashboardRecentOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.SoNo,
			&i.CustomerName,
			&i.Status,
			&i.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRevenueByDay = `-- name: DashboardRevenueByDay :many
SELECT
  d::date AS day,
  COALESCE(SUM(l.qty * l.unit_price), 0)::numeric(14,2) AS revenue,
  count(DISTINCT so.id)::int AS order_count
FROM generate_series(
  date_trunc('day', now()) - (($1::int - 1) || ' days')::interval,
  date_trunc('day', now()),
  '1 day'
) AS d
LEFT JOIN sales_orders so
  ON date_trunc('day', so.created_at) = d
  AND so.deleted_at IS NULL AND so.status NOT IN ('draft','cancelled')
LEFT JOIN sales_order_lines l ON l.sales_order_id = so.id AND l.deleted_at IS NULL
GROUP BY d
ORDER BY d
`

type DashboardRevenueByDayRow struct {
	Day        pgtype.Date
	Revenue    decimal.Decimal
	OrderCount int32
}

// The revenue sparkline. Uses generate_series so days with no orders appear as
// zero rather than being skipped — a gap in the axis would misread as a spike.
func (q *Queries) DashboardRevenueByDay(ctx context.Context, days int32) ([]DashboardRevenueByDayRow, error) {
	rows, err := q.db.Query(ctx, dashboardRevenueByDay, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardRevenueByDayRow{}
	for rows.Next() {
		var i DashboardRevenueByDayRow
		if err := rows.Scan(&i.Day, &i.Revenue, &i.OrderCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardSalesTotals = `-- name: DashboardSalesTotals :one

SELECT
  COALESCE(SUM(l.qty * l.unit_price), 0)::numeric(14,2) AS revenue,
  count(DISTINCT so.id)::int AS order_count
FROM sales_orders so
JOIN sales_order_lines l ON l.sales_order_id = so.id AND l.deleted_at IS NULL
WHERE so.deleted_at IS NULL
  AND so.status <> 'draft' AND so.status <> 'cancelled'
  AND so.created_at >= now() - ($1::int || ' days')::interval
`

type DashboardSalesTotalsRow struct {
	Revenue    decimal.Decimal
	OrderCount int32
}

// ---------------------------------------------------------------------------
// Панель управления — docs/05-MODULES.md §2
// ---------------------------------------------------------------------------
//
// Every figure here is computed from what actually happened. On opening day the
// factory has produced nothing, so these all return zero — and that is the
// correct answer. 05-MODULES.md:70 is explicit that the prototype's sample
// numbers must not be carried into production.
// Revenue and order count over a window. Confirmed onwards only: a draft is a
// quotation, and counting it as revenue would overstate the month.
func (q *Queries) DashboardSalesTotals(ctx context.Context, days int32) (DashboardSalesTotalsRow, error) {
	row := q.db.QueryRow(ctx, dashboardSalesTotals, days)
	var i DashboardSalesTotalsRow
	err := row.Scan(&i.Revenue, &i.OrderCount)
	return i, err
}

const dashboardStockValue = `-- name: DashboardStockValue :one
SELECT COALESCE(SUM(b.on_hand * COALESCE(p.unit_price, 0)), 0)::numeric(14,2) AS value
FROM stock_balances b
LEFT JOIN LATERAL (
  SELECT l.unit_price FROM purchase_order_lines l
  WHERE l.item_id = b.item_id AND l.deleted_at IS NULL
  ORDER BY l.created_at DESC LIMIT 1
) p ON true
WHERE b.on_hand > 0
`

// Stock at its most recent purchase price. Valued at cost, not at sale price:
// unsold stock is money spent, not money earned.
func (q *Queries) DashboardStockValue(ctx context.Context) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, dashboardStockValue)
	var value decimal.Decimal
	err := row.Scan(&value)
	return value, err
}

const getItemTotalOnHand = `-- name: GetItemTotalOnHand :one
SELECT COALESCE(SUM(on_hand), 0)::numeric AS on_hand
FROM stock_balances WHERE item_id = $1
`

// Total across every location and batch for one item. Used by the low-stock
// alert, which compares it against items.min_qty.
func (q *Queries) GetItemTotalOnHand(ctx context.Context, itemID uuid.UUID) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, getItemTotalOnHand, itemID)
	var on_hand decimal.Decimal
	err := row.Scan(&on_hand)
	return on_hand, err
}

const getLocationByCode = `-- name: GetLocationByCode :one
SELECT id, code, name, zone, created_at, updated_at, deleted_at, version, created_by FROM locations WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLocationByCode(ctx context.Context, code string) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByCode, code)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Zone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, code, name, zone, created_at, updated_at, deleted_at, version, created_by FROM locations WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLocationByID(ctx context.Context, id uuid.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Zone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getPositionBalance = `-- name: GetPositionBalance :one
SELECT COALESCE(SUM(qty_delta), 0)::numeric AS on_hand
FROM stock_movements
WHERE item_id = $1
  AND batch_id IS NOT DISTINCT FROM $3::uuid
  AND location_id = $2
  AND deleted_at IS NULL
`

type GetPositionBalanceParams struct {
	ItemID     uuid.UUID
	LocationID uuid.UUID
	BatchID    uuid.NullUUID
}

// The exact balance for one position. Read INSIDE the advisory lock before
// posting a negative delta — a value read before the lock is already stale.
func (q *Queries) GetPositionBalance(ctx context.Context, arg GetPositionBalanceParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, getPositionBalance, arg.ItemID, arg.LocationID, arg.BatchID)
	var on_hand decimal.Decimal
	err := row.Scan(&on_hand)
	return on_hand, err
}

const getQuarantineLocation = `-- name: GetQuarantineLocation :one
SELECT id, code, name, zone, created_at, updated_at, deleted_at, version, created_by FROM locations
WHERE zone = 'quarantine' AND deleted_at IS NULL
ORDER BY code
LIMIT 1
`

// Production output lands here and only a quality decision moves it out (§7).
func (q *Queries) GetQuarantineLocation(ctx context.Context) (Location, error) {
	row := q.db.QueryRow(ctx, getQuarantineLocation)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Zone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :one

INSERT INTO notifications (kind, resource, resource_id, level, title, body, created_by)
VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, kind, resource, resource_id, level, title, body, occurred_at, created_at, updated_at, deleted_at, version, created_by
`

type InsertNotificationParams struct {
	Kind       string
	Resource   string
	ResourceID uuid.NullUUID
	Level      string
	Title      string
	Body       *string
	CreatedBy  uuid.NullUUID
}

// ---------------------------------------------------------------------------
// Notifications — the three DISCRETE events only (docs/07 I15)
// ---------------------------------------------------------------------------
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.Kind,
		arg.Resource,
		arg.ResourceID,
		arg.Level,
		arg.Title,
		arg.Body,
		arg.CreatedBy,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Resource,
		&i.ResourceID,
		&i.Level,
		&i.Title,
		&i.Body,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const insertStockMovement = `-- name: InsertStockMovement :one

INSERT INTO stock_movements (
  item_id, batch_id, location_id, qty_delta, reason, ref_type, ref_id, note, occurred_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, COALESCE($10::timestamptz, now()), $9)
RETURNING id, item_id, batch_id, location_id, qty_delta, reason, ref_type, ref_id, note, occurred_at, created_at, updated_at, deleted_at, version, created_by
`

type InsertStockMovementParams struct {
	ItemID     uuid.UUID
	BatchID    uuid.NullUUID
	LocationID uuid.UUID
	QtyDelta   decimal.Decimal
	Reason     string
	RefType    *string
	RefID      uuid.NullUUID
	Note       *string
	CreatedBy  uuid.NullUUID
	OccurredAt pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// Movements
// ---------------------------------------------------------------------------
// The only way stock changes. qty_delta is signed; there is no other writer.
func (q *Queries) InsertStockMovement(ctx context.Context, arg InsertStockMovementParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, insertStockMovement,
		arg.ItemID,
		arg.BatchID,
		arg.LocationID,
		arg.QtyDelta,
		arg.Reason,
		arg.RefType,
		arg.RefID,
		arg.Note,
		arg.CreatedBy,
		arg.OccurredAt,
	)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.BatchID,
		&i.LocationID,
		&i.QtyDelta,
		&i.Reason,
		&i.RefType,
		&i.RefID,
		&i.Note,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many
SELECT id, code, name, zone, created_at, updated_at, deleted_at, version, created_by FROM locations WHERE deleted_at IS NULL ORDER BY zone, code
`

func (q *Queries) ListLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Zone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLowStockItems = `-- name: ListLowStockItems :many
SELECT i.id, i.sku, i.min_qty, SUM(b.on_hand)::numeric AS on_hand
FROM items i
JOIN stock_balances b ON b.item_id = i.id
WHERE i.deleted_at IS NULL AND i.min_qty IS NOT NULL
GROUP BY i.id, i.sku, i.min_qty
HAVING SUM(b.on_hand) < i.min_qty
ORDER BY i.sku
`

type ListLowStockItemsRow struct {
	ID     uuid.UUID
	Sku    string
	MinQty decimal.NullDecimal
	OnHand decimal.Decimal
}

func (q *Queries) ListLowStockItems(ctx context.Context) ([]ListLowStockItemsRow, error) {
	rows, err := q.db.Query(ctx, listLowStockItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLowStockItemsRow{}
	for rows.Next() {
		var i ListLowStockItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.MinQty,
			&i.OnHand,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovements = `-- name: ListMovements :many
SELECT m.id, m.item_id, m.batch_id, m.location_id, m.qty_delta, m.reason, m.ref_type, m.ref_id, m.note, m.occurred_at, m.created_at, m.updated_at, m.deleted_at, m.version, m.created_by, i.sku, l.code AS location_code
FROM stock_movements m
JOIN items i ON i.id = m.item_id
JOIN locations l ON l.id = m.location_id
WHERE m.deleted_at IS NULL
  AND ($3::uuid IS NULL OR m.item_id = $3)
  AND ($4::text IS NULL OR m.reason = $4)
  AND ($5::uuid IS NULL OR m.ref_id = $5)
ORDER BY m.occurred_at DESC, m.id DESC
LIMIT $1 OFFSET $2
`

type ListMovementsParams struct {
	Limit  int32
	Offset int32
	ItemID uuid.NullUUID
	Reason *string
	RefID  uuid.NullUUID
}

type ListMovementsRow struct {
	ID           uuid.UUID
	ItemID       uuid.UUID
	BatchID      uuid.NullUUID
	LocationID   uuid.UUID
	QtyDelta     decimal.Decimal
	Reason       string
	RefType      *string
	RefID        uuid.NullUUID
	Note         *string
	OccurredAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	Version      int32
	CreatedBy    uuid.NullUUID
	Sku          string
	LocationCode string
}

func (q *Queries) ListMovements(ctx context.Context, arg ListMovementsParams) ([]ListMovementsRow, error) {
	rows, err := q.db.Query(ctx, listMovements,
		arg.Limit,
		arg.Offset,
		arg.ItemID,
		arg.Reason,
		arg.RefID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMovementsRow{}
	for rows.Next() {
		var i ListMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.BatchID,
			&i.LocationID,
			&i.QtyDelta,
			&i.Reason,
			&i.RefType,
			&i.RefID,
			&i.Note,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
			&i.Sku,
			&i.LocationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsForPosition = `-- name: ListMovementsForPosition :many
SELECT
  m.id, m.item_id, m.batch_id, m.location_id, m.qty_delta, m.reason, m.ref_type, m.ref_id, m.note, m.occurred_at, m.created_at, m.updated_at, m.deleted_at, m.version, m.created_by,
  -- Cast for the same reason the view is cast in migration 00005: an
  -- uncast SUM over a window generates as int64 and truncates partial units.
  (SUM(m.qty_delta) OVER (ORDER BY m.occurred_at, m.id))::numeric(14,3) AS running_balance
FROM stock_movements m
WHERE m.item_id = $1
  AND m.batch_id IS NOT DISTINCT FROM $5::uuid
  AND m.location_id = $2
  AND m.deleted_at IS NULL
ORDER BY m.occurred_at DESC, m.id DESC
LIMIT $3 OFFSET $4
`

type ListMovementsForPositionParams struct {
	ItemID     uuid.UUID
	LocationID uuid.UUID
	Limit      int32
	Offset     int32
	BatchID    uuid.NullUUID
}

type ListMovementsForPositionRow struct {
	ID             uuid.UUID
	ItemID         uuid.UUID
	BatchID        uuid.NullUUID
	LocationID     uuid.UUID
	QtyDelta       decimal.Decimal
	Reason         string
	RefType        *string
	RefID          uuid.NullUUID
	Note           *string
	OccurredAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	Version        int32
	CreatedBy      uuid.NullUUID
	RunningBalance decimal.Decimal
}

// The movement ledger for one position, with a running balance — the detail view
// (docs/05-MODULES.md:115).
func (q *Queries) ListMovementsForPosition(ctx context.Context, arg ListMovementsForPositionParams) ([]ListMovementsForPositionRow, error) {
	rows, err := q.db.Query(ctx, listMovementsForPosition,
		arg.ItemID,
		arg.LocationID,
		arg.Limit,
		arg.Offset,
		arg.BatchID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMovementsForPositionRow{}
	for rows.Next() {
		var i ListMovementsForPositionRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.BatchID,
			&i.LocationID,
			&i.QtyDelta,
			&i.Reason,
			&i.RefType,
			&i.RefID,
			&i.Note,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
			&i.RunningBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT n.id, n.kind, n.resource, n.resource_id, n.level, n.title, n.body, n.occurred_at, n.created_at, n.updated_at, n.deleted_at, n.version, n.created_by, (r.id IS NOT NULL)::boolean AS is_read
FROM notifications n
LEFT JOIN notification_reads r ON r.notification_id=n.id AND r.user_id=$1
WHERE n.deleted_at IS NULL AND n.resource = ANY($3::text[])
ORDER BY n.occurred_at DESC LIMIT $2
`

type ListNotificationsParams struct {
	UserID    uuid.UUID
	Limit     int32
	Resources []string
}

type ListNotificationsRow struct {
	ID         uuid.UUID
	Kind       string
	Resource   string
	ResourceID uuid.NullUUID
	Level      string
	Title      string
	Body       *string
	OccurredAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	Version    int32
	CreatedBy  uuid.NullUUID
	IsRead     bool
}

// Filtered by the viewer's readable resources at READ time: a notification is
// broadcast by resource, not addressed to a user (docs/05-MODULES.md:294).
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit, arg.Resources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Resource,
			&i.ResourceID,
			&i.Level,
			&i.Title,
			&i.Body,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
			&i.IsRead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockBalances = `-- name: ListStockBalances :many

SELECT
  b.item_id, b.batch_id, b.location_id, b.on_hand, b.last_movement_at,
  i.sku,
  COALESCE(tr.name, i.sku) AS item_name,
  i.base_uom,
  i.min_qty,
  l.code AS location_code,
  l.zone AS location_zone,
  bt.batch_no,
  bt.expires_on,
  bt.status AS batch_status
FROM stock_balances b
JOIN items i ON i.id = b.item_id AND i.deleted_at IS NULL
JOIN locations l ON l.id = b.location_id AND l.deleted_at IS NULL
LEFT JOIN item_translations tr
  ON tr.item_id = i.id AND tr.locale = 'ru' AND tr.deleted_at IS NULL
LEFT JOIN batches bt ON bt.id = b.batch_id
WHERE b.on_hand <> 0
  AND ($3::uuid IS NULL OR b.item_id = $3)
  AND ($4::uuid IS NULL OR b.batch_id = $4)
  AND ($5::text IS NULL OR l.zone = $5)
  AND (
    $6::text IS NULL
    OR unaccent(lower(i.sku)) LIKE '%' || unaccent(lower($6)) || '%'
    OR unaccent(lower(COALESCE(tr.name, ''))) LIKE '%' || unaccent(lower($6)) || '%'
    OR unaccent(lower(COALESCE(bt.batch_no, ''))) LIKE '%' || unaccent(lower($6)) || '%'
  )
ORDER BY i.sku, l.code, bt.batch_no NULLS FIRST
LIMIT $1 OFFSET $2
`

type ListStockBalancesParams struct {
	Limit   int32
	Offset  int32
	ItemID  uuid.NullUUID
	BatchID uuid.NullUUID
	Zone    *string
	Q       *string
}

type ListStockBalancesRow struct {
	StockBalance StockBalance
	Sku          string
	ItemName     string
	BaseUom      string
	MinQty       decimal.NullDecimal
	LocationCode string
	LocationZone string
	BatchNo      *string
	ExpiresOn    pgtype.Date
	BatchStatus  *string
}

// ---------------------------------------------------------------------------
// Balances — derived, never stored
// ---------------------------------------------------------------------------
// The Склад list view. Every quantity here is a SUM computed at read time.
//
// Positions that have netted to zero are excluded: a row reading "0" is not a
// stock position, it is the absence of one, and showing it would fill the
// warehouse list with everything that ever passed through.
func (q *Queries) ListStockBalances(ctx context.Context, arg ListStockBalancesParams) ([]ListStockBalancesRow, error) {
	rows, err := q.db.Query(ctx, listStockBalances,
		arg.Limit,
		arg.Offset,
		arg.ItemID,
		arg.BatchID,
		arg.Zone,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockBalancesRow{}
	for rows.Next() {
		var i ListStockBalancesRow
		if err := rows.Scan(
			&i.StockBalance.ItemID,
			&i.StockBalance.BatchID,
			&i.StockBalance.LocationID,
			&i.StockBalance.OnHand,
			&i.StockBalance.LastMovementAt,
			&i.Sku,
			&i.ItemName,
			&i.BaseUom,
			&i.MinQty,
			&i.LocationCode,
			&i.LocationZone,
			&i.BatchNo,
			&i.ExpiresOn,
			&i.BatchStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStockPosition = `-- name: LockStockPosition :exec
SELECT pg_advisory_xact_lock(
  hashtextextended(
    $1::text || ':' || COALESCE($2::text, '-') || ':' || $3::text, 0))
`

type LockStockPositionParams struct {
	Column1 string
	Column2 string
	Column3 string
}

// Serialises writers against one (item, batch, location) for the rest of the
// transaction (docs/07-IMPLEMENTATION-PLAN.md I6).
//
// Taken only when posting a NEGATIVE delta: two receipts cannot oversell, so
// locking them would serialise the warehouse for nothing. The lock key hashes
// the position; batch_id is nullable, so it is coalesced to a fixed sentinel
// rather than left to hash NULL.
func (q *Queries) LockStockPosition(ctx context.Context, arg LockStockPositionParams) error {
	_, err := q.db.Exec(ctx, lockStockPosition, arg.Column1, arg.Column2, arg.Column3)
	return err
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
INSERT INTO notification_reads (notification_id, user_id)
SELECT n.id, $1 FROM notifications n
WHERE n.deleted_at IS NULL AND n.resource = ANY($2::text[])
ON CONFLICT DO NOTHING
`

type MarkNotificationsReadParams struct {
	UserID    uuid.UUID
	Resources []string
}

func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationsRead, arg.UserID, arg.Resources)
	return err
}
