// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countItems = `-- name: CountItems :one
SELECT count(*) FROM items WHERE deleted_at IS NULL
`

func (q *Queries) CountItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countItemsByStatus = `-- name: CountItemsByStatus :one
SELECT count(*) FROM items WHERE status = $1 AND deleted_at IS NULL
`

func (q *Queries) CountItemsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countItemsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getItemByID = `-- name: GetItemByID :one

SELECT id, sku, item_type, category, base_uom, shelf_life_days, min_qty, is_active, status, created_at, updated_at, deleted_at, version, created_by FROM items WHERE id = $1 AND deleted_at IS NULL
`

// Product master queries.
//
// Minimal for now: T03 wires sqlc and proves generation. The full Товары query
// set — list with search and filters, detail with translations, packaging units
// and price history — arrives with T11, which is the reference slice.
//
// Note there is no query here that reads or writes a stock quantity. There is no
// such column; stock is derived from the movement ledger (CLAUDE.md §4.2, T16).
func (q *Queries) GetItemByID(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.ItemType,
		&i.Category,
		&i.BaseUom,
		&i.ShelfLifeDays,
		&i.MinQty,
		&i.IsActive,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getItemBySKU = `-- name: GetItemBySKU :one
SELECT id, sku, item_type, category, base_uom, shelf_life_days, min_qty, is_active, status, created_at, updated_at, deleted_at, version, created_by FROM items WHERE sku = $1 AND deleted_at IS NULL
`

func (q *Queries) GetItemBySKU(ctx context.Context, sku string) (Item, error) {
	row := q.db.QueryRow(ctx, getItemBySKU, sku)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.ItemType,
		&i.Category,
		&i.BaseUom,
		&i.ShelfLifeDays,
		&i.MinQty,
		&i.IsActive,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const listItemTranslations = `-- name: ListItemTranslations :many
SELECT id, item_id, locale, name, description, ingredients, nutrition, storage_conditions, after_opening, created_at, updated_at, deleted_at, version, created_by FROM item_translations
WHERE item_id = $1 AND deleted_at IS NULL
ORDER BY locale
`

func (q *Queries) ListItemTranslations(ctx context.Context, itemID uuid.UUID) ([]ItemTranslation, error) {
	rows, err := q.db.Query(ctx, listItemTranslations, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemTranslation{}
	for rows.Next() {
		var i ItemTranslation
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Locale,
			&i.Name,
			&i.Description,
			&i.Ingredients,
			&i.Nutrition,
			&i.StorageConditions,
			&i.AfterOpening,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
