// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type AuditLog struct {
	ID         uuid.UUID
	ActorID    uuid.NullUUID
	Action     string
	Resource   string
	ResourceID uuid.NullUUID
	Before     []byte
	After      []byte
	Ip         *netip.Addr
	OccurredAt pgtype.Timestamptz
}

type Batch struct {
	ID         uuid.UUID
	BatchNo    string
	ItemID     uuid.UUID
	ProducedOn pgtype.Date
	ExpiresOn  pgtype.Date
	QrPayload  *string
	QrIssuedAt pgtype.Timestamptz
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	Version    int32
	CreatedBy  uuid.NullUUID
}

type Item struct {
	ID            uuid.UUID
	Sku           string
	ItemType      string
	Category      *string
	BaseUom       string
	ShelfLifeDays *int32
	MinQty        decimal.NullDecimal
	IsActive      bool
	Status        string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	Version       int32
	CreatedBy     uuid.NullUUID
}

type ItemPrice struct {
	ID        uuid.UUID
	ItemID    uuid.UUID
	Currency  string
	Amount    decimal.Decimal
	ValidFrom pgtype.Date
	ValidTo   pgtype.Date
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Version   int32
	CreatedBy uuid.NullUUID
}

type ItemTranslation struct {
	ID                uuid.UUID
	ItemID            uuid.UUID
	Locale            string
	Name              string
	Description       *string
	Ingredients       *string
	Nutrition         *string
	StorageConditions *string
	AfterOpening      *string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	Version           int32
	CreatedBy         uuid.NullUUID
}

type PackagingUnit struct {
	ID        uuid.UUID
	ItemID    uuid.UUID
	Code      string
	QtyInBase decimal.Decimal
	Barcode   *string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Version   int32
	CreatedBy uuid.NullUUID
}

type Role struct {
	ID        uuid.UUID
	Key       string
	NameRu    string
	NameTg    string
	NameEn    string
	IsSystem  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Version   int32
	CreatedBy uuid.NullUUID
}

type RolePermission struct {
	ID        uuid.UUID
	RoleID    uuid.UUID
	Resource  string
	Action    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Version   int32
	CreatedBy uuid.NullUUID
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	Ip        *netip.Addr
	UserAgent *string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Version   int32
	CreatedBy uuid.NullUUID
}

type User struct {
	ID             uuid.UUID
	Email          string
	FullName       string
	PasswordHash   string
	IsActive       bool
	LastLoginAt    pgtype.Timestamptz
	FailedAttempts int32
	LockedUntil    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	Version        int32
	CreatedBy      uuid.NullUUID
}

type UserRole struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	RoleID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Version   int32
	CreatedBy uuid.NullUUID
}
