// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: procurement.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countOverdueDeliveries = `-- name: CountOverdueDeliveries :one
SELECT count(*)::int FROM purchase_orders
WHERE deleted_at IS NULL AND expected_at < CURRENT_DATE
  AND status IN ('confirmed','in_transit','receiving')
`

func (q *Queries) CountOverdueDeliveries(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countOverdueDeliveries)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countPurchaseOrders = `-- name: CountPurchaseOrders :one
SELECT count(*) FROM purchase_orders po JOIN suppliers s ON s.id=po.supplier_id
WHERE po.deleted_at IS NULL
  AND ($1::text IS NULL OR po.status=$1)
  AND ($2::text IS NULL OR unaccent(lower(po.po_no)) LIKE '%'||unaccent(lower($2))||'%'
       OR unaccent(lower(s.name)) LIKE '%'||unaccent(lower($2))||'%')
`

type CountPurchaseOrdersParams struct {
	Status *string
	Q      *string
}

func (q *Queries) CountPurchaseOrders(ctx context.Context, arg CountPurchaseOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPurchaseOrders, arg.Status, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPurchaseOrdersAwaitingApproval = `-- name: CountPurchaseOrdersAwaitingApproval :one
SELECT count(*)::int FROM purchase_orders
WHERE deleted_at IS NULL AND status IN ('draft','approval')
`

func (q *Queries) CountPurchaseOrdersAwaitingApproval(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countPurchaseOrdersAwaitingApproval)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countSuppliers = `-- name: CountSuppliers :one
SELECT count(*) FROM suppliers WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR unaccent(lower(name)) LIKE '%'||unaccent(lower($1))||'%')
`

func (q *Queries) CountSuppliers(ctx context.Context, q_ *string) (int64, error) {
	row := q.db.QueryRow(ctx, countSuppliers, q_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGoodsReceipt = `-- name: CreateGoodsReceipt :one
INSERT INTO goods_receipts (po_id, location_id, received_by, note, created_by)
VALUES ($1,$2,$3,$4,$3) RETURNING id, po_id, location_id, received_at, received_by, note, created_at, updated_at, deleted_at, version, created_by
`

type CreateGoodsReceiptParams struct {
	PoID       uuid.UUID
	LocationID uuid.UUID
	ReceivedBy uuid.NullUUID
	Note       *string
}

func (q *Queries) CreateGoodsReceipt(ctx context.Context, arg CreateGoodsReceiptParams) (GoodsReceipt, error) {
	row := q.db.QueryRow(ctx, createGoodsReceipt,
		arg.PoID,
		arg.LocationID,
		arg.ReceivedBy,
		arg.Note,
	)
	var i GoodsReceipt
	err := row.Scan(
		&i.ID,
		&i.PoID,
		&i.LocationID,
		&i.ReceivedAt,
		&i.ReceivedBy,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const createGoodsReceiptLine = `-- name: CreateGoodsReceiptLine :one
INSERT INTO goods_receipt_lines (receipt_id, po_line_id, qty, created_by)
VALUES ($1,$2,$3,$4) RETURNING id, receipt_id, po_line_id, qty, created_at, updated_at, deleted_at, version, created_by
`

type CreateGoodsReceiptLineParams struct {
	ReceiptID uuid.UUID
	PoLineID  uuid.UUID
	Qty       decimal.Decimal
	CreatedBy uuid.NullUUID
}

func (q *Queries) CreateGoodsReceiptLine(ctx context.Context, arg CreateGoodsReceiptLineParams) (GoodsReceiptLine, error) {
	row := q.db.QueryRow(ctx, createGoodsReceiptLine,
		arg.ReceiptID,
		arg.PoLineID,
		arg.Qty,
		arg.CreatedBy,
	)
	var i GoodsReceiptLine
	err := row.Scan(
		&i.ID,
		&i.ReceiptID,
		&i.PoLineID,
		&i.Qty,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const createPurchaseOrder = `-- name: CreatePurchaseOrder :one
INSERT INTO purchase_orders (po_no, supplier_id, expected_at, created_by)
VALUES ($1,$2,$3,$4) RETURNING id, po_no, supplier_id, expected_at, status, created_at, updated_at, deleted_at, version, created_by
`

type CreatePurchaseOrderParams struct {
	PoNo       string
	SupplierID uuid.UUID
	ExpectedAt pgtype.Date
	CreatedBy  uuid.NullUUID
}

func (q *Queries) CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrder,
		arg.PoNo,
		arg.SupplierID,
		arg.ExpectedAt,
		arg.CreatedBy,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.PoNo,
		&i.SupplierID,
		&i.ExpectedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const createPurchaseOrderLine = `-- name: CreatePurchaseOrderLine :one
INSERT INTO purchase_order_lines (po_id, item_id, qty, unit_price, created_by)
VALUES ($1,$2,$3,$4,$5) RETURNING id, po_id, item_id, qty, unit_price, created_at, updated_at, deleted_at, version, created_by
`

type CreatePurchaseOrderLineParams struct {
	PoID      uuid.UUID
	ItemID    uuid.UUID
	Qty       decimal.Decimal
	UnitPrice decimal.Decimal
	CreatedBy uuid.NullUUID
}

func (q *Queries) CreatePurchaseOrderLine(ctx context.Context, arg CreatePurchaseOrderLineParams) (PurchaseOrderLine, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrderLine,
		arg.PoID,
		arg.ItemID,
		arg.Qty,
		arg.UnitPrice,
		arg.CreatedBy,
	)
	var i PurchaseOrderLine
	err := row.Scan(
		&i.ID,
		&i.PoID,
		&i.ItemID,
		&i.Qty,
		&i.UnitPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const createSupplier = `-- name: CreateSupplier :one

INSERT INTO suppliers (name, tax_id, contact, region, rating, created_by)
VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, name, tax_id, contact, region, rating, created_at, updated_at, deleted_at, version, created_by
`

type CreateSupplierParams struct {
	Name      string
	TaxID     *string
	Contact   *string
	Region    *string
	Rating    *int32
	CreatedBy uuid.NullUUID
}

// Закупки и поставщики — docs/05-MODULES.md §10.
// Goods receipt posts goods_receipt movements: this is how raw material enters
// inventory, and the two must happen in one transaction.
func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.Name,
		arg.TaxID,
		arg.Contact,
		arg.Region,
		arg.Rating,
		arg.CreatedBy,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TaxID,
		&i.Contact,
		&i.Region,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getPurchaseOrder = `-- name: GetPurchaseOrder :one
SELECT id, po_no, supplier_id, expected_at, status, created_at, updated_at, deleted_at, version, created_by FROM purchase_orders WHERE id=$1 AND deleted_at IS NULL
`

func (q *Queries) GetPurchaseOrder(ctx context.Context, id uuid.UUID) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrder, id)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.PoNo,
		&i.SupplierID,
		&i.ExpectedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getPurchaseOrderLine = `-- name: GetPurchaseOrderLine :one
SELECT id, po_id, item_id, qty, unit_price, created_at, updated_at, deleted_at, version, created_by FROM purchase_order_lines WHERE id=$1 AND deleted_at IS NULL
`

func (q *Queries) GetPurchaseOrderLine(ctx context.Context, id uuid.UUID) (PurchaseOrderLine, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrderLine, id)
	var i PurchaseOrderLine
	err := row.Scan(
		&i.ID,
		&i.PoID,
		&i.ItemID,
		&i.Qty,
		&i.UnitPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getSupplier = `-- name: GetSupplier :one
SELECT id, name, tax_id, contact, region, rating, created_at, updated_at, deleted_at, version, created_by FROM suppliers WHERE id=$1 AND deleted_at IS NULL
`

func (q *Queries) GetSupplier(ctx context.Context, id uuid.UUID) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplier, id)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TaxID,
		&i.Contact,
		&i.Region,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const listGoodsReceipts = `-- name: ListGoodsReceipts :many
SELECT id, po_id, location_id, received_at, received_by, note, created_at, updated_at, deleted_at, version, created_by FROM goods_receipts WHERE po_id=$1 AND deleted_at IS NULL ORDER BY received_at DESC
`

func (q *Queries) ListGoodsReceipts(ctx context.Context, poID uuid.UUID) ([]GoodsReceipt, error) {
	rows, err := q.db.Query(ctx, listGoodsReceipts, poID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GoodsReceipt{}
	for rows.Next() {
		var i GoodsReceipt
		if err := rows.Scan(
			&i.ID,
			&i.PoID,
			&i.LocationID,
			&i.ReceivedAt,
			&i.ReceivedBy,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrderLines = `-- name: ListPurchaseOrderLines :many
SELECT l.id, l.po_id, l.item_id, l.qty, l.unit_price, l.created_at, l.updated_at, l.deleted_at, l.version, l.created_by, i.sku, COALESCE(tr.name, i.sku) AS item_name,
  COALESCE((SELECT SUM(rl.qty) FROM goods_receipt_lines rl
            WHERE rl.po_line_id=l.id AND rl.deleted_at IS NULL),0)::numeric AS received_qty
FROM purchase_order_lines l JOIN items i ON i.id=l.item_id
LEFT JOIN item_translations tr
  ON tr.item_id = i.id AND tr.locale = 'ru' AND tr.deleted_at IS NULL
WHERE l.po_id=$1 AND l.deleted_at IS NULL ORDER BY i.sku
`

type ListPurchaseOrderLinesRow struct {
	ID          uuid.UUID
	PoID        uuid.UUID
	ItemID      uuid.UUID
	Qty         decimal.Decimal
	UnitPrice   decimal.Decimal
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	Version     int32
	CreatedBy   uuid.NullUUID
	Sku         string
	ItemName    string
	ReceivedQty decimal.Decimal
}

func (q *Queries) ListPurchaseOrderLines(ctx context.Context, poID uuid.UUID) ([]ListPurchaseOrderLinesRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrderLines, poID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchaseOrderLinesRow{}
	for rows.Next() {
		var i ListPurchaseOrderLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.PoID,
			&i.ItemID,
			&i.Qty,
			&i.UnitPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
			&i.Sku,
			&i.ItemName,
			&i.ReceivedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrders = `-- name: ListPurchaseOrders :many
SELECT po.id, po.po_no, po.supplier_id, po.expected_at, po.status, po.created_at, po.updated_at, po.deleted_at, po.version, po.created_by, s.name AS supplier_name,
  (SELECT count(*) FROM purchase_order_lines l WHERE l.po_id=po.id AND l.deleted_at IS NULL)::int AS line_count,
  COALESCE((SELECT SUM(l.qty*l.unit_price) FROM purchase_order_lines l
            WHERE l.po_id=po.id AND l.deleted_at IS NULL),0)::numeric AS total_amount
FROM purchase_orders po JOIN suppliers s ON s.id=po.supplier_id
WHERE po.deleted_at IS NULL
  AND ($3::text IS NULL OR po.status=$3)
  AND ($4::text IS NULL OR unaccent(lower(po.po_no)) LIKE '%'||unaccent(lower($4))||'%'
       OR unaccent(lower(s.name)) LIKE '%'||unaccent(lower($4))||'%')
ORDER BY po.expected_at DESC NULLS LAST, po.po_no DESC LIMIT $1 OFFSET $2
`

type ListPurchaseOrdersParams struct {
	Limit  int32
	Offset int32
	Status *string
	Q      *string
}

type ListPurchaseOrdersRow struct {
	PurchaseOrder PurchaseOrder
	SupplierName  string
	LineCount     int32
	TotalAmount   decimal.Decimal
}

func (q *Queries) ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]ListPurchaseOrdersRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrders,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchaseOrdersRow{}
	for rows.Next() {
		var i ListPurchaseOrdersRow
		if err := rows.Scan(
			&i.PurchaseOrder.ID,
			&i.PurchaseOrder.PoNo,
			&i.PurchaseOrder.SupplierID,
			&i.PurchaseOrder.ExpectedAt,
			&i.PurchaseOrder.Status,
			&i.PurchaseOrder.CreatedAt,
			&i.PurchaseOrder.UpdatedAt,
			&i.PurchaseOrder.DeletedAt,
			&i.PurchaseOrder.Version,
			&i.PurchaseOrder.CreatedBy,
			&i.SupplierName,
			&i.LineCount,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, name, tax_id, contact, region, rating, created_at, updated_at, deleted_at, version, created_by FROM suppliers WHERE deleted_at IS NULL
  AND ($3::text IS NULL OR unaccent(lower(name)) LIKE '%'||unaccent(lower($3))||'%')
ORDER BY name LIMIT $1 OFFSET $2
`

type ListSuppliersParams struct {
	Limit  int32
	Offset int32
	Q      *string
}

func (q *Queries) ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSuppliers, arg.Limit, arg.Offset, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TaxID,
			&i.Contact,
			&i.Region,
			&i.Rating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPurchaseOrderStatus = `-- name: SetPurchaseOrderStatus :one
UPDATE purchase_orders SET status=$2
WHERE id=$1 AND status=$3 AND deleted_at IS NULL RETURNING id, po_no, supplier_id, expected_at, status, created_at, updated_at, deleted_at, version, created_by
`

type SetPurchaseOrderStatusParams struct {
	ID         uuid.UUID
	ToStatus   string
	FromStatus string
}

// Guarded on the current status so a concurrent transition cannot slip through.
func (q *Queries) SetPurchaseOrderStatus(ctx context.Context, arg SetPurchaseOrderStatusParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, setPurchaseOrderStatus, arg.ID, arg.ToStatus, arg.FromStatus)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.PoNo,
		&i.SupplierID,
		&i.ExpectedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const sumReceivedForLine = `-- name: SumReceivedForLine :one
SELECT COALESCE(SUM(qty),0)::numeric FROM goods_receipt_lines
WHERE po_line_id=$1 AND deleted_at IS NULL
`

func (q *Queries) SumReceivedForLine(ctx context.Context, poLineID uuid.UUID) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, sumReceivedForLine, poLineID)
	var column_1 decimal.Decimal
	err := row.Scan(&column_1)
	return column_1, err
}
