// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: production.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countManufacturingOrders = `-- name: CountManufacturingOrders :one
SELECT count(*) FROM manufacturing_orders mo
JOIN items i ON i.id = mo.item_id
WHERE mo.deleted_at IS NULL
  AND ($1::text IS NULL OR mo.status = $1)
  AND ($2::text IS NULL
       OR unaccent(lower(mo.mo_no)) LIKE '%' || unaccent(lower($2)) || '%'
       OR unaccent(lower(i.sku)) LIKE '%' || unaccent(lower($2)) || '%')
`

type CountManufacturingOrdersParams struct {
	Status *string
	Q      *string
}

func (q *Queries) CountManufacturingOrders(ctx context.Context, arg CountManufacturingOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countManufacturingOrders, arg.Status, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createManufacturingOrder = `-- name: CreateManufacturingOrder :one

INSERT INTO manufacturing_orders (mo_no, item_id, batch_id, line, planned_qty, scheduled_for, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, mo_no, item_id, batch_id, line, planned_qty, scheduled_for, status, created_at, updated_at, deleted_at, version, created_by
`

type CreateManufacturingOrderParams struct {
	MoNo         string
	ItemID       uuid.UUID
	BatchID      uuid.NullUUID
	Line         *string
	PlannedQty   decimal.Decimal
	ScheduledFor pgtype.Date
	CreatedBy    uuid.NullUUID
}

// Производство — docs/02-SCHEMA.md §6.
//
// Actual output, yield and downtime are SUMS over production_entries, never
// columns on the order. There is deliberately no query here that writes them.
func (q *Queries) CreateManufacturingOrder(ctx context.Context, arg CreateManufacturingOrderParams) (ManufacturingOrder, error) {
	row := q.db.QueryRow(ctx, createManufacturingOrder,
		arg.MoNo,
		arg.ItemID,
		arg.BatchID,
		arg.Line,
		arg.PlannedQty,
		arg.ScheduledFor,
		arg.CreatedBy,
	)
	var i ManufacturingOrder
	err := row.Scan(
		&i.ID,
		&i.MoNo,
		&i.ItemID,
		&i.BatchID,
		&i.Line,
		&i.PlannedQty,
		&i.ScheduledFor,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getManufacturingOrder = `-- name: GetManufacturingOrder :one
SELECT id, mo_no, item_id, batch_id, line, planned_qty, scheduled_for, status, created_at, updated_at, deleted_at, version, created_by FROM manufacturing_orders WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetManufacturingOrder(ctx context.Context, id uuid.UUID) (ManufacturingOrder, error) {
	row := q.db.QueryRow(ctx, getManufacturingOrder, id)
	var i ManufacturingOrder
	err := row.Scan(
		&i.ID,
		&i.MoNo,
		&i.ItemID,
		&i.BatchID,
		&i.Line,
		&i.PlannedQty,
		&i.ScheduledFor,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getProductionTotals = `-- name: GetProductionTotals :one
SELECT
  COALESCE(SUM(good_qty), 0)::numeric     AS good_qty,
  COALESCE(SUM(scrap_qty), 0)::numeric    AS scrap_qty,
  COALESCE(SUM(downtime_min), 0)::bigint  AS downtime_min,
  count(*)::bigint                        AS entry_count
FROM production_entries
WHERE mo_id = $1 AND deleted_at IS NULL
`

type GetProductionTotalsRow struct {
	GoodQty     decimal.Decimal
	ScrapQty    decimal.Decimal
	DowntimeMin int64
	EntryCount  int64
}

// Yield is a computation, not a column (docs/02-SCHEMA.md:274).
func (q *Queries) GetProductionTotals(ctx context.Context, moID uuid.UUID) (GetProductionTotalsRow, error) {
	row := q.db.QueryRow(ctx, getProductionTotals, moID)
	var i GetProductionTotalsRow
	err := row.Scan(
		&i.GoodQty,
		&i.ScrapQty,
		&i.DowntimeMin,
		&i.EntryCount,
	)
	return i, err
}

const insertProductionEntry = `-- name: InsertProductionEntry :one
INSERT INTO production_entries (mo_id, good_qty, scrap_qty, downtime_min, note, recorded_by, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $6)
RETURNING id, mo_id, good_qty, scrap_qty, downtime_min, note, recorded_at, recorded_by, created_at, updated_at, deleted_at, version, created_by
`

type InsertProductionEntryParams struct {
	MoID        uuid.UUID
	GoodQty     decimal.Decimal
	ScrapQty    decimal.Decimal
	DowntimeMin int32
	Note        *string
	RecordedBy  uuid.NullUUID
}

func (q *Queries) InsertProductionEntry(ctx context.Context, arg InsertProductionEntryParams) (ProductionEntry, error) {
	row := q.db.QueryRow(ctx, insertProductionEntry,
		arg.MoID,
		arg.GoodQty,
		arg.ScrapQty,
		arg.DowntimeMin,
		arg.Note,
		arg.RecordedBy,
	)
	var i ProductionEntry
	err := row.Scan(
		&i.ID,
		&i.MoID,
		&i.GoodQty,
		&i.ScrapQty,
		&i.DowntimeMin,
		&i.Note,
		&i.RecordedAt,
		&i.RecordedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const listManufacturingOrders = `-- name: ListManufacturingOrders :many
SELECT mo.id, mo.mo_no, mo.item_id, mo.batch_id, mo.line, mo.planned_qty, mo.scheduled_for, mo.status, mo.created_at, mo.updated_at, mo.deleted_at, mo.version, mo.created_by, i.sku, b.batch_no,
  COALESCE((SELECT SUM(good_qty) FROM production_entries e
             WHERE e.mo_id = mo.id AND e.deleted_at IS NULL), 0)::numeric AS good_qty,
  COALESCE((SELECT SUM(scrap_qty) FROM production_entries e
             WHERE e.mo_id = mo.id AND e.deleted_at IS NULL), 0)::numeric AS scrap_qty
FROM manufacturing_orders mo
JOIN items i ON i.id = mo.item_id
LEFT JOIN batches b ON b.id = mo.batch_id
WHERE mo.deleted_at IS NULL
  AND ($3::text IS NULL OR mo.status = $3)
  AND ($4::text IS NULL
       OR unaccent(lower(mo.mo_no)) LIKE '%' || unaccent(lower($4)) || '%'
       OR unaccent(lower(i.sku)) LIKE '%' || unaccent(lower($4)) || '%')
ORDER BY mo.scheduled_for DESC NULLS LAST, mo.mo_no DESC
LIMIT $1 OFFSET $2
`

type ListManufacturingOrdersParams struct {
	Limit  int32
	Offset int32
	Status *string
	Q      *string
}

type ListManufacturingOrdersRow struct {
	ManufacturingOrder ManufacturingOrder
	Sku                string
	BatchNo            *string
	GoodQty            decimal.Decimal
	ScrapQty           decimal.Decimal
}

func (q *Queries) ListManufacturingOrders(ctx context.Context, arg ListManufacturingOrdersParams) ([]ListManufacturingOrdersRow, error) {
	rows, err := q.db.Query(ctx, listManufacturingOrders,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManufacturingOrdersRow{}
	for rows.Next() {
		var i ListManufacturingOrdersRow
		if err := rows.Scan(
			&i.ManufacturingOrder.ID,
			&i.ManufacturingOrder.MoNo,
			&i.ManufacturingOrder.ItemID,
			&i.ManufacturingOrder.BatchID,
			&i.ManufacturingOrder.Line,
			&i.ManufacturingOrder.PlannedQty,
			&i.ManufacturingOrder.ScheduledFor,
			&i.ManufacturingOrder.Status,
			&i.ManufacturingOrder.CreatedAt,
			&i.ManufacturingOrder.UpdatedAt,
			&i.ManufacturingOrder.DeletedAt,
			&i.ManufacturingOrder.Version,
			&i.ManufacturingOrder.CreatedBy,
			&i.Sku,
			&i.BatchNo,
			&i.GoodQty,
			&i.ScrapQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionEntries = `-- name: ListProductionEntries :many
SELECT id, mo_id, good_qty, scrap_qty, downtime_min, note, recorded_at, recorded_by, created_at, updated_at, deleted_at, version, created_by FROM production_entries
WHERE mo_id = $1 AND deleted_at IS NULL
ORDER BY recorded_at DESC
`

func (q *Queries) ListProductionEntries(ctx context.Context, moID uuid.UUID) ([]ProductionEntry, error) {
	rows, err := q.db.Query(ctx, listProductionEntries, moID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductionEntry{}
	for rows.Next() {
		var i ProductionEntry
		if err := rows.Scan(
			&i.ID,
			&i.MoID,
			&i.GoodQty,
			&i.ScrapQty,
			&i.DowntimeMin,
			&i.Note,
			&i.RecordedAt,
			&i.RecordedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setManufacturingOrderStatus = `-- name: SetManufacturingOrderStatus :one
UPDATE manufacturing_orders SET status = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, mo_no, item_id, batch_id, line, planned_qty, scheduled_for, status, created_at, updated_at, deleted_at, version, created_by
`

type SetManufacturingOrderStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetManufacturingOrderStatus(ctx context.Context, arg SetManufacturingOrderStatusParams) (ManufacturingOrder, error) {
	row := q.db.QueryRow(ctx, setManufacturingOrderStatus, arg.ID, arg.Status)
	var i ManufacturingOrder
	err := row.Scan(
		&i.ID,
		&i.MoNo,
		&i.ItemID,
		&i.BatchID,
		&i.Line,
		&i.PlannedQty,
		&i.ScheduledFor,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}
