// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quality.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countBatchesByStatus = `-- name: CountBatchesByStatus :one
SELECT count(*)::int FROM batches WHERE status = $1 AND deleted_at IS NULL
`

func (q *Queries) CountBatchesByStatus(ctx context.Context, status string) (int32, error) {
	row := q.db.QueryRow(ctx, countBatchesByStatus, status)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countFailedTests = `-- name: CountFailedTests :one
SELECT count(*)::int FROM quality_tests WHERE passed = false AND deleted_at IS NULL
`

func (q *Queries) CountFailedTests(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countFailedTests)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countQualityTestsPaged = `-- name: CountQualityTestsPaged :one
SELECT count(*) FROM quality_tests qt
JOIN batches b ON b.id = qt.batch_id
JOIN items i ON i.id = b.item_id
WHERE qt.deleted_at IS NULL
  AND ($1::text IS NULL OR b.status = $1)
  AND ($2::text IS NULL
       OR unaccent(lower(b.batch_no)) LIKE '%' || unaccent(lower($2)) || '%'
       OR unaccent(lower(i.sku)) LIKE '%' || unaccent(lower($2)) || '%')
`

type CountQualityTestsPagedParams struct {
	BatchStatus *string
	Q           *string
}

func (q *Queries) CountQualityTestsPaged(ctx context.Context, arg CountQualityTestsPagedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countQualityTestsPaged, arg.BatchStatus, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQualityTest = `-- name: CreateQualityTest :one

INSERT INTO quality_tests (batch_id, test_type, result_value, passed, inspector_id, notes, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $5)
RETURNING id, batch_id, test_type, result_value, passed, inspector_id, tested_at, notes, created_at, updated_at, deleted_at, version, created_by
`

type CreateQualityTestParams struct {
	BatchID     uuid.UUID
	TestType    string
	ResultValue *string
	Passed      *bool
	InspectorID uuid.NullUUID
	Notes       *string
}

// Качество и безопасность — docs/02-SCHEMA.md §7. The regulatory heart.
//
// batches.status is changed ONLY through here, and only by a batch_status_events
// row that names the deciding user. That table is the evidence trail behind the
// website's laboratory-control claim.
func (q *Queries) CreateQualityTest(ctx context.Context, arg CreateQualityTestParams) (QualityTest, error) {
	row := q.db.QueryRow(ctx, createQualityTest,
		arg.BatchID,
		arg.TestType,
		arg.ResultValue,
		arg.Passed,
		arg.InspectorID,
		arg.Notes,
	)
	var i QualityTest
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.TestType,
		&i.ResultValue,
		&i.Passed,
		&i.InspectorID,
		&i.TestedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const insertBatchStatusEvent = `-- name: InsertBatchStatusEvent :one
INSERT INTO batch_status_events (batch_id, from_status, to_status, decided_by, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, batch_id, from_status, to_status, decided_by, reason, occurred_at, created_at
`

type InsertBatchStatusEventParams struct {
	BatchID    uuid.UUID
	FromStatus *string
	ToStatus   string
	DecidedBy  uuid.UUID
	Reason     *string
}

// Append-only and immutable: no deleted_at, no version. This row is the evidence.
func (q *Queries) InsertBatchStatusEvent(ctx context.Context, arg InsertBatchStatusEventParams) (BatchStatusEvent, error) {
	row := q.db.QueryRow(ctx, insertBatchStatusEvent,
		arg.BatchID,
		arg.FromStatus,
		arg.ToStatus,
		arg.DecidedBy,
		arg.Reason,
	)
	var i BatchStatusEvent
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.FromStatus,
		&i.ToStatus,
		&i.DecidedBy,
		&i.Reason,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listBatchStatusEvents = `-- name: ListBatchStatusEvents :many
SELECT e.id, e.batch_id, e.from_status, e.to_status, e.decided_by, e.reason, e.occurred_at, e.created_at, u.full_name AS decided_by_name
FROM batch_status_events e
JOIN users u ON u.id = e.decided_by
WHERE e.batch_id = $1
ORDER BY e.occurred_at DESC
`

type ListBatchStatusEventsRow struct {
	ID            uuid.UUID
	BatchID       uuid.UUID
	FromStatus    *string
	ToStatus      string
	DecidedBy     uuid.UUID
	Reason        *string
	OccurredAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	DecidedByName string
}

func (q *Queries) ListBatchStatusEvents(ctx context.Context, batchID uuid.UUID) ([]ListBatchStatusEventsRow, error) {
	rows, err := q.db.Query(ctx, listBatchStatusEvents, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBatchStatusEventsRow{}
	for rows.Next() {
		var i ListBatchStatusEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.FromStatus,
			&i.ToStatus,
			&i.DecidedBy,
			&i.Reason,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.DecidedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQualityTests = `-- name: ListQualityTests :many
SELECT qt.id, qt.batch_id, qt.test_type, qt.result_value, qt.passed, qt.inspector_id, qt.tested_at, qt.notes, qt.created_at, qt.updated_at, qt.deleted_at, qt.version, qt.created_by, u.full_name AS inspector_name
FROM quality_tests qt
LEFT JOIN users u ON u.id = qt.inspector_id
WHERE qt.batch_id = $1 AND qt.deleted_at IS NULL
ORDER BY qt.tested_at DESC
`

type ListQualityTestsRow struct {
	ID            uuid.UUID
	BatchID       uuid.UUID
	TestType      string
	ResultValue   *string
	Passed        *bool
	InspectorID   uuid.NullUUID
	TestedAt      pgtype.Timestamptz
	Notes         *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	Version       int32
	CreatedBy     uuid.NullUUID
	InspectorName *string
}

func (q *Queries) ListQualityTests(ctx context.Context, batchID uuid.UUID) ([]ListQualityTestsRow, error) {
	rows, err := q.db.Query(ctx, listQualityTests, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQualityTestsRow{}
	for rows.Next() {
		var i ListQualityTestsRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.TestType,
			&i.ResultValue,
			&i.Passed,
			&i.InspectorID,
			&i.TestedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
			&i.InspectorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQualityTestsPaged = `-- name: ListQualityTestsPaged :many
SELECT qt.id, qt.batch_id, qt.test_type, qt.result_value, qt.passed, qt.inspector_id, qt.tested_at, qt.notes, qt.created_at, qt.updated_at, qt.deleted_at, qt.version, qt.created_by, b.batch_no, i.sku, b.status AS batch_status,
       COALESCE(u.full_name, '') AS inspector_name
FROM quality_tests qt
JOIN batches b ON b.id = qt.batch_id
JOIN items i ON i.id = b.item_id
LEFT JOIN users u ON u.id = qt.inspector_id
WHERE qt.deleted_at IS NULL
  AND ($3::text IS NULL OR b.status = $3)
  AND ($4::text IS NULL
       OR unaccent(lower(b.batch_no)) LIKE '%' || unaccent(lower($4)) || '%'
       OR unaccent(lower(i.sku)) LIKE '%' || unaccent(lower($4)) || '%')
ORDER BY qt.tested_at DESC
LIMIT $1 OFFSET $2
`

type ListQualityTestsPagedParams struct {
	Limit       int32
	Offset      int32
	BatchStatus *string
	Q           *string
}

type ListQualityTestsPagedRow struct {
	QualityTest   QualityTest
	BatchNo       string
	Sku           string
	BatchStatus   string
	InspectorName string
}

func (q *Queries) ListQualityTestsPaged(ctx context.Context, arg ListQualityTestsPagedParams) ([]ListQualityTestsPagedRow, error) {
	rows, err := q.db.Query(ctx, listQualityTestsPaged,
		arg.Limit,
		arg.Offset,
		arg.BatchStatus,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQualityTestsPagedRow{}
	for rows.Next() {
		var i ListQualityTestsPagedRow
		if err := rows.Scan(
			&i.QualityTest.ID,
			&i.QualityTest.BatchID,
			&i.QualityTest.TestType,
			&i.QualityTest.ResultValue,
			&i.QualityTest.Passed,
			&i.QualityTest.InspectorID,
			&i.QualityTest.TestedAt,
			&i.QualityTest.Notes,
			&i.QualityTest.CreatedAt,
			&i.QualityTest.UpdatedAt,
			&i.QualityTest.DeletedAt,
			&i.QualityTest.Version,
			&i.QualityTest.CreatedBy,
			&i.BatchNo,
			&i.Sku,
			&i.BatchStatus,
			&i.InspectorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionBatchStatus = `-- name: TransitionBatchStatus :one
UPDATE batches SET status = $2
WHERE id = $1 AND status = $3 AND deleted_at IS NULL
RETURNING id, batch_no, item_id, produced_on, expires_on, qr_payload, qr_issued_at, status, created_at, updated_at, deleted_at, version, created_by
`

type TransitionBatchStatusParams struct {
	ID         uuid.UUID
	ToStatus   string
	FromStatus string
}

// Guarded on the CURRENT status, so an illegal transition cannot slip through a
// read-then-write race. Zero rows means the batch moved underneath us.
func (q *Queries) TransitionBatchStatus(ctx context.Context, arg TransitionBatchStatusParams) (Batch, error) {
	row := q.db.QueryRow(ctx, transitionBatchStatus, arg.ID, arg.ToStatus, arg.FromStatus)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.BatchNo,
		&i.ItemID,
		&i.ProducedOn,
		&i.ExpiresOn,
		&i.QrPayload,
		&i.QrIssuedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}
