// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAudit(ctx context.Context, arg CountAuditParams) (int64, error)
	CountAuditForResource(ctx context.Context, arg CountAuditForResourceParams) (int64, error)
	CountItems(ctx context.Context) (int64, error)
	CountItemsByStatus(ctx context.Context, status string) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context, retain pgtype.Interval) error
	// Product master queries.
	//
	// Minimal for now: T03 wires sqlc and proves generation. The full Товары query
	// set — list with search and filters, detail with translations, packaging units
	// and price history — arrives with T11, which is the reference slice.
	//
	// Note there is no query here that reads or writes a stock quantity. There is no
	// such column; stock is derived from the movement ledger (CLAUDE.md §4.2, T16).
	GetItemByID(ctx context.Context, id uuid.UUID) (Item, error)
	GetItemBySKU(ctx context.Context, sku string) (Item, error)
	// Deliberately does not filter on expiry or revocation: the domain layer
	// distinguishes "unknown token" from "expired" from "revoked".
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	// Identity and session queries. Consumed by internal/auth (T05).
	//
	// Every read filters deleted_at IS NULL (CLAUDE.md §4.3). The one exception is
	// session lookup by token hash, which must find revoked and expired sessions so
	// the domain layer can reject them with a precise reason instead of a generic 401.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// A user's effective permissions are the union across all their roles
	// (docs/04-RBAC.md §1). Resolved per request and never cached (04-RBAC.md:148).
	GetUserPermissions(ctx context.Context, userID uuid.UUID) ([]GetUserPermissionsRow, error)
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]Role, error)
	// Audit log. Append-only: there is no update and no delete, by design
	// (docs/02-SCHEMA.md:123). Every mutation in the system writes one row, inside
	// the mutating transaction (docs/07-IMPLEMENTATION-PLAN.md I4).
	InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) (AuditLog, error)
	// The audit viewer (docs/04-RBAC.md §6), filterable by actor, resource and date
	// range. NULL means "no filter" for each dimension.
	ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error)
	// Powers the activity panel on every detail view (docs/05-MODULES.md §2).
	ListAuditForResource(ctx context.Context, arg ListAuditForResourceParams) ([]AuditLog, error)
	ListItemTranslations(ctx context.Context, itemID uuid.UUID) ([]ItemTranslation, error)
	// Increments the counter and locks the account once the threshold is reached.
	// Returning the row lets the caller report the resulting state without a re-read.
	RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) (User, error)
	RecordLoginSuccess(ctx context.Context, id uuid.UUID) error
	// Logout everywhere, required on password change (docs/03-API-CONTRACT.md:193).
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error
	// Idle-timeout support: slides the expiry window on activity.
	TouchSession(ctx context.Context, arg TouchSessionParams) error
}

var _ Querier = (*Queries)(nil)
