// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAssets = `-- name: CountAssets :one
SELECT count(*) FROM assets a
WHERE a.deleted_at IS NULL
  AND ($1::text IS NULL OR a.status = $1)
  AND ($2::text IS NULL
       OR unaccent(lower(a.asset_no)) LIKE '%'||unaccent(lower($2))||'%'
       OR unaccent(lower(a.name)) LIKE '%'||unaccent(lower($2))||'%'
       OR unaccent(lower(COALESCE(a.line,''))) LIKE '%'||unaccent(lower($2))||'%')
`

type CountAssetsParams struct {
	Status *string
	Q      *string
}

func (q *Queries) CountAssets(ctx context.Context, arg CountAssetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssets, arg.Status, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocuments = `-- name: CountDocuments :one
SELECT count(*) FROM documents d
WHERE d.deleted_at IS NULL
  AND ($1::text IS NULL OR d.status = $1)
  AND ($2::text IS NULL
       OR unaccent(lower(d.doc_no)) LIKE '%'||unaccent(lower($2))||'%'
       OR unaccent(lower(d.title)) LIKE '%'||unaccent(lower($2))||'%')
`

type CountDocumentsParams struct {
	Status *string
	Q      *string
}

func (q *Queries) CountDocuments(ctx context.Context, arg CountDocumentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDocuments, arg.Status, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmployees = `-- name: CountEmployees :one
SELECT count(*) FROM employees e
LEFT JOIN positions p ON p.id = e.position_id AND p.deleted_at IS NULL
WHERE e.deleted_at IS NULL
  AND ($1::text IS NULL OR e.status = $1)
  AND ($2::text IS NULL
       OR unaccent(lower(e.full_name)) LIKE '%'||unaccent(lower($2))||'%'
       OR unaccent(lower(COALESCE(p.title,''))) LIKE '%'||unaccent(lower($2))||'%')
`

type CountEmployeesParams struct {
	Status *string
	Q      *string
}

func (q *Queries) CountEmployees(ctx context.Context, arg CountEmployeesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployees, arg.Status, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (asset_no, name, asset_type, line, commissioned_on, warranty_until, status, created_by)
VALUES ($1,$2,$3,$4,$5,$6,COALESCE($8::text,'running'),$7)
RETURNING id, asset_no, name, asset_type, line, commissioned_on, warranty_until, status, created_at, updated_at, deleted_at, version, created_by
`

type CreateAssetParams struct {
	AssetNo        string
	Name           string
	AssetType      *string
	Line           *string
	CommissionedOn pgtype.Date
	WarrantyUntil  pgtype.Date
	CreatedBy      uuid.NullUUID
	Status         *string
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.AssetNo,
		arg.Name,
		arg.AssetType,
		arg.Line,
		arg.CommissionedOn,
		arg.WarrantyUntil,
		arg.CreatedBy,
		arg.Status,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AssetNo,
		&i.Name,
		&i.AssetType,
		&i.Line,
		&i.CommissionedOn,
		&i.WarrantyUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (doc_no, title, doc_type, owner_id, valid_until, status, created_by)
VALUES ($1,$2,$3,$4,$5,COALESCE($7::text,'draft'),$6)
RETURNING id, doc_no, title, doc_type, owner_id, valid_until, status, created_at, updated_at, deleted_at, version, created_by
`

type CreateDocumentParams struct {
	DocNo      string
	Title      string
	DocType    *string
	OwnerID    uuid.NullUUID
	ValidUntil pgtype.Date
	CreatedBy  uuid.NullUUID
	Status     *string
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.DocNo,
		arg.Title,
		arg.DocType,
		arg.OwnerID,
		arg.ValidUntil,
		arg.CreatedBy,
		arg.Status,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.Title,
		&i.DocType,
		&i.OwnerID,
		&i.ValidUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (full_name, position_id, shift, hired_on, contract_until, status, created_by)
VALUES ($1,$2,$3,$4,$5,COALESCE($7::text,'active'),$6)
RETURNING id, full_name, position_id, shift, hired_on, contract_until, status, created_at, updated_at, deleted_at, version, created_by
`

type CreateEmployeeParams struct {
	FullName      string
	PositionID    uuid.NullUUID
	Shift         *string
	HiredOn       pgtype.Date
	ContractUntil pgtype.Date
	CreatedBy     uuid.NullUUID
	Status        *string
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.FullName,
		arg.PositionID,
		arg.Shift,
		arg.HiredOn,
		arg.ContractUntil,
		arg.CreatedBy,
		arg.Status,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PositionID,
		&i.Shift,
		&i.HiredOn,
		&i.ContractUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const createMaintenanceEvent = `-- name: CreateMaintenanceEvent :one
INSERT INTO maintenance_events (asset_id, event_type, performed_at, next_due_on, notes, created_by)
VALUES ($1,$2,COALESCE($6::timestamptz, now()),$3,$4,$5)
RETURNING id, asset_id, event_type, performed_at, next_due_on, notes, created_at, updated_at, deleted_at, version, created_by
`

type CreateMaintenanceEventParams struct {
	AssetID     uuid.UUID
	EventType   *string
	NextDueOn   pgtype.Date
	Notes       *string
	CreatedBy   uuid.NullUUID
	PerformedAt pgtype.Timestamptz
}

func (q *Queries) CreateMaintenanceEvent(ctx context.Context, arg CreateMaintenanceEventParams) (MaintenanceEvent, error) {
	row := q.db.QueryRow(ctx, createMaintenanceEvent,
		arg.AssetID,
		arg.EventType,
		arg.NextDueOn,
		arg.Notes,
		arg.CreatedBy,
		arg.PerformedAt,
	)
	var i MaintenanceEvent
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.EventType,
		&i.PerformedAt,
		&i.NextDueOn,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, asset_no, name, asset_type, line, commissioned_on, warranty_until, status, created_at, updated_at, deleted_at, version, created_by FROM assets WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAsset(ctx context.Context, id uuid.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AssetNo,
		&i.Name,
		&i.AssetType,
		&i.Line,
		&i.CommissionedOn,
		&i.WarrantyUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getAssetDetail = `-- name: GetAssetDetail :one
SELECT a.id, a.asset_no, a.name, a.asset_type, a.line, a.commissioned_on, a.warranty_until, a.status, a.created_at, a.updated_at, a.deleted_at, a.version, a.created_by,
  (SELECT max(m.next_due_on) FROM maintenance_events m
    WHERE m.asset_id = a.id AND m.deleted_at IS NULL)::date AS next_due_on,
  (SELECT max(m.performed_at) FROM maintenance_events m
    WHERE m.asset_id = a.id AND m.deleted_at IS NULL)::timestamptz AS last_service_at
FROM assets a
WHERE a.id = $1 AND a.deleted_at IS NULL
`

type GetAssetDetailRow struct {
	Asset         Asset
	NextDueOn     pgtype.Date
	LastServiceAt pgtype.Timestamptz
}

// Mirrors ListAssets, including the two derived service dates, so an asset's
// register row and its detail view cannot disagree about when it is next due.
func (q *Queries) GetAssetDetail(ctx context.Context, id uuid.UUID) (GetAssetDetailRow, error) {
	row := q.db.QueryRow(ctx, getAssetDetail, id)
	var i GetAssetDetailRow
	err := row.Scan(
		&i.Asset.ID,
		&i.Asset.AssetNo,
		&i.Asset.Name,
		&i.Asset.AssetType,
		&i.Asset.Line,
		&i.Asset.CommissionedOn,
		&i.Asset.WarrantyUntil,
		&i.Asset.Status,
		&i.Asset.CreatedAt,
		&i.Asset.UpdatedAt,
		&i.Asset.DeletedAt,
		&i.Asset.Version,
		&i.Asset.CreatedBy,
		&i.NextDueOn,
		&i.LastServiceAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT d.id, d.doc_no, d.title, d.doc_type, d.owner_id, d.valid_until, d.status, d.created_at, d.updated_at, d.deleted_at, d.version, d.created_by, u.full_name AS owner_name
FROM documents d
LEFT JOIN users u ON u.id = d.owner_id
WHERE d.id = $1 AND d.deleted_at IS NULL
`

type GetDocumentRow struct {
	ID         uuid.UUID
	DocNo      string
	Title      string
	DocType    *string
	OwnerID    uuid.NullUUID
	ValidUntil pgtype.Date
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	Version    int32
	CreatedBy  uuid.NullUUID
	OwnerName  *string
}

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.Title,
		&i.DocType,
		&i.OwnerID,
		&i.ValidUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
		&i.OwnerName,
	)
	return i, err
}

const getEmployee = `-- name: GetEmployee :one
SELECT e.id, e.full_name, e.position_id, e.shift, e.hired_on, e.contract_until, e.status, e.created_at, e.updated_at, e.deleted_at, e.version, e.created_by, p.title AS position_title, d.name AS department_name
FROM employees e
LEFT JOIN positions p ON p.id = e.position_id AND p.deleted_at IS NULL
LEFT JOIN departments d ON d.id = p.department_id AND d.deleted_at IS NULL
WHERE e.id = $1 AND e.deleted_at IS NULL
`

type GetEmployeeRow struct {
	Employee       Employee
	PositionTitle  *string
	DepartmentName *string
}

func (q *Queries) GetEmployee(ctx context.Context, id uuid.UUID) (GetEmployeeRow, error) {
	row := q.db.QueryRow(ctx, getEmployee, id)
	var i GetEmployeeRow
	err := row.Scan(
		&i.Employee.ID,
		&i.Employee.FullName,
		&i.Employee.PositionID,
		&i.Employee.Shift,
		&i.Employee.HiredOn,
		&i.Employee.ContractUntil,
		&i.Employee.Status,
		&i.Employee.CreatedAt,
		&i.Employee.UpdatedAt,
		&i.Employee.DeletedAt,
		&i.Employee.Version,
		&i.Employee.CreatedBy,
		&i.PositionTitle,
		&i.DepartmentName,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many

SELECT a.id, a.asset_no, a.name, a.asset_type, a.line, a.commissioned_on, a.warranty_until, a.status, a.created_at, a.updated_at, a.deleted_at, a.version, a.created_by,
  -- Cast for the same reason as migration 00005: sqlc types a bare aggregate as
  -- interface{}, which is unusable without a runtime assertion at every call.
  (SELECT max(m.next_due_on) FROM maintenance_events m
    WHERE m.asset_id = a.id AND m.deleted_at IS NULL)::date AS next_due_on,
  (SELECT max(m.performed_at) FROM maintenance_events m
    WHERE m.asset_id = a.id AND m.deleted_at IS NULL)::timestamptz AS last_service_at
FROM assets a
WHERE a.deleted_at IS NULL
  AND ($3::text IS NULL OR a.status = $3)
  AND ($4::text IS NULL
       OR unaccent(lower(a.asset_no)) LIKE '%'||unaccent(lower($4))||'%'
       OR unaccent(lower(a.name)) LIKE '%'||unaccent(lower($4))||'%'
       OR unaccent(lower(COALESCE(a.line,''))) LIKE '%'||unaccent(lower($4))||'%')
ORDER BY a.asset_no
LIMIT $1 OFFSET $2
`

type ListAssetsParams struct {
	Limit  int32
	Offset int32
	Status *string
	Q      *string
}

type ListAssetsRow struct {
	Asset         Asset
	NextDueOn     pgtype.Date
	LastServiceAt pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// Оборудование и ТО
// ---------------------------------------------------------------------------
func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]ListAssetsRow, error) {
	rows, err := q.db.Query(ctx, listAssets,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetsRow{}
	for rows.Next() {
		var i ListAssetsRow
		if err := rows.Scan(
			&i.Asset.ID,
			&i.Asset.AssetNo,
			&i.Asset.Name,
			&i.Asset.AssetType,
			&i.Asset.Line,
			&i.Asset.CommissionedOn,
			&i.Asset.WarrantyUntil,
			&i.Asset.Status,
			&i.Asset.CreatedAt,
			&i.Asset.UpdatedAt,
			&i.Asset.DeletedAt,
			&i.Asset.Version,
			&i.Asset.CreatedBy,
			&i.NextDueOn,
			&i.LastServiceAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many

SELECT d.id, d.doc_no, d.title, d.doc_type, d.owner_id, d.valid_until, d.status, d.created_at, d.updated_at, d.deleted_at, d.version, d.created_by, u.full_name AS owner_name
FROM documents d
LEFT JOIN users u ON u.id = d.owner_id
WHERE d.deleted_at IS NULL
  AND ($3::text IS NULL OR d.status = $3)
  AND ($4::text IS NULL
       OR unaccent(lower(d.doc_no)) LIKE '%'||unaccent(lower($4))||'%'
       OR unaccent(lower(d.title)) LIKE '%'||unaccent(lower($4))||'%')
ORDER BY d.valid_until ASC NULLS LAST, d.doc_no
LIMIT $1 OFFSET $2
`

type ListDocumentsParams struct {
	Limit  int32
	Offset int32
	Status *string
	Q      *string
}

type ListDocumentsRow struct {
	ID         uuid.UUID
	DocNo      string
	Title      string
	DocType    *string
	OwnerID    uuid.NullUUID
	ValidUntil pgtype.Date
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	Version    int32
	CreatedBy  uuid.NullUUID
	OwnerName  *string
}

// ---------------------------------------------------------------------------
// Документы
// ---------------------------------------------------------------------------
func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]ListDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listDocuments,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsRow{}
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocNo,
			&i.Title,
			&i.DocType,
			&i.OwnerID,
			&i.ValidUntil,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployees = `-- name: ListEmployees :many


SELECT e.id, e.full_name, e.position_id, e.shift, e.hired_on, e.contract_until, e.status, e.created_at, e.updated_at, e.deleted_at, e.version, e.created_by, p.title AS position_title, d.name AS department_name
FROM employees e
LEFT JOIN positions p ON p.id = e.position_id AND p.deleted_at IS NULL
LEFT JOIN departments d ON d.id = p.department_id AND d.deleted_at IS NULL
WHERE e.deleted_at IS NULL
  AND ($3::text IS NULL OR e.status = $3)
  AND ($4::text IS NULL
       OR unaccent(lower(e.full_name)) LIKE '%'||unaccent(lower($4))||'%'
       OR unaccent(lower(COALESCE(p.title,''))) LIKE '%'||unaccent(lower($4))||'%')
ORDER BY
  -- Contracts closest to expiry first: that is the column this list exists for.
  e.contract_until ASC NULLS LAST, e.full_name
LIMIT $1 OFFSET $2
`

type ListEmployeesParams struct {
	Limit  int32
	Offset int32
	Status *string
	Q      *string
}

type ListEmployeesRow struct {
	Employee       Employee
	PositionTitle  *string
	DepartmentName *string
}

// Персонал, Оборудование и ТО, Документы — docs/05-MODULES.md §12, §13, §14.
//
// These three are registries rather than transaction flows: rows are created,
// kept current, and watched for expiry. What they share is a date that runs out
// — a contract, a service interval, a certificate — which is why all three feed
// standing conditions in the alerts service rather than firing events.
// ---------------------------------------------------------------------------
// Персонал
// ---------------------------------------------------------------------------
func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]ListEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listEmployees,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesRow{}
	for rows.Next() {
		var i ListEmployeesRow
		if err := rows.Scan(
			&i.Employee.ID,
			&i.Employee.FullName,
			&i.Employee.PositionID,
			&i.Employee.Shift,
			&i.Employee.HiredOn,
			&i.Employee.ContractUntil,
			&i.Employee.Status,
			&i.Employee.CreatedAt,
			&i.Employee.UpdatedAt,
			&i.Employee.DeletedAt,
			&i.Employee.Version,
			&i.Employee.CreatedBy,
			&i.PositionTitle,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceEvents = `-- name: ListMaintenanceEvents :many
SELECT id, asset_id, event_type, performed_at, next_due_on, notes, created_at, updated_at, deleted_at, version, created_by FROM maintenance_events
WHERE asset_id = $1 AND deleted_at IS NULL
ORDER BY performed_at DESC NULLS LAST, created_at DESC
`

// Append-only in practice: a service record is what someone did on a date, and
// there is no endpoint that edits one.
func (q *Queries) ListMaintenanceEvents(ctx context.Context, assetID uuid.UUID) ([]MaintenanceEvent, error) {
	rows, err := q.db.Query(ctx, listMaintenanceEvents, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceEvent{}
	for rows.Next() {
		var i MaintenanceEvent
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.EventType,
			&i.PerformedAt,
			&i.NextDueOn,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositions = `-- name: ListPositions :many
SELECT p.id, p.department_id, p.title, p.created_at, p.updated_at, p.deleted_at, p.version, p.created_by, d.name AS department_name
FROM positions p
JOIN departments d ON d.id = p.department_id AND d.deleted_at IS NULL
WHERE p.deleted_at IS NULL ORDER BY d.name, p.title
`

type ListPositionsRow struct {
	ID             uuid.UUID
	DepartmentID   uuid.UUID
	Title          string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	Version        int32
	CreatedBy      uuid.NullUUID
	DepartmentName string
}

func (q *Queries) ListPositions(ctx context.Context) ([]ListPositionsRow, error) {
	rows, err := q.db.Query(ctx, listPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPositionsRow{}
	for rows.Next() {
		var i ListPositionsRow
		if err := rows.Scan(
			&i.ID,
			&i.DepartmentID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tombstoneAsset = `-- name: TombstoneAsset :one
UPDATE assets SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL AND version = $2
RETURNING id, asset_no, name, asset_type, line, commissioned_on, warranty_until, status, created_at, updated_at, deleted_at, version, created_by
`

type TombstoneAssetParams struct {
	ID      uuid.UUID
	Version int32
}

func (q *Queries) TombstoneAsset(ctx context.Context, arg TombstoneAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, tombstoneAsset, arg.ID, arg.Version)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AssetNo,
		&i.Name,
		&i.AssetType,
		&i.Line,
		&i.CommissionedOn,
		&i.WarrantyUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const tombstoneDocument = `-- name: TombstoneDocument :one
UPDATE documents SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL AND version = $2
RETURNING id, doc_no, title, doc_type, owner_id, valid_until, status, created_at, updated_at, deleted_at, version, created_by
`

type TombstoneDocumentParams struct {
	ID      uuid.UUID
	Version int32
}

func (q *Queries) TombstoneDocument(ctx context.Context, arg TombstoneDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, tombstoneDocument, arg.ID, arg.Version)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.Title,
		&i.DocType,
		&i.OwnerID,
		&i.ValidUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const tombstoneEmployee = `-- name: TombstoneEmployee :one
UPDATE employees SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL AND version = $2
RETURNING id, full_name, position_id, shift, hired_on, contract_until, status, created_at, updated_at, deleted_at, version, created_by
`

type TombstoneEmployeeParams struct {
	ID      uuid.UUID
	Version int32
}

func (q *Queries) TombstoneEmployee(ctx context.Context, arg TombstoneEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, tombstoneEmployee, arg.ID, arg.Version)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PositionID,
		&i.Shift,
		&i.HiredOn,
		&i.ContractUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const transitionDocument = `-- name: TransitionDocument :one
UPDATE documents SET status = $2::text
WHERE id = $1 AND deleted_at IS NULL AND status = $3::text
RETURNING id, doc_no, title, doc_type, owner_id, valid_until, status, created_at, updated_at, deleted_at, version, created_by
`

type TransitionDocumentParams struct {
	ID         uuid.UUID
	ToStatus   string
	FromStatus string
}

// Guarded on the current status, so a concurrent transition cannot slip between
// the caller's read and this write.
func (q *Queries) TransitionDocument(ctx context.Context, arg TransitionDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, transitionDocument, arg.ID, arg.ToStatus, arg.FromStatus)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.Title,
		&i.DocType,
		&i.OwnerID,
		&i.ValidUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets SET
  asset_no = $2, name = $3, asset_type = $4, line = $5,
  commissioned_on = $6, warranty_until = $7, status = $8
WHERE id = $1 AND deleted_at IS NULL AND version = $9
RETURNING id, asset_no, name, asset_type, line, commissioned_on, warranty_until, status, created_at, updated_at, deleted_at, version, created_by
`

type UpdateAssetParams struct {
	ID             uuid.UUID
	AssetNo        string
	Name           string
	AssetType      *string
	Line           *string
	CommissionedOn pgtype.Date
	WarrantyUntil  pgtype.Date
	Status         string
	Version        int32
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.ID,
		arg.AssetNo,
		arg.Name,
		arg.AssetType,
		arg.Line,
		arg.CommissionedOn,
		arg.WarrantyUntil,
		arg.Status,
		arg.Version,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AssetNo,
		&i.Name,
		&i.AssetType,
		&i.Line,
		&i.CommissionedOn,
		&i.WarrantyUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents SET
  doc_no = $2, title = $3, doc_type = $4, owner_id = $5, valid_until = $6
WHERE id = $1 AND deleted_at IS NULL AND version = $7
RETURNING id, doc_no, title, doc_type, owner_id, valid_until, status, created_at, updated_at, deleted_at, version, created_by
`

type UpdateDocumentParams struct {
	ID         uuid.UUID
	DocNo      string
	Title      string
	DocType    *string
	OwnerID    uuid.NullUUID
	ValidUntil pgtype.Date
	Version    int32
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.ID,
		arg.DocNo,
		arg.Title,
		arg.DocType,
		arg.OwnerID,
		arg.ValidUntil,
		arg.Version,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.DocNo,
		&i.Title,
		&i.DocType,
		&i.OwnerID,
		&i.ValidUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees SET
  full_name = $2, position_id = $3, shift = $4,
  hired_on = $5, contract_until = $6, status = $7
WHERE id = $1 AND deleted_at IS NULL AND version = $8
RETURNING id, full_name, position_id, shift, hired_on, contract_until, status, created_at, updated_at, deleted_at, version, created_by
`

type UpdateEmployeeParams struct {
	ID            uuid.UUID
	FullName      string
	PositionID    uuid.NullUUID
	Shift         *string
	HiredOn       pgtype.Date
	ContractUntil pgtype.Date
	Status        string
	Version       int32
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.FullName,
		arg.PositionID,
		arg.Shift,
		arg.HiredOn,
		arg.ContractUntil,
		arg.Status,
		arg.Version,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PositionID,
		&i.Shift,
		&i.HiredOn,
		&i.ContractUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}
