// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countOverdueTasks = `-- name: CountOverdueTasks :one
SELECT count(*)::int FROM tasks
WHERE deleted_at IS NULL AND status='open' AND due_on < CURRENT_DATE
`

func (q *Queries) CountOverdueTasks(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countOverdueTasks)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countSalesOrders = `-- name: CountSalesOrders :one
SELECT count(*) FROM sales_orders so JOIN customers c ON c.id=so.customer_id
WHERE so.deleted_at IS NULL
  AND ($1::text IS NULL OR so.status=$1)
  AND ($2::text IS NULL OR unaccent(lower(so.so_no)) LIKE '%'||unaccent(lower($2))||'%'
       OR unaccent(lower(c.name)) LIKE '%'||unaccent(lower($2))||'%')
`

type CountSalesOrdersParams struct {
	Status *string
	Q      *string
}

func (q *Queries) CountSalesOrders(ctx context.Context, arg CountSalesOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSalesOrders, arg.Status, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countShipments = `-- name: CountShipments :one
SELECT count(*) FROM shipments WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status=$1)
  AND ($2::text IS NULL OR unaccent(lower(trip_no)) LIKE '%'||unaccent(lower($2))||'%')
`

type CountShipmentsParams struct {
	Status *string
	Q      *string
}

func (q *Queries) CountShipments(ctx context.Context, arg CountShipmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countShipments, arg.Status, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSalesOrder = `-- name: CreateSalesOrder :one

INSERT INTO sales_orders (so_no, customer_id, ordered_on, created_by)
VALUES ($1,$2,$3,$4) RETURNING id, so_no, customer_id, ordered_on, status, created_at, updated_at, deleted_at, version, created_by
`

type CreateSalesOrderParams struct {
	SoNo       string
	CustomerID uuid.UUID
	OrderedOn  pgtype.Date
	CreatedBy  uuid.NullUUID
}

// CRM и продажи, Логистика. Both enforce the released-batch rule.
func (q *Queries) CreateSalesOrder(ctx context.Context, arg CreateSalesOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, createSalesOrder,
		arg.SoNo,
		arg.CustomerID,
		arg.OrderedOn,
		arg.CreatedBy,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.SoNo,
		&i.CustomerID,
		&i.OrderedOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const createSalesOrderLine = `-- name: CreateSalesOrderLine :one
INSERT INTO sales_order_lines (sales_order_id, item_id, batch_id, qty, unit_price, created_by)
VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, sales_order_id, item_id, batch_id, qty, unit_price, created_at, updated_at, deleted_at, version, created_by
`

type CreateSalesOrderLineParams struct {
	SalesOrderID uuid.UUID
	ItemID       uuid.UUID
	BatchID      uuid.NullUUID
	Qty          decimal.Decimal
	UnitPrice    decimal.Decimal
	CreatedBy    uuid.NullUUID
}

func (q *Queries) CreateSalesOrderLine(ctx context.Context, arg CreateSalesOrderLineParams) (SalesOrderLine, error) {
	row := q.db.QueryRow(ctx, createSalesOrderLine,
		arg.SalesOrderID,
		arg.ItemID,
		arg.BatchID,
		arg.Qty,
		arg.UnitPrice,
		arg.CreatedBy,
	)
	var i SalesOrderLine
	err := row.Scan(
		&i.ID,
		&i.SalesOrderID,
		&i.ItemID,
		&i.BatchID,
		&i.Qty,
		&i.UnitPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const createShipment = `-- name: CreateShipment :one
INSERT INTO shipments (trip_no, route_from, route_to, driver_id, vehicle_id, transport_cost, created_by)
VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, trip_no, route_from, route_to, driver_id, vehicle_id, transport_cost, status, departed_at, delivered_at, created_at, updated_at, deleted_at, version, created_by
`

type CreateShipmentParams struct {
	TripNo        string
	RouteFrom     *string
	RouteTo       *string
	DriverID      uuid.NullUUID
	VehicleID     uuid.NullUUID
	TransportCost decimal.NullDecimal
	CreatedBy     uuid.NullUUID
}

func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, createShipment,
		arg.TripNo,
		arg.RouteFrom,
		arg.RouteTo,
		arg.DriverID,
		arg.VehicleID,
		arg.TransportCost,
		arg.CreatedBy,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TripNo,
		&i.RouteFrom,
		&i.RouteTo,
		&i.DriverID,
		&i.VehicleID,
		&i.TransportCost,
		&i.Status,
		&i.DepartedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const createShipmentLine = `-- name: CreateShipmentLine :one
INSERT INTO shipment_lines (shipment_id, item_id, batch_id, qty, created_by)
VALUES ($1,$2,$3,$4,$5) RETURNING id, shipment_id, item_id, batch_id, qty, created_at, updated_at, deleted_at, version, created_by
`

type CreateShipmentLineParams struct {
	ShipmentID uuid.UUID
	ItemID     uuid.UUID
	BatchID    uuid.UUID
	Qty        decimal.Decimal
	CreatedBy  uuid.NullUUID
}

func (q *Queries) CreateShipmentLine(ctx context.Context, arg CreateShipmentLineParams) (ShipmentLine, error) {
	row := q.db.QueryRow(ctx, createShipmentLine,
		arg.ShipmentID,
		arg.ItemID,
		arg.BatchID,
		arg.Qty,
		arg.CreatedBy,
	)
	var i ShipmentLine
	err := row.Scan(
		&i.ID,
		&i.ShipmentID,
		&i.ItemID,
		&i.BatchID,
		&i.Qty,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getSalesOrder = `-- name: GetSalesOrder :one
SELECT id, so_no, customer_id, ordered_on, status, created_at, updated_at, deleted_at, version, created_by FROM sales_orders WHERE id=$1 AND deleted_at IS NULL
`

func (q *Queries) GetSalesOrder(ctx context.Context, id uuid.UUID) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, getSalesOrder, id)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.SoNo,
		&i.CustomerID,
		&i.OrderedOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getShipment = `-- name: GetShipment :one
SELECT id, trip_no, route_from, route_to, driver_id, vehicle_id, transport_cost, status, departed_at, delivered_at, created_at, updated_at, deleted_at, version, created_by FROM shipments WHERE id=$1 AND deleted_at IS NULL
`

func (q *Queries) GetShipment(ctx context.Context, id uuid.UUID) (Shipment, error) {
	row := q.db.QueryRow(ctx, getShipment, id)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TripNo,
		&i.RouteFrom,
		&i.RouteTo,
		&i.DriverID,
		&i.VehicleID,
		&i.TransportCost,
		&i.Status,
		&i.DepartedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const listSalesOrderLines = `-- name: ListSalesOrderLines :many
SELECT l.id, l.sales_order_id, l.item_id, l.batch_id, l.qty, l.unit_price, l.created_at, l.updated_at, l.deleted_at, l.version, l.created_by, i.sku, COALESCE(tr.name, i.sku) AS item_name, b.batch_no, b.status AS batch_status
FROM sales_order_lines l
JOIN items i ON i.id=l.item_id
LEFT JOIN batches b ON b.id=l.batch_id
LEFT JOIN item_translations tr
  ON tr.item_id = i.id AND tr.locale = 'ru' AND tr.deleted_at IS NULL
WHERE l.sales_order_id=$1 AND l.deleted_at IS NULL ORDER BY i.sku
`

type ListSalesOrderLinesRow struct {
	ID           uuid.UUID
	SalesOrderID uuid.UUID
	ItemID       uuid.UUID
	BatchID      uuid.NullUUID
	Qty          decimal.Decimal
	UnitPrice    decimal.Decimal
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	Version      int32
	CreatedBy    uuid.NullUUID
	Sku          string
	ItemName     string
	BatchNo      *string
	BatchStatus  *string
}

func (q *Queries) ListSalesOrderLines(ctx context.Context, salesOrderID uuid.UUID) ([]ListSalesOrderLinesRow, error) {
	rows, err := q.db.Query(ctx, listSalesOrderLines, salesOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesOrderLinesRow{}
	for rows.Next() {
		var i ListSalesOrderLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.SalesOrderID,
			&i.ItemID,
			&i.BatchID,
			&i.Qty,
			&i.UnitPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
			&i.Sku,
			&i.ItemName,
			&i.BatchNo,
			&i.BatchStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrders = `-- name: ListSalesOrders :many
SELECT so.id, so.so_no, so.customer_id, so.ordered_on, so.status, so.created_at, so.updated_at, so.deleted_at, so.version, so.created_by, c.name AS customer_name,
  COALESCE((SELECT SUM(l.qty*l.unit_price) FROM sales_order_lines l
            WHERE l.sales_order_id=so.id AND l.deleted_at IS NULL),0)::numeric AS total_amount
FROM sales_orders so JOIN customers c ON c.id=so.customer_id
WHERE so.deleted_at IS NULL
  AND ($3::text IS NULL OR so.status=$3)
  AND ($4::text IS NULL OR unaccent(lower(so.so_no)) LIKE '%'||unaccent(lower($4))||'%'
       OR unaccent(lower(c.name)) LIKE '%'||unaccent(lower($4))||'%')
ORDER BY so.ordered_on DESC NULLS LAST, so.so_no DESC LIMIT $1 OFFSET $2
`

type ListSalesOrdersParams struct {
	Limit  int32
	Offset int32
	Status *string
	Q      *string
}

type ListSalesOrdersRow struct {
	SalesOrder   SalesOrder
	CustomerName string
	TotalAmount  decimal.Decimal
}

func (q *Queries) ListSalesOrders(ctx context.Context, arg ListSalesOrdersParams) ([]ListSalesOrdersRow, error) {
	rows, err := q.db.Query(ctx, listSalesOrders,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesOrdersRow{}
	for rows.Next() {
		var i ListSalesOrdersRow
		if err := rows.Scan(
			&i.SalesOrder.ID,
			&i.SalesOrder.SoNo,
			&i.SalesOrder.CustomerID,
			&i.SalesOrder.OrderedOn,
			&i.SalesOrder.Status,
			&i.SalesOrder.CreatedAt,
			&i.SalesOrder.UpdatedAt,
			&i.SalesOrder.DeletedAt,
			&i.SalesOrder.Version,
			&i.SalesOrder.CreatedBy,
			&i.CustomerName,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipmentLines = `-- name: ListShipmentLines :many
SELECT l.id, l.shipment_id, l.item_id, l.batch_id, l.qty, l.created_at, l.updated_at, l.deleted_at, l.version, l.created_by, i.sku, COALESCE(tr.name, i.sku) AS item_name, b.batch_no, b.status AS batch_status
FROM shipment_lines l JOIN items i ON i.id=l.item_id JOIN batches b ON b.id=l.batch_id
LEFT JOIN item_translations tr
  ON tr.item_id = i.id AND tr.locale = 'ru' AND tr.deleted_at IS NULL
WHERE l.shipment_id=$1 AND l.deleted_at IS NULL ORDER BY i.sku
`

type ListShipmentLinesRow struct {
	ID          uuid.UUID
	ShipmentID  uuid.UUID
	ItemID      uuid.UUID
	BatchID     uuid.UUID
	Qty         decimal.Decimal
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	Version     int32
	CreatedBy   uuid.NullUUID
	Sku         string
	ItemName    string
	BatchNo     string
	BatchStatus string
}

func (q *Queries) ListShipmentLines(ctx context.Context, shipmentID uuid.UUID) ([]ListShipmentLinesRow, error) {
	rows, err := q.db.Query(ctx, listShipmentLines, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShipmentLinesRow{}
	for rows.Next() {
		var i ListShipmentLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.ShipmentID,
			&i.ItemID,
			&i.BatchID,
			&i.Qty,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
			&i.Sku,
			&i.ItemName,
			&i.BatchNo,
			&i.BatchStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShipments = `-- name: ListShipments :many
SELECT s.id, s.trip_no, s.route_from, s.route_to, s.driver_id, s.vehicle_id, s.transport_cost, s.status, s.departed_at, s.delivered_at, s.created_at, s.updated_at, s.deleted_at, s.version, s.created_by, e.full_name AS driver_name, v.plate AS vehicle_plate
FROM shipments s
LEFT JOIN employees e ON e.id=s.driver_id
LEFT JOIN vehicles v ON v.id=s.vehicle_id
WHERE s.deleted_at IS NULL
  AND ($3::text IS NULL OR s.status=$3)
  AND ($4::text IS NULL OR unaccent(lower(s.trip_no)) LIKE '%'||unaccent(lower($4))||'%')
ORDER BY s.created_at DESC LIMIT $1 OFFSET $2
`

type ListShipmentsParams struct {
	Limit  int32
	Offset int32
	Status *string
	Q      *string
}

type ListShipmentsRow struct {
	Shipment     Shipment
	DriverName   *string
	VehiclePlate *string
}

func (q *Queries) ListShipments(ctx context.Context, arg ListShipmentsParams) ([]ListShipmentsRow, error) {
	rows, err := q.db.Query(ctx, listShipments,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShipmentsRow{}
	for rows.Next() {
		var i ListShipmentsRow
		if err := rows.Scan(
			&i.Shipment.ID,
			&i.Shipment.TripNo,
			&i.Shipment.RouteFrom,
			&i.Shipment.RouteTo,
			&i.Shipment.DriverID,
			&i.Shipment.VehicleID,
			&i.Shipment.TransportCost,
			&i.Shipment.Status,
			&i.Shipment.DepartedAt,
			&i.Shipment.DeliveredAt,
			&i.Shipment.CreatedAt,
			&i.Shipment.UpdatedAt,
			&i.Shipment.DeletedAt,
			&i.Shipment.Version,
			&i.Shipment.CreatedBy,
			&i.DriverName,
			&i.VehiclePlate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSalesOrderStatus = `-- name: SetSalesOrderStatus :one
UPDATE sales_orders SET status=$2
WHERE id=$1 AND status=$3 AND deleted_at IS NULL RETURNING id, so_no, customer_id, ordered_on, status, created_at, updated_at, deleted_at, version, created_by
`

type SetSalesOrderStatusParams struct {
	ID         uuid.UUID
	ToStatus   string
	FromStatus string
}

func (q *Queries) SetSalesOrderStatus(ctx context.Context, arg SetSalesOrderStatusParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, setSalesOrderStatus, arg.ID, arg.ToStatus, arg.FromStatus)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.SoNo,
		&i.CustomerID,
		&i.OrderedOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const setShipmentStatus = `-- name: SetShipmentStatus :one
UPDATE shipments SET status=$2
WHERE id=$1 AND status=$3 AND deleted_at IS NULL RETURNING id, trip_no, route_from, route_to, driver_id, vehicle_id, transport_cost, status, departed_at, delivered_at, created_at, updated_at, deleted_at, version, created_by
`

type SetShipmentStatusParams struct {
	ID         uuid.UUID
	ToStatus   string
	FromStatus string
}

func (q *Queries) SetShipmentStatus(ctx context.Context, arg SetShipmentStatusParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, setShipmentStatus, arg.ID, arg.ToStatus, arg.FromStatus)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.TripNo,
		&i.RouteFrom,
		&i.RouteTo,
		&i.DriverID,
		&i.VehicleID,
		&i.TransportCost,
		&i.Status,
		&i.DepartedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const sumConfirmedSalesRevenue = `-- name: SumConfirmedSalesRevenue :one
SELECT COALESCE(SUM(l.qty*l.unit_price),0)::numeric
FROM sales_orders so JOIN sales_order_lines l ON l.sales_order_id=so.id
WHERE so.deleted_at IS NULL AND l.deleted_at IS NULL
  AND so.status IN ('confirmed','picking','shipped','closed')
`

// The dashboard's Выручка. Sourced from CONFIRMED sales orders only
// (docs/05-MODULES.md:65) — there is no finance module to ask.
func (q *Queries) SumConfirmedSalesRevenue(ctx context.Context) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, sumConfirmedSalesRevenue)
	var column_1 decimal.Decimal
	err := row.Scan(&column_1)
	return column_1, err
}
