// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at, ip, user_agent, created_by)
VALUES ($1, $2, $3, $4, $5, $1)
RETURNING id, user_id, token_hash, expires_at, revoked_at, ip, user_agent, created_at, updated_at, deleted_at, version, created_by
`

type CreateSessionParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	Ip        *netip.Addr
	UserAgent *string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, full_name, password_hash, is_active, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, full_name, password_hash, is_active, last_login_at, failed_attempts, locked_until, created_at, updated_at, deleted_at, version, created_by
`

type CreateUserParams struct {
	Email        string
	FullName     string
	PasswordHash string
	IsActive     bool
	CreatedBy    uuid.NullUUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.IsActive,
		&i.LastLoginAt,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
UPDATE sessions SET deleted_at = now()
WHERE deleted_at IS NULL AND expires_at < now() - $1::interval
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, retain pgtype.Interval) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions, retain)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT sessions.id, sessions.user_id, sessions.token_hash, sessions.expires_at, sessions.revoked_at, sessions.ip, sessions.user_agent, sessions.created_at, sessions.updated_at, sessions.deleted_at, sessions.version, sessions.created_by, users.id, users.email, users.full_name, users.password_hash, users.is_active, users.last_login_at, users.failed_attempts, users.locked_until, users.created_at, users.updated_at, users.deleted_at, users.version, users.created_by
FROM sessions
JOIN users ON users.id = sessions.user_id AND users.deleted_at IS NULL
WHERE sessions.token_hash = $1 AND sessions.deleted_at IS NULL
`

type GetSessionByTokenHashRow struct {
	Session Session
	User    User
}

// Deliberately does not filter on expiry or revocation: the domain layer
// distinguishes "unknown token" from "expired" from "revoked".
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.TokenHash,
		&i.Session.ExpiresAt,
		&i.Session.RevokedAt,
		&i.Session.Ip,
		&i.Session.UserAgent,
		&i.Session.CreatedAt,
		&i.Session.UpdatedAt,
		&i.Session.DeletedAt,
		&i.Session.Version,
		&i.Session.CreatedBy,
		&i.User.ID,
		&i.User.Email,
		&i.User.FullName,
		&i.User.PasswordHash,
		&i.User.IsActive,
		&i.User.LastLoginAt,
		&i.User.FailedAttempts,
		&i.User.LockedUntil,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.DeletedAt,
		&i.User.Version,
		&i.User.CreatedBy,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, email, full_name, password_hash, is_active, last_login_at, failed_attempts, locked_until, created_at, updated_at, deleted_at, version, created_by FROM users
WHERE lower(email) = lower($1) AND deleted_at IS NULL
`

// Identity and session queries. Consumed by internal/auth (T05).
//
// Every read filters deleted_at IS NULL (CLAUDE.md §4.3). The one exception is
// session lookup by token hash, which must find revoked and expired sessions so
// the domain layer can reject them with a precise reason instead of a generic 401.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.IsActive,
		&i.LastLoginAt,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, full_name, password_hash, is_active, last_login_at, failed_attempts, locked_until, created_at, updated_at, deleted_at, version, created_by FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.IsActive,
		&i.LastLoginAt,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT DISTINCT rp.resource, rp.action
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id AND r.deleted_at IS NULL
JOIN role_permissions rp ON rp.role_id = r.id AND rp.deleted_at IS NULL
WHERE ur.user_id = $1 AND ur.deleted_at IS NULL
ORDER BY rp.resource, rp.action
`

type GetUserPermissionsRow struct {
	Resource string
	Action   string
}

// A user's effective permissions are the union across all their roles
// (docs/04-RBAC.md §1). Resolved per request and never cached (04-RBAC.md:148).
func (q *Queries) GetUserPermissions(ctx context.Context, userID uuid.UUID) ([]GetUserPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserPermissionsRow{}
	for rows.Next() {
		var i GetUserPermissionsRow
		if err := rows.Scan(&i.Resource, &i.Action); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.id, r.key, r.name_ru, r.name_tg, r.name_en, r.is_system, r.created_at, r.updated_at, r.deleted_at, r.version, r.created_by FROM user_roles ur
JOIN roles r ON r.id = ur.role_id AND r.deleted_at IS NULL
WHERE ur.user_id = $1 AND ur.deleted_at IS NULL
ORDER BY r.key
`

func (q *Queries) GetUserRoles(ctx context.Context, userID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.NameRu,
			&i.NameTg,
			&i.NameEn,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLoginFailure = `-- name: RecordLoginFailure :one
UPDATE users
SET failed_attempts = failed_attempts + 1,
    locked_until = CASE
      WHEN failed_attempts + 1 >= $2::int
      THEN now() + $3::interval
      ELSE locked_until
    END
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, full_name, password_hash, is_active, last_login_at, failed_attempts, locked_until, created_at, updated_at, deleted_at, version, created_by
`

type RecordLoginFailureParams struct {
	ID          uuid.UUID
	MaxAttempts int32
	Lockout     pgtype.Interval
}

// Increments the counter and locks the account once the threshold is reached.
// Returning the row lets the caller report the resulting state without a re-read.
func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) (User, error) {
	row := q.db.QueryRow(ctx, recordLoginFailure, arg.ID, arg.MaxAttempts, arg.Lockout)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.IsActive,
		&i.LastLoginAt,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.CreatedBy,
	)
	return i, err
}

const recordLoginSuccess = `-- name: RecordLoginSuccess :exec
UPDATE users
SET last_login_at = now(), failed_attempts = 0, locked_until = NULL
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) RecordLoginSuccess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordLoginSuccess, id)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions SET revoked_at = now()
WHERE user_id = $1 AND deleted_at IS NULL AND revoked_at IS NULL
`

// Logout everywhere, required on password change (docs/03-API-CONTRACT.md:193).
func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now()
WHERE id = $1 AND deleted_at IS NULL AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const setPasswordHash = `-- name: SetPasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1 AND deleted_at IS NULL
`

type SetPasswordHashParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET expires_at = $2
WHERE id = $1 AND deleted_at IS NULL AND revoked_at IS NULL
`

type TouchSessionParams struct {
	ID        uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

// Idle-timeout support: slides the expiry window on activity.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.ExpiresAt)
	return err
}
